### ISSUE TITLE
Add a gamerule for season progression

### ISSUE THREAD

**Issue by Adubbz** [Glitchfiend/SereneSeasons#1]
As per title. This should be independent of `doDaylightCycle`, so players can have worlds where it is always day, but seasons progress.

**Comment by darloth** [comment]
It's been a year, and I'd find this really convenient, so I hope you won't mind me poking it.  I'll leave it for another year after this, unless of course I manage to learn how to do it myself in the meantime - in which case I'll send you a PR.  Presumably something in SeasonHandler.onWorldTick that checks a value that can be set via a command.
