### ISSUE TITLE
[Issue]Snow lying too long in non-winter season.

### ISSUE THREAD

**Issue by GrzechuGrek** [Glitchfiend/SereneSeasons#103]
Do exist a way, to melt snow a very lot quicker in spring and his instantly disappear in summer? 
Its strange, when in mid of spring or summer, a snow is lying in areas whose player don't visited since winter. Maybe implementing such mechanism/solution will resolve this problem?

**Comment by Forstride** [comment]
There are already multiple other issues similar to this.  We're going to be implementing something to help prevent snow from staying in unloaded chunks after winter is over.

**Comment by dantaeusb** [comment]
Sorry to bug you, but any updates on this? I think the feature to remove snow in unloaded biomes is cool, but could be too difficult to implement; and meanwhile, having snow ticks tweaked or something would make the big difference. If there's some config, please let me know – can't find anything related to melting speed. Playing on 1.19.2 with Snow! Real Magic and having snow lying late-autumn even though chunks were loaded ~half of the time. I was thinking to blame that mod but seeing snow not melted even on a regular blocks which are not tweaked.
