### ISSUE TITLE
Biomes Freezing

### ISSUE THREAD

**Issue by DrakeBD** [Glitchfiend/SereneSeasons#106]
Current version of the mod in the sunflower biome no matter what season it is its settling snow and freezing the water if its winter it snows and if its summer it rains so that works but rain is settling the snow so think its a bug

![2018-12-02_16 58 53](https://user-images.githubusercontent.com/1292832/49342560-db326980-f654-11e8-951f-e21a0145e46b.png)

**Comment by Forstride** [comment]
The snow isn't melting in summer?

**Comment by DrakeBD** [comment]
> The snow isn't melting in summer?

No its not even when its raining in summer the snow is still settling its rather odd lol

**Comment by Forstride** [comment]
I can't recreate this at all.  The only thing I can think of is some other mod is directly interfering and not allowing Serene Season's to properly override it.  Can you test this with *only* Serene Seasons installed?

**Comment by DrakeBD** [comment]
Could be a bug with dynamic surroundings or open terrain generator maybe will have to investigate it more to nail down the issue the issue was in the sunflower plains biome.

**Comment by DrakeBD** [comment]
I have nailed down the bug it seems to come from Dynamic Surroundings within any Plains biomes removing that mod and making a new world fixes it i will contact the dev with the bug report

**Comment by Exorno** [comment]
I can confirm through personal testing that this also gets caused by Dynamic Lights (by AtomicStryker)
