### ISSUE TITLE
*Suggestions* Add comments for suggested Season Durations

### ISSUE THREAD

**Issue by Deliphin** [Glitchfiend/SereneSeasons#111]
It's kind of annoying to have to calculate how long sub seasons need to be, and I think this mod should save people that convenience.

In seasons.cfg, we have this:

```
# The duration of a sub season in days [range: 1 ~ 2147483647, default: 7]
I:"Sub Season Duration"=7
```

I think this part should be modified to this:

```
# The duration of a sub season in days [range: 1 ~ 2147483647, default: 7]
# For 24/7 servers you might want to have a longer seasonal cycle.
# 1 week per full cycle: 42
# 1 week per season: 126
# 30 days per full cycle: 180
# 30 days per season: 540
# 1 year per full cycle: 2190
# 1 year per season: 6570
I:"Sub Season Duration"=7
```

As you can see I've already done the math, so you just have to add the comments.

**Comment by Insane-96** [comment]
Isn't the duration based off minecraft's days?
42 minecraft days are 14 hours not a week (168 minecraft days).
