### ISSUE TITLE
Some Traverse biomes have missing seasonal effects

### ISSUE THREAD

**Issue by Insane-96** [Glitchfiend/SereneSeasons#112]
Like Temperate Rainforest
It snows in winter but snow doesn't place itself.

**Comment by Forstride** [comment]
Do you have snow/ice generation disabled?

**Comment by Insane-96** [comment]
Nope,

Il 15 dic 2018 20:07, "Forstride" <notifications@github.com> ha scritto:

Do you have snow/ice generation disabled?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Glitchfiend/SereneSeasons/issues/112#issuecomment-447590868>,
or mute the thread

**Comment by Forstride** [comment]
Working fine for me.  Check your mod list and make sure something else isn't interfering

![2018-12-15_14 52 10](https://user-images.githubusercontent.com/1512908/50046895-141d0600-0079-11e9-91f3-d8310fa23c4c.png)

**Comment by Insane-96** [comment]
Should those biomes be wrote down in biome_info.json?

Il 15 dic 2018 20:52, "Forstride" <notifications@github.com> ha scritto:

Working fine for me. Check your mod list and make sure something else isn't
interfering

[image: 2018-12-15_14 52 10]
<https://user-images.githubusercontent.com/1512908/50046895-141d0600-0079-11e9-91f3-d8310fa23c4c.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Glitchfiend/SereneSeasons/issues/112#issuecomment-447593579>,
or mute the thread
