### ISSUE TITLE
*Compatability* Random Things Rain Shield

### ISSUE THREAD

**Issue by Mrbysco** [Glitchfiend/SereneSeasons#115]
I would like to request compatability with Random Things rain shield. Which normally stops rain from rendering in a 5 chunk radius but due to the changes with Serene Seasons it no longer works. Now it just stops the rain sound while still displaying rain.

**Comment by Forstride** [comment]
That really doesn't seem like something where the compatibility should be added on our end.  They likely use ASM to override various rain function's, which we do as well, but we have an API available which has hooks to check for whether it's raining/snowing by season, and it'd probably be much easier for them to add support than the other way around.

**Comment by Mrbysco** [comment]
Will poke them then. :)
