### ISSUE TITLE
Different spawn tables for specific seasons

### ISSUE THREAD

**Issue by Yoshi72** [Glitchfiend/SereneSeasons#116]
It would be nice to be able to change the spawn list for each biome for certain seasons, similiar to how crop growth works. For example, you could add slimes spawns to during spring, while removing them during the winter entirely (even in swamp biomes).

While not terribly important for vanilla minecraft, it would be really nice for mods and modpack creators.

**Comment by Forstride** [comment]
Changing it per biome *and* per season would be a bit too much.

We used to disable animal spawns completely in Winter, but it really messed things up, and even after Winter was over, animals wouldn't respawn.  So we're likely just not going to mess with it again in any form.
