### ISSUE TITLE
Mod compatiblity issue with Better With Mods causing an exception server tick look

### ISSUE THREAD

**Issue by kreezxil** [Glitchfiend/SereneSeasons#118]
## versions
Forge: 1.12.2-14.23.5.2796
Better With Mods: 1.12-2.3.20-1027
Serene Seasons: 1.12.2-1.2.15

## what's going on
Mods are having a fight over ice blocks and crashing my dedicated server

## server crash reports:
http://paste.ubuntu.com/p/TgFTt5wYbf/
http://paste.ubuntu.com/p/ms3QxsF4wq/

**Comment by kreezxil** [comment]
Also posted at Better With Mods: https://gitlab.com/BetterWithMods/BetterWithMods/issues/1289

**Comment by primetoxinz** [comment]
Not serene season's issue. Please close this and continue over at BWM
