### ISSUE TITLE
Setup our API properly

### ISSUE THREAD

**Issue by Adubbz** [Glitchfiend/SereneSeasons#12]
We've been very slack with this for our mods. I think this would be a good opportunity to do it properly. Stuff like package-info should be added, and maybe IMC support for biome blacklisting?

**Comment by Lanse505** [comment]
I'd love for this to be explored further somehow.
I'd like to add support for Serene Seasons out of the box for my new mod, however, as of currently It doesn't seem like there is an easy way to do this, outside of having end-users add the support :/
