### ISSUE TITLE
[BUG/Suggestion?] No snow in traverse:rocky_plains in winter

### ISSUE THREAD

**Issue by nick-johnson** [Glitchfiend/SereneSeasons#122]
https://github.com/Prospector/Traverse/blob/master/src/main/java/prospector/traverse/world/biomes/BiomeRockyPlains.java

https://github.com/Glitchfiend/SereneSeasons/blob/f67ed87d7cd00287d636769e5a1e7593ebc2ac76/src/main/java/sereneseasons/season/SeasonASMHelper.java#L185

Looks like the Traverse Rocky Plains biome is just outside the 0.8F cut-off for season change, its default temp is 0.9F. Not sure what Traverse's developer intended for snowfall for the biome, but I filed a suggestion on the Traverse issue tracker as well (https://github.com/Prospector/Traverse/issues/37).

**Comment by Forstride** [comment]
There's really nothing we can do about it on our end.  0.8 is our baseline between snowy and non-snowy, and that's not gonna change.  They register the Rocky Plains as a cool-type biome, so the temperature probably should be changed for accuracy's sake.

**Comment by nick-johnson** [comment]
Thanks for the info, @Forstride. Hopefully @Prospector agrees!
