### ISSUE TITLE
Cannot support multi world in spongeforge 1.12.2

### ISSUE THREAD

**Issue by Jecvay** [Glitchfiend/SereneSeasons#123]
the default [World] world is no problem
i create a new world named "kaka"
in "kaka", the **season-clock** wave all the time and will not stop
the **redstone light block** will not activate at any season.

--- [ mod list ] ---
SereneSeasons-1.12.2-1.2.15-universal.jar
LuckPerms-Sponge-4.2.17.jar
Nucleus-1.6.1-S7.1-MC1.12.2-plugin.jar
forge-1.12.2-14.23.5.2768-universal.jar
spongeforge-1.12.2-2768.jar

**Comment by Jecvay** [comment]
Update: the dim num of 'kaka' is 2
after add 2 to whitelist
the season-clock is still broken
but the redstoneblock will activate ok.

**Comment by Jecvay** [comment]
Update:
'World' is ok
'kaka":
- season-clock broken
- weather ok (winter-snow)
- environment broken ( tree's color will not change )

**Comment by ScarletDor** [comment]
这bug现在还有啊，为什么关闭了，不修复了？
