### ISSUE TITLE
Method Exception sereneseasons.season.SeasonASMHelper.getFloatTemperature

### ISSUE THREAD

**Issue by MishkaG** [Glitchfiend/SereneSeasons#124]
Weather2 via CoroUtil  is trying to call method with exception.

[Exception from Server Log](https://hastebin.com/xawunuwiro.css)

**Comment by dscime** [comment]
Can confirm.  Also using Weather2 / CoroUtil and am getting the same exception logged to my console.

Serene Seasons Version:  1.2.15

Forge Version:  14.23.5.2768

Weather2 Version:  2.6.12

CoroUtil Version: 1.2.15
