### ISSUE TITLE
[Suggestion] Snow border-gore fix

### ISSUE THREAD

**Issue by JustGalactic** [Glitchfiend/SereneSeasons#125]
The snow is extremely ugly in non-rendered chunks after winter is over. I am not a programmer or a developer, so this may not be possible. Though, I had an idea of how you could fix the ugly post winter snow. What if during winter, there was like a 'state' of winter depending on how long it has been going. So if it is a little bit through winter, and it has snowed, other chunks would update in relation to that. And when it becomes spring, the snow would disappear slowly, with a percentage, and all chunks would update to this percentage of how far the snow is gone. So when it is farther into spring, and you rendered a chunk that was last rendered in winter, it would update to the snow being 100% gone, and the snow would disappear before you would really notice it. Feel free to ask me if you don't understand. I am not the greatest at explaining things. It would also be wonderful if you made this compatible with weather2. Thank you very much for reading this!

**Comment by Forstride** [comment]
There's already an open issue for this (As well as a PR that implements it waiting for us to test and approve it).

As for Weather 2, it's on them to make it compatible, not us.
