### ISSUE TITLE
Cannot build cloned repo

### ISSUE THREAD

**Issue by vishtheshnu** [Glitchfiend/SereneSeasons#127]
I'm currently on a Windows 10 machine and copy the code via "git clone https://github.com/Glitchfiend/SereneSeasons.git" and try to build it with "gradlew setupDecompWorkspace idea". Trying to build it causes a crash with the following error: https://hastebin.com/dacicaxafu.http

It looks like it's a problem with mappings. Any chance this could be fixed? I want to try and add the ability to specify metadata for seasonal crops in the config, but I can't if I'm unable to build the project. Thanks!

**Comment by Jecvay** [comment]
i just run ```gradlew build ``` and ok

**Comment by Jecvay** [comment]
```de.oceanlabs.mcp``` what's this
