### ISSUE TITLE
Frozen/Snow-Covered rivers spawn in hot biomes

### ISSUE THREAD

**Issue by SirChamomile** [Glitchfiend/SereneSeasons#133]
In my last few worlds that I've played in, the rivers always spawn partially frozen and the banks are covered in snow. This often happens in desert biomes. Is this perhaps a conflict with Geographicraft? 

![2019-01-27_12 05 27](https://user-images.githubusercontent.com/23204608/51805158-b828ce00-222f-11e9-9fdd-a3de31f00397.png)

**Comment by Forstride** [comment]
Vanilla river biomes have snow disabled, so Geographicraft might not use vanilla biomes.

Maybe delete your biome_info.json file in the Serene Seasons config and let it regenerate to make sure that it properly updates.
