### ISSUE TITLE
[suggestion] ground warmth

### ISSUE THREAD

**Issue by DemonfangArun** [Glitchfiend/SereneSeasons#136]
Would it be possible to add an option where below a (configurable) y level crops from (configurable) seasons grew without greenhouse glass above, instead using the warmth of the earth?

**Comment by vedisdragon** [comment]
I'm running 1.12.2 SereneSeasons and Forestry's managed multifarm appears to grow vanilla crops regardless of season.

**Comment by DemonfangArun** [comment]
Well that doesn't seem right. For me it was following seasons fine, but it has been a while since I looked at it.

**Comment by DemonfangArun** [comment]
Sorry for the long delay. I'm not seeing the config option for this anywhere in the three files, even after letting them generate fresh.

**Comment by DemonfangArun** [comment]
Is this option not going to be made available to 1.12.2 users?

**Comment by Forstride** [comment]
No.  We don't support older versions.  It's enough work keeping one version updated

**Comment by DemonfangArun** [comment]
I figured as much, and I don't blame you. I'll see this in a couple years then when I actually get fully moved over to a newer Minecraft version (big mods move at a glacial pace).
