### ISSUE TITLE
Add config options to disable weather effects

### ISSUE THREAD

**Issue by Forstride** [Glitchfiend/SereneSeasons#14]
Another self-explanatory title

**Comment by Insane-96** [comment]
We should be able to disable single weather effects.

**Comment by Renk0u** [comment]
I'd love an option to disable snow piling up and ice forming.
Because I'm not a fan of walking into an unloaded chunk in summer and have snow everywhere.

Is it possible to visually keep it snowing instead of raining though? Just not create snow layers on the ground.

**Comment by Mike-U5** [comment]
I'm with @Renk0u, I'm not a fan of snow to begin with.

**Comment by lindseyrie** [comment]
I would like a way to turn off ice atleast, i don't mind the snow so much
