### ISSUE TITLE
Clock not showing correct season?

### ISSUE THREAD

**Issue by ZDongV** [Glitchfiend/SereneSeasons#140]
![2019-02-22_01 16 29](https://user-images.githubusercontent.com/47888112/53238599-8de0f980-3691-11e9-91b5-66a421112b96.png)

Running a small MC server with serene seasons and the clock doesn't seem to correlate with the seasons.

I'm not sure whether the clock is not showing the correct season or the season is not changing at all. But as can be seen in the screenshot above - manually setting the season to something else doesn't change the clock (set to autumn, clock says it's moving in to early spring). The clock periodically seems to wobble left/right but ultimately stays as in the screenshot. In the nether the clock spins and flies back and forward (as it should like a normal clock)

Possible conflicts on the server:
Pam's Harvestcraft
Tough As Nails
Local Weather, Storms & Tornadoes
OTG/Biome Bundle

Any ideas on this? Am I doing something stupid?

**Comment by Pirog17000** [comment]
got same issue using OTG + SereneSeasons.
We're playing mainly in dimension-2, not 0 (overworld) and this might be a reason why clock acts like this.
Yet, seasons act like normal - I've defined in config that dimension 2 should be used for seasons and only in this dimension they're working, not affecting the others. But clock seems to be broken for us as well.

**Comment by clootas** [comment]
Season's clock isn't working for me either, came here to post the same issue

**Comment by Mnesikos** [comment]
Hey, I wanted to let anyone still having this issue on a server that you need the same Serene Seasons config on your client as the server has, and that will get the season clock to work!
