### ISSUE TITLE
Seasons out of sync with clients

### ISSUE THREAD

**Issue by sammyp1003** [Glitchfiend/SereneSeasons#141]
I run a small 10-ish player server. An issue I observed is that if I set the subseason length to anything other than default, seasons will not sync properly with clients unless I distribute the serene seasons configuration files manually. 

For example, when setting the subseason length to 24 days, summer according to the server displays as the end of winter on the season clock for clients who have not manually synchronized their config file. It even snows for them during the summer (though only visually). Syncing the config file seems to fix the issue, but I'm not sure if that behavior is intended or not.

**Comment by Forstride** [comment]
Yes, you need to have the same config on the client as the server.
