### ISSUE TITLE
[Suggestion] No snow during summer in polar biomes

### ISSUE THREAD

**Issue by Captain26050** [Glitchfiend/SereneSeasons#143]
Hello, this is my first post here in github, so I'm sorry if there are any mistakes in it.
My suggestion only goes for polar biomes, where even in the summer, there is snowfall.
I would appreciate if the precipitation during the summer in these biomes was rain, not snow.
I'm putting this suggestion up based on real life weather observations, mostly in Alaska, USA.

**Comment by Forstride** [comment]
We're not changing biomes that are normally always snowy
