### ISSUE TITLE
[Bug] Seasons crops do not corrilate with visual season indication

### ISSUE THREAD

**Issue by PaxJaromeMalues** [Glitchfiend/SereneSeasons#145]
Hi folks,

we are running a small `forge-1.12.2-14.23.5.2824-universal.jar` server with the following modpack:

- AmbientSounds_v3.0.3_mc1.12.2.jar
- animania-1.12.2-1.6.2.jar
- AppleCore-mc1.12.2-3.2.0.jar
- AppleSkin-mc1.12-1.0.9.jar
- backpacks_1.12.2_-_3.5.5.jar
- base-1.12.2-3.12.0.jar
- BetterFps-1.4.8.jar
- BetterPlacement-1.0.0-1.jar
- BetterWithLib-1.12-1.5.jar
- BetterWithMods-1.12-2.3.20-1027.jar
- BiblioCraft[v2.4.5][MC1.12.2].jar
- BiomesOPlenty-1.12.2-7.0.1.2422-universal.jar
- buildcraft-all-7.99.23.jar
- Bullseye-1.12.2-3.0.7.jar
- CarryOn_MC1.12.2_v1.12.1.jar
- Clumps-3.1.2.jar
- CodeChickenLib-1.12.2-3.2.2.353-universal.jar
- ContentTweaker-1.12.2-4.9.1.jar
- CookingForBlockheads_1.12.2-6.4.69.jar
- CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar
- CraftTweaker2-1.12-4.1.17.jar
- CTMLib-MC1.7.10-1.4.1.5.jar
- DynamicLights-1.12.2.jar
- DynamicSurroundings-1.12.2-3.5.4.3.jar
- DynamicTrees-1.12.2-0.9.4.jar
- DynamicTreesBOP-1.12.2-1.4.1e.jar
- DynamicTreesPHC-1.12.2-1.4.2.jar
- FamiliarFauna-1.12.2-1.0.11.jar
- Farseek-1.12-2.3.1.jar
- findme-1.12.2-1.1.0-8.jar
- forestry_1.12.2-5.8.1.322.jar
- ForgeCraft-1.6.44.jar
- HardcoreDarkness-MC1.12.2-2.0.jar
- Hwyla-1.8.26-B41_1.12.2.jar
- ImmersiveCraft-1.12-1.5.1.jar
- jehc-1.12.2-1.6.3.jar
- jei_1.12.2-4.15.0.268.jar
- JustAFewFish-1.7_for_1.12.jar
- mcjtylib-1.12-3.1.1.jar
- memory_repo
- modtweaker-4.0.17.jar
- MTLib-3.0.6.jar
- OreLib-1.12.2-3.5.2.2.jar
- Pam's HarvestCraft 1.12.2zb.jar
- PrimalCore-1.12.2-0.6.104.jar
- reauth-3.6.0.jar
- SereneSeasons-1.12.2-1.2.15-universal.jar
- Streams-1.12-0.4.4.jar
- TCFastCraftingMod-2.6-mc[1.12-1.12.2].jar
- ToughAsNails-1.12.2-3.1.0.139-universal.jar
- Voice Chat Reloaded-1.0.1.jar
- wumpleutil-1.12.2-2.12.6.jar

and a few small CraftTweaker scripts for ImmersiveCraft which do not interfere with SereneSeasons AFAIK.

### What is happening:

We currently have set a subseason cycle of 180 minecraft days, as seasons continued to pass on rapidly on our 24/7 server. This should limit a full year cycle to one real life month as long as the server population will not sleep or otherwise skip any ticks.

We currently have the issue that the actual season is still **spring** (we tried to confirm this with planting crops of multiple season fertility and only the spring crops remained planted and actually grew), while the surrounding color scheme of the SereneSeasons currently shows the foilage colors of autumn.

Maybe someone can point us to possible settings/mods that cause issues with SereneSeasons.

**Comment by Forstride** [comment]
You need to same config on both the server and client (For all users).  This is likely what's causing it.

**Comment by PaxJaromeMalues** [comment]
oh damn, thanks a lot. We will try this. Is there a way how we can transmit the config from the server to all connecting clients?

btw, here is the funky screenshot of me breathing hot air in spring, dankily donkely
[Imgur](https://i.imgur.com/XnKFESf.jpg)

**Comment by Forstride** [comment]
No, you'll have to manually send the config to all users, which is really something that you should do anyway with a server, as there may be a handful of other config changes from other mods that the client doesn't have

**Comment by PaxJaromeMalues** [comment]
configs have been sync across clients. Everything seems to work now, thanks a lot!
