### ISSUE TITLE
[Feature request] Announce the day/season

### ISSUE THREAD

**Issue by MushWolf** [Glitchfiend/SereneSeasons#146]
This is a small feature request for the mod to announce the new day in chat when the player/server skips to day through sleeping or when a new day starts.

Some examples of this feature would could be:

[Serene Seasons] Spring. Day 1.
Winter. Day 28.
Summer. Day 29/31.

Using 1/7 instead of simply the day makes it so players on a server will always know the day/season when they join the server again and how many days are left in the season so what they need to plant.

**Comment by cody-greene** [comment]
The "season clock" is indecipherable so this would be a welcome change

**Comment by lebanni** [comment]
How about a calendar you hang at a wall and consult with a click, or maybe connected to opencomputer/computercraft and show the date on an screen.

**Comment by Forstride** [comment]
Don't think we're gonna add this since we have a new Calendar item that's far easier to interpret than the old Season Clock.  If you really want it announced in the chat though, that can most likely be done using the Season Sensor and Command Blocks.
