### ISSUE TITLE
[1.2.15] update to latest harvestcraft

### ISSUE THREAD

**Issue by ilvrak** [Glitchfiend/SereneSeasons#150]
for some of new harvestcraft crops not setted fertility seasons:

agave
sisal
cassava
chickpeas
lentils

huckleberry
kohlrabi
qinoa

jute

millet
jicama
green grape
mulberry

kenaf
arrowroot
taro

flax
amaranth
elderberry

**Comment by Forstride** [comment]
You need to delete your Serene Seasons config and let the game generate a new one, as those were added months ago, but can't be added to existing config files automatically.

**Comment by ilvrak** [comment]
i delete 'config/sereneseasons' folder. but new file still not contain these

**Comment by Forstride** [comment]
Are you using the latest version of Serene Seasons?  Because they're definitely there

**Comment by Forstride** [comment]
Actually, my bad.  I never made a build with the new Pam's HarvestCraft stuff.  I'll do that now, and it should be up on CurseForge shortly
