### ISSUE TITLE
Crash from trying to change seasons

### ISSUE THREAD

**Issue by ItzMeDB** [Glitchfiend/SereneSeasons#152]
from what i can tell, the game is trying to go to the next season but crashes instead, here is the crash report
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: sereneseasons.api.season.SeasonHelper.canSnowAtTempInSeason(Lsereneseasons/api/season/Season;F)Z

this info might also help 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  ItemPatchingLoader (ItemPhysic-Mod-Full-1.12.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.13.jar)
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/11/19 10:19 PM
Description: Unexpected error

java.lang.NoSuchMethodError: sereneseasons.api.season.SeasonHelper.canSnowAtTempInSeason(Lsereneseasons/api/season/Season;F)Z
	at org.blockartistry.DynSurround.registry.season.SeasonInfoSereneSeasons.canWaterFreeze(SeasonInfoSereneSeasons.java:84)
	at org.blockartistry.DynSurround.registry.season.SeasonInfoSereneSeasons.getPrecipitationType(SeasonInfoSereneSeasons.java:122)
	at org.blockartistry.DynSurround.registry.SeasonRegistry.getPrecipitationType(SeasonRegistry.java:126)
	at org.blockartistry.DynSurround.client.weather.StormSplashRenderer.addRainParticles(StormSplashRenderer.java:204)
	at org.blockartistry.DynSurround.client.weather.StormSplashRenderer.renderStormSplashes(StormSplashRenderer.java:79)
	at org.blockartistry.DynSurround.client.weather.RenderWeather.addRainParticles(RenderWeather.java:62)
	at net.minecraft.client.renderer.EntityRenderer.func_78484_h(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:430)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1827)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.blockartistry.DynSurround.registry.season.SeasonInfoSereneSeasons.canWaterFreeze(SeasonInfoSereneSeasons.java:84)
	at org.blockartistry.DynSurround.registry.season.SeasonInfoSereneSeasons.getPrecipitationType(SeasonInfoSereneSeasons.java:122)
	at org.blockartistry.DynSurround.registry.SeasonRegistry.getPrecipitationType(SeasonRegistry.java:126)
	at org.blockartistry.DynSurround.client.weather.StormSplashRenderer.addRainParticles(StormSplashRenderer.java:204)
	at org.blockartistry.DynSurround.client.weather.StormSplashRenderer.renderStormSplashes(StormSplashRenderer.java:79)
	at org.blockartistry.DynSurround.client.weather.RenderWeather.addRainParticles(RenderWeather.java:62)
	at net.minecraft.client.renderer.EntityRenderer.func_78484_h(EntityRenderer.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78464_a(EntityRenderer.java:430)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['ItzMeDB'/32, l='MpServer', x=33.85, y=91.00, z=145.49]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (208,64,164), Chunk: (at 0,4,4 in 13,10; contains blocks 208,0,160 to 223,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 58558 game time, 58558 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [GCEntityClientPlayerMP['ItzMeDB'/32, l='MpServer', x=33.85, y=91.00, z=145.49], EntityVillager['Villager'/38, l='MpServer', x=-19.95, y=63.94, z=75.41], EntityVillager['Villager'/39, l='MpServer', x=-19.01, y=63.94, z=75.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 871901384 bytes (831 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D2 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                          | Version                  | Source                                          | Signature                                |
	|:--------- |:--------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                   | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                         | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                       | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy           | 1.0.0                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | itemphysic                  | 1.4.0                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | ivtoolkit                   | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | micdoodlecore               |                          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | foamfixcore                 | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | antiqueatlas                | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | antiqueatlasoverlay         | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | examplemod                  | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
	| UCHIJAAAA | appleskin                   | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
	| UCHIJAAAA | appliedenergistics2         | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJAAAA | biomesoplenty               | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar   | None                                     |
	| UCHIJAAAA | buildcraftlib               | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftcore              | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftbuilders          | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcrafttransport         | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftsilicon           | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftcompat            | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftenergy            | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftfactory           | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | buildcraftrobotics          | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                    | None                                     |
	| UCHIJAAAA | camoucreepers               | 1.5                      | Camouflaged-Creepers-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | codechickenlib              | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks               | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chiselsandbits              | 14.29                    | chiselsandbits-14.29.jar                        | None                                     |
	| UCHIJAAAA | redstoneflux                | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | cofhcore                    | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                   | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | creativecore                | 1.7.4                    | CreativeCore-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | galacticraftcore            | 4.0.2.210                | GalacticraftCore-1.12.2-4.0.2.210.jar           | None                                     |
	| UCHIJAAAA | dsurround                   | 3.4.9.13                 | DynamicSurroundings-1.12.2-3.4.9.13.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                     | 3.4.9.13                 | DynamicSurroundings-1.12.2-3.4.9.13.jar         | None                                     |
	| UCHIJAAAA | dynamictrees                | 1.12.2-0.9.4             | DynamicTrees-1.12.2-0.9.4.jar                   | None                                     |
	| UCHIJAAAA | dynamictreesbop             | 1.12.2-1.4.1e            | DynamicTreesBOP-1.12.2-1.4.1e.jar               | None                                     |
	| UCHIJAAAA | fbp                         | 2.3.9                    | Fancy-Block-Particles-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | foamfix                     | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | galacticraftplanets         | 4.0.2.210                | Galacticraft-Planets-1.12.2-4.0.2.210.jar       | None                                     |
	| UCHIJAAAA | galacticraftfoods1122101357 | 1.0                      | Galaticraft-Foods-1.12.2-1.0.1.357.jar          | None                                     |
	| UCHIJAAAA | inventorytweaks             | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest                   | 1.12.2-7.0.67.844        | Iron-Chests-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | malisiscore                 | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHIJAAAA | malisisdoors                | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHIJAAAA | millenaire                  | Millénaire 7.2.1         | millenaire-7.2.1.jar                            | None                                     |
	| UCHIJAAAA | pixelmon                    | 7.0.5                    | Pixelmon-1.12.2-7.0.5-universal.jar             | None                                     |
	| UCHIJAAAA | sereneseasons               | 1.2.15                   | SereneSeasons-1.12.2-1.2.15-universal.jar       | None                                     |
	| UCHIJAAAA | thermalfoundation           | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalexpansion            | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics             | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | winterwonderland            | 1.2.2                    | WinterWonderLand-1.2.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ItemPatchingLoader (ItemPhysic-Mod-Full-1.12.1.jar)
  com.creativemd.itemphysic.ItemTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.13.jar)
  org.blockartistry.DynSurround.asm.Transformer
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GT 710/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz

i just want my mods to work, so please help
-ItzMeDB

**Comment by Forstride** [comment]
Updated Dynamic Surroundings
