### ISSUE TITLE
BetterPortals compatibility

### ISSUE THREAD

**Issue by Johni0702** [Glitchfiend/SereneSeasons#153]
[BetterPortals](https://github.com/Johni0702/BetterPortals) allows multiple worlds to be loaded on the client at the same time (by spawning fake players on the server, tunneling their packets to the client and swapping out mc.world, mc.player, etc. during packet handling/ticking/rendering as required).
> if the season changes the color of foliage and grass, then the opened betterportal provokes a constant reload of chunks between normal and seasoned

 (Johni0702/BetterPortals#88).

From quickly skimming over SereneSeasons' code, there's at least this static value which causes issues:
https://github.com/Glitchfiend/SereneSeasons/blob/31258d44484db5c1f69bdf4b33cd1cab5191b713/src/main/java/sereneseasons/handler/season/SeasonHandler.java#L70
If possibly, please change it to have one value per-world (Mixin, Capability, WeakHashMap, etc. however you see fit).
If you're aware of other parts in your code which assume there to be only ever one world loaded on the client, please update those as well.

**Comment by Forstride** [comment]
We're likely not doing anything else with the mod in 1.12.  We're still in the process of updating Biomes O' Plenty to 1.13/1.14, and that's gonna be taking up all of our time that we can devote to modding for the next few months, and then begins the process of doing the same for Serene Seasons and our other mods.

But, if you or anyone else has the time, you're welcome to make a PR and we'll try to look over it and merge it.

**Comment by SpGilbert** [comment]
hmm how long would it take to make this pull request most likely?

**Comment by Soulcrafter** [comment]
2 weeks and no pull request?
