### ISSUE TITLE
[Feature Request] Ocean biomes freeze

### ISSUE THREAD

**Issue by duncanwebb** [Glitchfiend/SereneSeasons#157]
Hi,

I'm playing the https://www.curseforge.com/minecraft/modpacks/real-tech pack and the ocean and deep ocean biomes are freezing in the winter. I don't really expect salt water to freeze unless it is adjacent to an icy biome. It seems to freeze very far out from the coast.

The picture shows how far the ice formed and it was further out than the glass, into deep ocean.

![ice-ocean](https://user-images.githubusercontent.com/4198031/61513739-55eea000-a9fe-11e9-968b-82f49c2691ed.png)

The request is for the oceans not to freeze more than a few blocks from the coast.

Dynamic Surroundings is in the pack, if this has an influence on the ice.

Many thanks.

**Comment by Forstride** [comment]
SS already *does* disable freezing in the oceans by default.  Either another mod is interfering, or your config isn't up to date.  It should list oceans, deep oceans, rivers, etc. in the blacklisted biomes section of the config.

**Comment by duncanwebb** [comment]
Thanks for the very quick reply, the config files are were of date. Now it is raining and not snowing.
