### ISSUE TITLE
Foliage Colour not synced on LAN servers.

### ISSUE THREAD

**Issue by IAMNameless9t9** [Glitchfiend/SereneSeasons#159]
Seasons work based on the host (for crops and precipitation), but leaf and grass colour is localized for each person when joining a LAN server. So for example, while the server may be in summer and will appear like summer for the host, connected players may see fall or winter coloured leaves and grass. Just a minor visual glitch that does not appear to affect performance or gameplay, but it is a bit confusing for other players.

**Comment by Forstride** [comment]
You need to make sure all players have the same config

**Comment by IAMNameless9t9** [comment]
Thanks a bunch. Can't believe I didn't think about that.
