### ISSUE TITLE
Resource Pack

### ISSUE THREAD

**Issue by MrRitsher149** [Glitchfiend/SereneSeasons#168]
Hello!
I want to play the mod with a resource pack, but with just using a regular one, the leaves and the grass wont change Color... what files do i have to add into the resource pack folder to make it compatible with the Color changing of the mod?
Thank you!!

**Comment by Forstride** [comment]
If the texture pack you're using doesn't use the grass/foliage colormap with grayscale grass/foliage textures, then it's not going to work.  Also, you need to make sure Swamp Colors are turned on in OptiFine if you're using that.

**Comment by MrRitsher149** [comment]
I tried a few different resource packs, all with a foliage and grass file in the colormap folder, but the Color auf the blocks wont change, it only Works in default resource pack (Swamp Colors Are turned on)
