### ISSUE TITLE
Change Birch leaf coloring throughout the seasons

### ISSUE THREAD

**Issue by beanaboston** [Glitchfiend/SereneSeasons#17]
Only oak leaves change right now. It'd be great if the other leaves changed color too. Maybe not spruce as that's supposed to be a pine tree (I think). And probably not jungle trees since they're tropical.

**Comment by Forstride** [comment]
I'm not sure if we'd be able to change birch colors, but I'd like to if it's possible.  Spruce colors shouldn't change though, because it's an evergreen tree.  Also, jungle leaves *do* change.  Any kind of block that uses the grass/foliage colormaps will change.

**Comment by beanaboston** [comment]
Hm. Good to know about the jungle leaves.
