### ISSUE TITLE
Client crash : unexpected error

### ISSUE THREAD

**Issue by lebanni** [Glitchfiend/SereneSeasons#171]
Version : SereneSeasons-1.12.2-1.2.17-universal.jar
Forge : forge-1.12.2-14.23.5.2838-universal.jar

Client crash at start.

[crash-2019-09-01_23.35.59-client.txt](https://github.com/Glitchfiend/SereneSeasons/files/3563967/crash-2019-09-01_23.35.59-client.txt)

**Comment by Forstride** [comment]
You'll need to wait for Dynamic Surroundings to update and support our recent changes
