### ISSUE TITLE
Seasons visual issue

### ISSUE THREAD

**Issue by ghostofatitan** [Glitchfiend/SereneSeasons#172]
Seems both 1.2.16 and 1.2.17 have the same issue on my server of the seasons change but it can not load the visual changes to the plants, it attempts to load each chunk to the color shift but reverts back, temp changes still work though so snows in biomes during winter etc. Also the seasons clock goes haywire and can not display what season it is.

*update* found the reason, when you change the sub season in days it causes this as it occurs in single player as well. I have it set to change sub season every 2160 days which is 30 days rl with progress while offline being true so it bugged out

**Comment by Forstride** [comment]
Yes, you need to have the same configs on both the server and client
