### ISSUE TITLE
NullPointerException Crash

### ISSUE THREAD

**Issue by CactusDuud** [Glitchfiend/SereneSeasons#175]
Has happened a few times now, 

[crash](https://pastebin.com/cVTBtUZn)
[and again](https://pastebin.com/XX31aKK)

**Comment by ALIAS-001** [comment]
Same. mine's happening in the getSeaasonState function
not sure how to fix
[log](https://paste.ee/p/ExHvW)

**Comment by Tommsy64** [comment]
This happens on the latest version (1.12.2-1.2.17) due the lack of null checks in the way Better Portals compatibility is implemented. If Better Portals compatibility isn't required, the quickest fix is to simply downgrade to 1.12.2-1.2.16.

**Comment by 0xebjc** [comment]
Is this the same root cause with issue #174, NPE at sereneseasons.handler.season.SeasonHandler.getClientSeasonTime?
