### ISSUE TITLE
Crash when changing dimension

### ISSUE THREAD

**Issue by BrisingrAerowing** [Glitchfiend/SereneSeasons#179]
[Crash Log](https://gist.github.com/BrisingrAerowing/82fbab47bd797a86d65a9f43249f5d67)

Happened while I was teleporting out of Random Things Spectre Dimension back to the overworld.

**Comment by IdrisQe** [comment]
I also have a crash when changing dimension. This has been noted to occur when using BetterPortals, I've yet to test with Vanilla portals as that's significantly slower to test. It doesn't occur all the time, but when it does, it can make the world unplayable until SS is removed.
The actual error is different to the one BrisingrAerowing is experiencing.
It seems to be an issue with tesselating the foliage color of leaves.
Note that although the crash mentions Ambient Environment, I've tested this without said mod and the crash still occurs.
https://pastebin.com/TeT7MAZe

**Comment by Forstride** [comment]
Should be fixed now in the latest update (Released today)
