### ISSUE TITLE
Crash - Serverside

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Glitchfiend/SereneSeasons#18]
https://gist.github.com/P3rf3ctXZer0/6dc2c08a11342595d3c5adb8cf5a3e8c

**Comment by QAngelusQ** [comment]
Same error message for server - SpongeForge 1.12.2 on Forge 2655

https://pastebin.com/2GkdUE1Q

**Comment by Dalethium** [comment]
Confirmed on mine as well, [Crash Report](https://pastebin.com/x183tqw0)

**Comment by Forstride** [comment]
Can you try downgrading Forge temporarily to see if it fixes it?  If that's the case, we'll need to update the mod to use a newer Forge verison.

**Comment by QAngelusQ** [comment]
This is for SpongeForge 1.12.2 on Forge 2611

https://pastebin.com/aYw10huc

**Comment by Forstride** [comment]
Might be a SpongeForge issue that we can't fix then.  They're known to cause issues with a lot of mods due to how much they change to the base game, so we can't guarantee that we'll be able to do anything.

**Comment by Dalethium** [comment]
I am not running spongeforge, just regular forge with a bunch of mods and I experience this issue as well.
