### ISSUE TITLE
Crops growing during wrong seasons

### ISSUE THREAD

**Issue by TheRedBow** [Glitchfiend/SereneSeasons#180]
i'm playing on a personal server that me and 1 other player play on, but for some reason both potatoes and wheat grow at the same time, while potatoes are a spring crop and wheat is summer/autumn

**Comment by TheRedBow** [comment]
the crops are planted in a river biome, and keep growing there, they act normally in other biomes, i have not changed anything in the config about rivers, and it doesn't have tropical seasons on it

**Comment by TheRedBow** [comment]
i tought i fixed it by enableing season effects in the riverbiome, so i closed it, but then i relaunched the server, and the issue wasn't fixed, i'll keep looking but i'll take any advice

**Comment by Forstride** [comment]
You need to make sure you have the same config on both the server and client
