### ISSUE TITLE
Crash on restarting the game in other dimensions

### ISSUE THREAD

**Issue by Romz24** [Glitchfiend/SereneSeasons#181]
If I try to restart the game while in a different dimension, when I try to log back into the server I will always get a crash. The error is also accompanied by a flood in the chat.

![I-O2L0P8fFk](https://user-images.githubusercontent.com/2458113/65897289-9f247e00-e3b7-11e9-83cd-e9d2e0ceafb6.jpg)

**Crash log:**
* [https://paste.dimdev.org/anuzofamox.mccrash](https://paste.dimdev.org/anuzofamox.mccrash)
* [https://paste.dimdev.org/izurofofat.mccrash](https://paste.dimdev.org/izurofofat.mccrash)
* [https://paste.dimdev.org/ropokuquze.mccrash](https://paste.dimdev.org/ropokuquze.mccrash)
* [https://paste.dimdev.org/hagonujavi.mccrash](https://paste.dimdev.org/hagonujavi.mccrash)

**Comment by Forstride** [comment]
Should be fixed now in the latest update (Released today)
