### ISSUE TITLE
Compatability PVJ, climatic biomes and Husbandry 

### ISSUE THREAD

**Issue by SpGilbert** [Glitchfiend/SereneSeasons#182]
https://www.curseforge.com/minecraft/mc-mods/hsbdryhttps://www.curseforge.com/minecraft/mc-mods/climatic-biomes
https://github.com/mc-jt9/ProjectVibrantJourneys 
I'm requesting if these mods that add biomes are not compatible with the season feature of this mod. That you add the seasons to these biomes.

**Comment by SpGilbert** [comment]
also gave a possible solution to bug #50 in the comments of that bug.

**Comment by Forstride** [comment]
We already have support for Climatic Biomes.  Husbandry was only created 5 days ago and only has 52 downloads, and also doesn't have a source available.  Project Vibrant Journeys only adds a few biomes and I'm not sure if they even need support.

We're also not going to be doing anything else with 1.12, but you're more than welcome to just add this stuff to your own configs.

**Comment by SpGilbert** [comment]
ok
