### ISSUE TITLE
possable /sereneseason setseason command fix

### ISSUE THREAD

**Issue by SpGilbert** [Glitchfiend/SereneSeasons#183]
When you press the tab for the command to determine the season. My solution is to have 12 different choices, one for the early, mid and late parts of each season. The following choices early_spring, mid_spring, late_spring ,early_summer, mid_summer, late_summer, early_autumn, mid_autumn, late_autumn, early_winter, mid_winter and late_winter. Just have it when you use the tab button for the _____  in the /sereneseasons set season ______. the 12 mentioned above fill the blank.

**Comment by Forstride** [comment]
Closing this as it's no longer relevant in 1.14/1.15
