### ISSUE TITLE
Server-related crash within the first 5-10 minutes of starting a new world on latest 1.12.2 release.

### ISSUE THREAD

**Issue by bokuwaTel** [Glitchfiend/SereneSeasons#184]
Hi.
I run a modpack, so this could be any number of things, but seeing as Serene Seasons is the one mod that has the _most_ to do with server tick loop (timing) and whatnot, especially in a new world, I thought this would be the best place to start for trying to troubleshoot my issue. I have no clue what's going on in this crash log, I'm going to have to mention that, because essentially all I see is an error with chests causing a feedback issue in the server tick loop. This only started happening as of my October update to my pack, and didn't once happen beforehand, in which I updated this mod and maybe two or three others. My blood sugar was running high at the time as I'm going through personal problems, which is relevant because it causes difficulty with brain functions and thus thinking processes are slower, so I could well have smeffed something while updating my modpack for the month, but I digress.
If anyone could help me with troubleshooting this issue that I can only assume to be caused by this mod's most recent update due to the fact that the aforementioned biological issue caused me to not have the energy to keep a log of what all I did in said update, it would be much appreciated. Attached is the crash log, it's been repeated constantly and it's always when I start a new world. It seems to resolve after the first time, as far as I'm aware, however it is _incredibly_ annoying and I can imagine it causing frustration amongst less patient users than myself.
Thank you.
[crash-2019-10-05_16.21.09-server.txt](https://github.com/Glitchfiend/SereneSeasons/files/3693747/crash-2019-10-05_16.21.09-server.txt)

P.S.: Yes, I always feel the need to explain myself so in-depth on the internet, as people seem to be quite apt to just be incredibly rude, so I apologize.

**Comment by Forstride** [comment]
This has nothing to do with Serene Seasons
