### ISSUE TITLE
Natura Redwoods

### ISSUE THREAD

**Issue by CynicalShrew** [Glitchfiend/SereneSeasons#185]
Natura redwoods seem to be affected by the changing leaf colors, while BoP redwoods aren't. It'd be nice if the Natura ones were consistent with that. Not a huge issue, just something I noticed about since I have a base in a pair of them.

**Comment by Forstride** [comment]
BOP redwoods aren't affected because they don't use foliage coloring at all, whereas Natura's do.  There's nothing we can do about this, and we're certainly not implementing a block blacklist

**Comment by CynicalShrew** [comment]
Yeah, that's fair. Like I said, not a major issue, mostly just preference.
