### ISSUE TITLE
Crops don't grow when bellow Fertile Soil and greenhouse.

### ISSUE THREAD

**Issue by Kodworgen** [Glitchfiend/SereneSeasons#188]
I tried to do an underground farm by layers, and I used the greenhouse to help. 
I also used Fertile Soil, which is from Rustic Mod and allow crops to grow without water.
But when I finished, it turns out only the crops directly below the greenhouse 
( the first layer) grew up.
 So I used normal dirt to test and found out that this bug just happens with fertile soil.

I don't know if I should have contacted the rustic's owner or you, so sorry for any 
inconvenient.

**Comment by Forstride** [comment]
Just gonna close this because I'm really not sure what you even mean, and it's possibly an issue with Rustic and not us.
