### ISSUE TITLE
EntityRenderer crash at startup

### ISSUE THREAD

**Issue by ddelaparte** [Glitchfiend/SereneSeasons#19]
https://pastebin.com/myFqBUFQ

**Comment by ddelaparte** [comment]
Latest 1.1.0 version. Looks like maybe incompatibility with MultiMC.

**Comment by Dalethium** [comment]
Similar crash here too, I am also using MultiMC - [Crash Report](https://pastebin.com/ZfXZU1cs)

**Comment by Adubbz** [comment]
I have attempted to fix this. I doubt it's MultiMC, it would be one of the coremods you have installed. If the above fix doesn't work then I'd need to know exactly which mod it is before I can do anything else.

**Comment by ddelaparte** [comment]
Still not fixed for me. And it's Optifine. The crash is caused by an incompatibility with Optifine.
