### ISSUE TITLE
[feature request] Dimension Season locking

### ISSUE THREAD

**Issue by Riernar** [Glitchfiend/SereneSeasons#190]
Hi @Forstride,
Would it be possible to add an option to lock certain dimensions into a fixed, eternal dimension (e.g. always winter, always summer...) ?

If the per-dimension season only supports season-locking (e.g. a dimension either follows the global season cycle, or is locked into a fix dimension - there is only one season cycle), that would be fine.

I can help a bit with the code if needed, though I'll have to learn how SereneSeason works.

Thanks for considering !

**Comment by Riernar** [comment]
By the way @Forstride, are PR fine with SereneSeasons' license ? Since it is not allowed to 'Share Adapted materials' ?

**Comment by Forstride** [comment]
yes PRs are allowed

**Comment by Riernar** [comment]
Nice ! I'll see what I can do.
I also saw that TAN was discontinued. Is there any plan to allow adapted material for TAN to allow a fork/continuation ?

**Comment by Forstride** [comment]
no

**Comment by Forstride** [comment]
Just gonna close this.  No PR was made, and we're likely not gonna add it ourselves.  Seasons work on a global timer, so it'd likely require too much overhauling, and it's just not worth it when it'd be a very niche feature.
