### ISSUE TITLE
[Feature Request] Stop Seasons when nobody is online

### ISSUE THREAD

**Issue by nyctodarkmatter** [Glitchfiend/SereneSeasons#191]
Can you add a config option that stops the seasons from moving when nobody is online (obviously this would only affect servers)? Because of the way the time is set up it's almost always winter when my friends can play which is less fun, it'd be nice if we could experience all the seasons by having them pause when nobody is online. Alternatively you could just add an option pause the daylight cycle when nobody is online which would (effectively) pause the seasons. Would be incredibly nice

**Comment by Forstride** [comment]
There already is one...

**Comment by nyctodarkmatter** [comment]
Uh, where? I've checked all the Serene Seasons config files and can't find it.

**Comment by AllieWade** [comment]
In my install it's time settings\"Progress Season While Offline" (line 29 for me), in \config\sereneseasons\seasons.cfg.

**Comment by netWilk** [comment]
Check the configuration file in \world\serverconfig rather than the usual \config folder
