### ISSUE TITLE
[1.12.2] Serious bug: changing the day/night cycle in the config does nothing

### ISSUE THREAD

**Issue by Nikedemos** [Glitchfiend/SereneSeasons#194]
I wanted the Minecraft day to be JUST A LITTLE BIT longer. 28800 ticks to be exact.

In real world, there's 20 ticks per second - so a Minecraft minute is actually closer to a IRL second. I'm going to treat it as such. Why not make a Minecraft minute last exactly 1 IRL second, then?

[20 ticks * 24 * 60 = 28800. Here's my config. Didn't change anything but the numbers (day length and subseason length).](https://pastebin.com/5GeGdiuc).

So imagine my disappointment when I performed /time set 28700, Only to get Day 2, 10:45 AM (roughly). So as far as Minecraft (and SereneSeasons) is concerned, the day still operates on a 24000 tick cycle.

Am I completely missing the point here? Did I assume SereneSeasons actually has the ability to change a day/night cycle length, while in reality you have to get a different mod for that? And the only point of putting the value in the config is so that SS knows when to increment the day count by 1?
[I have about 68 mods installed, none of them's supposed to be messing with date/time. But for posterity sake, here it is (from an unrelated crash report, I crashed the game on purpose so I could get a quick rundown of mods).](https://pastebin.com/K3QQWAGi).

**Comment by Shivaxi** [comment]
Pretty sure the day duration setting in serene seasons is meant only for the season timer, and allows you to change it to MATCH other mods that change day cycle length, not change the actual day cycle length directly.

**Comment by Nikedemos** [comment]
As far as I know there's only 1 mod that can adjust the day length [Longer Days](https://www.curseforge.com/minecraft/mc-mods/longer-days) out there for 1.12.2 - and it operates on multipliers, you don't put the ticks directly.

So what's the point of having that in the config, really? For future-proofing reasons, or is that an atavistic remnant of the better times?

Either way, thanks for clearing that up. I might just fork the source and see if there's any way around it.
