### ISSUE TITLE
Strange Reaction with Dynamic Trees and Serene Seasons?

### ISSUE THREAD

**Issue by Flapcats** [Glitchfiend/SereneSeasons#195]
Something that I've noticed in cooler climates such as Taiga is the presence of trees covered in snow with no snow covering the ground in Spring/Autumn/Winter with both Dynamic Trees and Serene Season enabled.

![2019-10-23_15 01 45](https://user-images.githubusercontent.com/56931628/67425495-18258880-f5a6-11e9-8005-79091222b257.png)
Picture above is a spawning of a fresh world with Serene Seasons in Summer which I then set to Spring/Autumn/Winter, showing fresh chunks of taiga having snow covering the trees but not on the ground.

![2019-10-23_14 47 00](https://user-images.githubusercontent.com/56931628/67425509-207dc380-f5a6-11e9-8085-b07e3dcb1af2.png)
Not sure which side is causing this or if this is intentional, but I wanted to point it out.

**Comment by Elmfeather7** [comment]
Same as me! I have both mods, It also snows on mountains/Taiga, I'm meant to be spawning in spring, Wonder which mod is the cause...?

**Comment by Forstride** [comment]
This is most likely caused by Dynamic Trees.  I'm not sure how their tree spawning works exactly, but it might be generating the snow on the trees itself

**Comment by roccscout** [comment]
> Same as me! I have both mods, It also snows on mountains/Taiga, I'm meant to be spawning in spring, Wonder which mod is the cause...?

Did you ever find the culprit? I have the same issue.
