### ISSUE TITLE
randomized starting season only spawns you in summer

### ISSUE THREAD

**Issue by Shivaxi** [Glitchfiend/SereneSeasons#197]
In the config we have:

The starting sub season for new worlds.  0 = Random, 1 - 3 = Early/Mid/Late Spring, 4 - 6 = Early/Mid/Late Summer, 7 - 9 = Early/Mid/Late Autumn, 10 - 12 = Early/Mid/Late Winter [range: 0 ~ 12, default: 5]

So I set:

I:"Starting Sub Season"=0

For randomized starting seasons, however you always spawn in summer, either early mid or late summer, never any of the other seasons.

Using latest version for 1.12.2

**Comment by Shivaxi** [comment]
of coursed as I post this, I just got a spawn in mid autumn.  We tried literally 12 worlds that all started in summer haha.  was that just incredibly bad luck or is something a bit unbalanced?

**Comment by Elmfeather7** [comment]
I've recently changed the config to be random, but I only get spawned in the end of winter, No other season. I've made manymanymanymany worlds to test and yeah, Was there another mod conflicting with this one? or was there something you changed that fixed this issue? thanks for any info :)
