### ISSUE TITLE
[Important Bug Report!] Being able breaking everything what also includes bedrock in survival mode.

### ISSUE THREAD

**Issue by jjfurkan** [Glitchfiend/SereneSeasons#198]
I placed a greenhouse glass and placed seed under it and I broke the greenhouse glass. After that I could break everything in that y coordinates. **I fell out of the world in survival mode** while I trying mode. Please fix it.

**Comment by floral-qua-floral** [comment]
I'm not the dev, but I got curious and tried to replicate this. I tried multiple different ways to recreate the bug you're talking about, but nothing's happening.

Did you have any other mods installed? If you try doing this again, does it cause the same issue this time as well or is it inconsistent? The mod's developers will have a much easier time tracking down and fixing the bug if they're able to reproduce it themselves, and this kind of information is super useful for that.
