### ISSUE TITLE
Strange interaction with worldedit, sand layers instead of snow

### ISSUE THREAD

**Issue by Eowyn13** [Glitchfiend/SereneSeasons#199]
So  I noticed, that when I'm using the worldedit command //snow in winter in regions with lots of water like beach, river or swamp, there are sometimes small areas where there are layers of sand instead of snow layers. I can't really find a reason why this is happening, as those areas completely change when I undo and redo the //snow command and it does not seem to be related to any biome borders or anything similar.

**Comment by Forstride** [comment]
Report it to them?  There's likely nothing we can do about it, because it's likely not being caused by us
