### ISSUE TITLE
Crops growing in wrong season (still happening,?) 1.12.2

### ISSUE THREAD

**Issue by Elmfeather7** [Glitchfiend/SereneSeasons#200]
So I've read the closed issue of this same problem and my sugar cane grows no matter what season it is, I've tested out other crops from both vanilla and PHC and I have the same issue reguarding a few of those crops, I think its cause I'm near a river? Not really sure but it might be a factor. I have the most recent update for 1.12.2, and the most recent forge update (2847), Is there some code i need to change to stop this? Thanks! :)

Images of sugar cane growing in spring, but its set to summer only:

![2019-11-15_12 02 35](https://user-images.githubusercontent.com/37834855/68908871-ae615e80-07a0-11ea-8868-14fea7c8f7a9.png)
![2019-11-15_12 02 53](https://user-images.githubusercontent.com/37834855/68908879-b3bea900-07a0-11ea-9d3d-7fb06a12fe84.png)

**Comment by Elmfeather7** [comment]
Well I've done more testing, Seems like in rivers, villager garden beds and pre generated crops can all grow no matter the season.

**Comment by Kehaan** [comment]
Just wanted to say i have the same issue. But it is with any crops xD I can even use bonemeal on them outside of a season. Strange.

**Comment by Kehaan** [comment]
Any chance you have Hungeroverhaul installed? I think it is conflicting with it :)

**Comment by Forstride** [comment]
Rivers are blacklisted biomes that aren't affected by seasons, so any crop can grow there
