### ISSUE TITLE
Crops dont grow under ground

### ISSUE THREAD

**Issue by CowHItFace** [Glitchfiend/SereneSeasons#201]
Hey,
my crops arent growing under the ground although i got enough greenhouse glass for the whole farm. Do the crops still sunlight to grow?

**Comment by DarkShadow44** [comment]
Crops should still need light, yes.

**Comment by Forstride** [comment]
Crops do not need sunlight.  Also you need to make sure the greenhouse glass is within the required distance above the crops

**Comment by ZeroKnight** [comment]
@CowHItFace If you're using the 1.12.2 version, the underground fertility feature won't be available. From what I can gather, it was added not long after the 1.12.2 version.

The docs neglect to mention differences between versions; I was confused for quite a while as to why underground growing wasn't working until I perused the source and wiki revisions.
