### ISSUE TITLE
Port to Version 1.7.10

### ISSUE THREAD

**Issue by kuxii2016** [Glitchfiend/SereneSeasons#202]
Can port this mod to Forge 1.7.10?

**Comment by Adubbz** [comment]
We have no plans to backport any of our mods.

**Comment by DarkShadow44** [comment]
@Adubbz I understand that you won't backport yourself, would you accept a pullrequest for a 1.7.10 version?

**Comment by Adubbz** [comment]
If someone else wants to backport it then a PR would indeed be accepted

**Comment by DarkShadow44** [comment]
@Adubbz I have a working 1.7.10 version now, mind creating a branch (based on current master) so I could create a PR? Thanks in advance!

**Comment by Adubbz** [comment]
Done!

**Comment by DarkShadow44** [comment]
@Adubbz 
Will there be an official release of the 1.7.10 version, and if not, are we allowed to share a binary version?

**Comment by Adubbz** [comment]
I've uploaded a build now

**Comment by DarkShadow44** [comment]
@Adubbz Great, thanks!
