### ISSUE TITLE
[Compatibility Issue] Simulated Nights jumps several days' worth of seasons

### ISSUE THREAD

**Issue by Sweddy** [Glitchfiend/SereneSeasons#204]
I know asking for compatibility patches for other mods is a bit needy, but this is something I simply can't explain.

['Simulated Nights'](https://www.curseforge.com/minecraft/mc-mods/simulated-nights) is a small mod that simulates the remaining night-time ticks while the player is sleeping. The number of ticks simulated is equal to the number of ticks remaining until daytime. Weird thing is, despite this being only about 10% of Serene Seasons' season duration, it inexplicably skips about two seasons ahead. The number of ticks per day is set to 24000 in the Serene Seasons config.
What's also weird is the fact that this other mod called [Invasions](https://www.curseforge.com/minecraft/mc-mods/hostile-worlds-invasions) also has to keep track of the days but Simulated Nights does not interfere at all with its cycle.

I'd try contacting the author of the Simulated Nights mod but they don't seem to update it anymore.

If there's already a solution somewhere that I'm missing I'd like to hear it.

**Comment by Forstride** [comment]
Just gonna close this.  We don't support 1.12 anymore, and if the author of the other mod isn't updating it anymore, there's nothing we can do.  It's likely an issue on their end anyway
