### ISSUE TITLE
Uncraftable things

### ISSUE THREAD

**Issue by DaveRainbowin** [Glitchfiend/SereneSeasons#212]
1.14.4 forge.
Tried to edit the crafting recipes myself and failed. I am sad. I can no longer tell what the season is without looking at leaves. I can still craft greenhouse. Can't craft 
Downloaded from curseforge

**Comment by Adubbz** [comment]
You need to update the mod, this has already been fixed

**Comment by DaveRainbowin** [comment]
I was just about to say that. 40 seconds late
