### ISSUE TITLE
Seasonal crop list

### ISSUE THREAD

**Issue by Alberto247** [Glitchfiend/SereneSeasons#214]
### What's the issue you encountered?
Apparently the fertility config is ignored by the mod. Adding a crop(i tried using both the simplefarming and the xlfoodmod) doesn't set it's fertility to the specified seasons. The tooltip doesn't appear(it is enabled) and it still grows in every season except winter.
Moreover also removing a minecraft crop from the list doesn't work, it keeps the tooltip, and it still grows only in the season that were specified.

### How can the issue be reproduced?

The mod i had installed were JEI, HWYLA, Serene Seasons, xlfoodmod and simplefarming

### Logs

[debug.log](https://github.com/Glitchfiend/SereneSeasons/files/4007088/debug.log)

### Mod Version

SereneSeasons-1.14.4-2.0.0.14-universal

**Comment by resinate** [comment]
can confirm this on latest version, and carrots dont grow at all
