### ISSUE TITLE
Set season doesn't work

### ISSUE THREAD

**Issue by Darkness2796** [Glitchfiend/SereneSeasons#218]
when i run the command it sends me this message, I did it as the wikki says 

06.01 03:29:57 [Server] Server thread/INFO [minecraft/DedicatedServer]: Could not parse command: No enum constant sereneseasons.api.season.Season.SubSeason.early_spring
06.01 03:29:57 [Server] Server thread/INFO [minecraft/DedicatedServer]: ...rly_spring<--[HERE]

**Comment by Forstride** [comment]
You have to use all caps as it shows in the autocomplete.  I'll fix it in the wiki

**Comment by Darkness2796** [comment]
when I press tab for the autocomplete doesn´t show how to write the subseason 
![Anotación 2020-01-06 034205](https://user-images.githubusercontent.com/42597148/71806331-88389c00-3036-11ea-9172-84f6e5c82210.png)

**Comment by Forstride** [comment]
What version of the mod are you using?

**Comment by Darkness2796** [comment]
Nevermind i used the caps and it worked, thanks
