### ISSUE TITLE
Why do potatoes only grow in spring in the dafult config?

### ISSUE THREAD

**Issue by Khris777** [Glitchfiend/SereneSeasons#223]
Potatoes grow throughout most of the year in nature, from spring to autumn, depending on the climate zone, why are they limited to spring in the default config file?

**Comment by Forstride** [comment]
A lot of crop listings are based on Stardew Valley's crops, as well as basic Google searches I did.  Potatoes generally seem to be a cooler season plant, but I feel like they're appropriate for Spring only
