### ISSUE TITLE
Don't remove broken greenhouse glass or sensors

### ISSUE THREAD

**Issue by Seegras** [Glitchfiend/SereneSeasons#224]
## Feature Request

Greenhouse glass or the season sensor should not vanish upon being broken.

### What feature are you suggesting?

Greenhouse glass or the season sensor should not vanish upon being broken.

### Why should it be added?

Both blocks aren't cheap, and it's a nuisance. And if somebody would suspect a bug first, it's always a misfeature.

**Comment by Forstride** [comment]
Forgot to add the loot table for the Season Sensor block drop, which I fixed in the latest commit, but Greenhouse Glass *should* break IMO.  It is glass after all, and the newer recipe doesn't require dye, so it's really not *that* expensive.

**Comment by Seegras** [comment]
For 4 glass, it should produce 4 greenhouse glass, otherwise it IS expensive.

**Comment by Forstride** [comment]
The idea is that the glass is "compressed" to provide better heating.  You're making it for the purpose of growing out of season crops, not for decoration or whatever.
