### ISSUE TITLE
Console commands not working?

### ISSUE THREAD

**Issue by Kazekai** [Glitchfiend/SereneSeasons#226]
Hello. :) I'm trying to use the commands to change the seasons for testing purposes on a custom instance.

The commands listed here don't appear to do anything though?
https://github.com/Glitchfiend/SereneSeasons/wiki/Commands

/ss getseason produces no information. Nothing appears in the chatlog. Nothing appears on-screen.

/ss setseason lists NO ID's or common names for seasons. Typing in /ss setseason spring returns an invalid message in chat.

There is no information on the wiki about how to use these commands. The lack of feedback on the getseason command leads me to believe it isn't working correctly, and there's no information anywhere online that could tell me what the problem is on my end. Could someone help me?

I'm running MC version 1.12, Forge 2847.

**Comment by Forstride** [comment]
You need to at least include the version you're using

**Comment by Kazekai** [comment]
I'm sorry. I edited the initial post with the omitted info when I realized I'd forgotten it.

I'll repeat it here though, since your reply was so quick. :O 

MC version 1.12
Forge version 2847

**Comment by Forstride** [comment]
"For bugs that occur with Serene Seasons for 1.15.1. We do not support older versions!"

getseason is only in 1.15, and setseason is different between both versions.  In 1.15 it has autocomplete, and on versions below it uses lowercase, so..."/ss setseason early_spring"

**Comment by Kazekai** [comment]
Thank you. Sorry, I... didn't know there were mods out for MC past 1.12 yet. This helps me test my instance though, I appreciate your time.

**Comment by MrRedstoneA1** [comment]
Just adding a quick note. I thought the clock was broken when I viewed it in JEI interface. I never actually crafted it. Turns out the clock has to be in your inventory to display the correct season. In the JEI interface it just shows the same season all the time. Don't make the same mistake I made and spend 30 minutes hunting down an answer. I hope this saves someone some time.

**Comment by Devilswarchild** [comment]
i just tried the /ss setseason command on 1.12.2 and no matter which season I input i get an "Invalid Season" in response to the command.

also using the latest version is Serene Seasons on 1.12.2
