### ISSUE TITLE
generate_snow_ice config doesn't work

### ISSUE THREAD

**Issue by NillerMedDild** [Glitchfiend/SereneSeasons#227]
## Bug Report

During the winter, water freezes despite the config being set to false.

### What's the issue you encountered?

During the winter, water freezes despite the config being set to false.
I checked out the source, and it looks like the methods used to check if snow/ice should be a thing during the winter is commented out.

### How can the issue be reproduced?

* Make a new world. 
* Change the season to any winter season.
* Place water in a hole
* Wait for it to freeze

### Logs

Nothing about SS in the logs.

### Mod Version
SereneSeasons-1.15.1-3.0.0.43-universal

**Comment by yuhshii** [comment]
Generate snow and ice set to false also seems to prevent the snow and ice from melting, but not forming. At least on my server

**Comment by DoomSquirter** [comment]
using SereneSeasons-1.15.2-3.0.0.69-universal and problem still exists.  

I don't see this as a minor bug tho.  if a config option is ignored, that's definately an obvious bad bug.

every winter I keep on having to switch it to another season and do a command line to get rid of all the ice near my base.  I'd disable the mod but I don't like doing that normally.  

also, same as yuhshii stated.  ice forms and never melts on it's own.

**Comment by DoomSquirter** [comment]
pinging for awareness/visibility since ticket is closed already but problem still persists.
@Forstride @Adubbz

**Comment by Forstride** [comment]
?  It's not closed lol

Also you don't need to ping us, we have notifications every time an issue gets a comment.  Anyway, it's up to Adubbz to fix, and IDK when he'll get around to it.  Both of us are kind of taking a short break from Minecraft modding though.

**Comment by DoomSquirter** [comment]
lol my bad.  that's what I get for githubbing before caffeine after waking up ... sorry about that.  I saw the other ticket closed status and brain didn't connect right.

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.

**Comment by EQGShadow** [comment]
Im not sure if its supposed to be fixed or not, but this issue is still around in 1.16.5 - 4.0.1.89. Rather than seasons, this mod has effectively made my whole world icy and snowy. I don't mind ice and snow, I just want it to disappear fully by the end of spring.

**Comment by AccountofShame** [comment]
this problem is still not fixed, swamp seasonal effects are set to true in my config file, but still nothing happens in swamps.

**Comment by Forstride** [comment]
> this problem is still not fixed, swamp seasonal effects are set to true in my config file, but still nothing happens in swamps.

That has nothing to do with this issue.  You need to disable tropical seasons for swamps.

**Comment by mcjojo3** [comment]
This is still an Issue in version: SereneSeasons-1.16.5-4.0.1.91-universal which is outdated I know but I was wondering since the thread isn't closed if that's still the case with the newest version?

**Comment by Adubbz** [comment]
This has been fixed in the 1.18 version which will be released soon.
