### ISSUE TITLE
Calendar bugs out.

### ISSUE THREAD

**Issue by Stygan** [Glitchfiend/SereneSeasons#231]
Well, first bug report i make.

I'm hosting a server, and changed the config file of this mod, changed the duration of a subseason from 7 to 20, just to make them las longer.

The thing is that the calendar works well whit the 7 days schedule, but when it is other than 7, it doesen't work.

I tested it a bit, and from what i can understand, the calendar still count seven days to change it's graphic, althogh in game the seasons work fine with the 20 days cycle.

So, for instance, if i'm on day 18 of early_spring, calendar shows the graph of late_spring. And when i'm on day 1 of mid_spring, calendar shows graph of early_summer.

Using the last version available.

Hope it's understandable. Not my main language

**Comment by Forstride** [comment]
Do you have the same config file on the server *and* client?  They both need to be the same, otherwise issues like this will appear with client-side things.

**Comment by Stygan** [comment]
Ohh, yes, that was the problem. Didn't know that, sorry for the issue and thanks :)
