### ISSUE TITLE
Server packets(?) not being sent to client

### ISSUE THREAD

**Issue by coph1563** [Glitchfiend/SereneSeasons#232]
## Bug Report

[ Server packets not being sent  to the client  ]</br>

### What's the issue you encountered?

 I am running the recommended version of a Forge server (forge-1.15.2-31.1.0) with SS version SereneSeasons-1.15.2-3.0.0.62-universal . Seasons aren't lining up, crops don't really change behavior. In general, the server and client don't seem to be linked, communicating, and it makes the mod unplayable for multiplayer.  </br>
Also, the season's commands do not work on the server. (at all, doesn't show up)</br>

### How can the issue be reproduced?

With only SS installed with the previously stated version (same version of forge and ss on client and server) (the config files are exactly equal)
This is all on a local machine connecting with localhost, although other players get the same error when joining from other locations.
1.  start the server. 
2.  Join the server.
3. Error log from the server that tells me something cannot be serialized and will not be sent to the client.
4. Playing is not consistent with season time. (client is out of sink)...

Playing single player works as expected with functioning commands, even when opening to LAN(though I haven't tested with other players on LAN)
 </br>

### Logs

server:
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/4211457/latest.log)
[debug.log](https://github.com/Glitchfiend/SereneSeasons/files/4211534/debug.log)

client:
[debug.log](https://github.com/Glitchfiend/SereneSeasons/files/4211552/debug.log)
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/4211553/latest.log)

config (i copied and pasted them between server and client so theyre the same):
[config.zip](https://github.com/Glitchfiend/SereneSeasons/files/4211578/config.zip)

zip of logs for 31.0.1 : 
[forge 31.0.1.zip](https://github.com/Glitchfiend/SereneSeasons/files/4211617/forge.31.0.1.zip)

 </br>

### Mod Version
 SereneSeasons-1.15.2-3.0.0.62-universal </br>

**Comment by Adubbz** [comment]
I can't reproduce this on the latest version so this has likely already been fixed at some point.
