### ISSUE TITLE
korean language feels auto-translator flavor

### ISSUE THREAD

**Issue by MilkissWhite** [Glitchfiend/SereneSeasons#236]
## Feature Request

 Korean language file modify</br>

### What feature are you suggesting?

Now- 
"desc.sereneseasons.fertile_seasons": "비옥한 계절",
"desc.sereneseasons.year_round": "연중지속",

To be-
"desc.sereneseasons.fertile_seasons": "재배 시기",
"desc.sereneseasons.year_round": "일년 내내",
</br>

### Why should it be added?

 "비옥한 계절" and "연중지속" not wrong, but it feels translated too directly.
 actually, fertile_seasons show information about "when this crop can grow(or grow fast)?". in korea, commonly use "재배 가능한 시기 = season can grow", little shorten word "재배 시기" will fit better.
 year_round show information about "season name". "연중지속" mean all-year continue. it's not wrong but not fit for "whenever you want" taste. "일년 내내" is easier to understand.
</br>

**Comment by Forstride** [comment]
We don't do the translation ourselves, nor do we read/speak the languages, so I'd rather not make changes based on one person's suggestion.  Take it up with the person that made it: https://github.com/Glitchfiend/SereneSeasons/pull/230
