### ISSUE TITLE
Config setting for duration of each season separatley

### ISSUE THREAD

**Issue by SirSmuggler** [Glitchfiend/SereneSeasons#237]
## Feature Request

We can change the lenth of seasons in the config which is great. It would be even greater though if we could change the duration of each season independently.</br>

### What feature are you suggesting?

The ability to determine the length of each season independently via config settings instead of just one length setting that apply to all four seasons.</br>

### Why should it be added?

It gives the player more ways to customise the mod to suite their taste. F.ex. I realy like the changeing seasons, but I do find I get enough of winter long befor it's over, and spring feels like it barley begins befor it is over.</br>

**Comment by Forstride** [comment]
This really wouldn't be possible without completely changing how our seasons work, and it would not be worth the effort when it's a very niche request, and one that we don't really see a need for.
