### ISSUE TITLE
more realism

### ISSUE THREAD

**Issue by mrstuffem** [Glitchfiend/SereneSeasons#238]
### What feature are you suggesting?

[ across the x axis weather stays constant and warm along 0. across the z axis weather gets more diverse/harsh ]</br>

### Why should it be added?

[ just an extra level of realism and immersiveness. ]</br>

**Comment by Forstride** [comment]
This really wouldn't make sense given how Minecraft's biomes generate, and with how our seasons are affected by biomes (As in, whether they're temperate or tropical).  You can use the Latitude generation option in Biomes O' Plenty if you want a similar effect.
