### ISSUE TITLE
Question: Are this mod compatible with BiomeTweaker spawn tweaks?

### ISSUE THREAD

**Issue by vpontin** [Glitchfiend/SereneSeasons#24]
Hi!
I begin to use SereneSeasons today but i have some questions about its per-season spawn changes and my [custom spawn tweaks made with BiomeTweker](https://github.com/superckl/BiomeTweaker/wiki/Basic-Script-Commands#addspawn) by @superckl.

I currently spawn wolves and oocelots and some biomes (other than the ones they spawn in vanilla), and in both i spawn as "CREATURE" instead of "MONSTER". Will they actually spawn? And will season changes tweak its spawn rates?

Thanks in advance for any answers!

**Comment by Forstride** [comment]
We've removed our Winter animal spawn prevention feature as of last night.  So it won't affect anything.

**Comment by ddelaparte** [comment]
@Forstride For the record, I kinda liked the reduced spawns in winter. Are there any plans to bring this back as a config option?

**Comment by vpontin** [comment]
In fact, a complete shutdown of creature spawning on winter is acceptable, i just want to know if at least on "middle" seasons my custom spawing would spawn. Or even if i could tweak the mob spawn entirely via SS instead of BT.

**Comment by vpontin** [comment]
Honestly i would love to have season-based spawns on addspawn. But this should be made on @superckl side, and i dont even know if an integration like this is possible
