### ISSUE TITLE
spring issue

### ISSUE THREAD

**Issue by Hjelm2002** [Glitchfiend/SereneSeasons#241]
## Issue Report
I've got an Issue with the spring season

### What's the issue you encountered?
So, when I launched my world with serene seasons installed and a couple of other mods, everythings worked perfectly fine. However, when summer arrived a problem occured. To make it simpe, everyday I got a different season working. So it was like this : one day spring, one day summer, one day spring etc..  until autumn, then, one day autumn, one day spring etc... So this is my problem, Spring invade my minecraft days on alternate days.

### How can the issue be reproduced?

I don't know
### Logs
I don't know wich log to choose
### Mod Version
SereneSeasons-1.14.4-2.0.0.40-universal.jar

**Comment by Forstride** [comment]
We do not support 1.14 anymore.  Please read when opening a new issue
