### ISSUE TITLE
How do you change the season lenght

### ISSUE THREAD

**Issue by edux2008** [Glitchfiend/SereneSeasons#245]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue with only Serene Seasons installed. ]</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Please put the version of the mod you were using here. ]</br>

**Comment by Adubbz** [comment]
Change the sub season length in the config file.
