### ISSUE TITLE
Overwrite World.isRainingAt()

### ISSUE THREAD

**Issue by CreativeMD** [Glitchfiend/SereneSeasons#247]
Hey there,
I'm the author of AmbientSounds. Many people have reported an issue with this mod. The raining sound is played even if it's snowing. Pretty sure SereneSeasons does not implement an extra check for the temperature in `world.isRainingAt(BlockPos)`. Would it be possible to add it?

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.

**Comment by Forstride** [comment]
This should be fixed now with 1.16.4 (Yet to be released)

**Comment by Moleculor** [comment]
Was this in v4.0.0.82? Trying to figure out if this is still an issue:

https://github.com/Snownee/SnowRealMagic/issues/100

**Comment by Adubbz** [comment]
This specific issue has been fixed for awhile, yes. We do this here: https://github.com/Glitchfiend/SereneSeasons/blob/SS-1.16.x-4.x.x/src/main/java/sereneseasons/mixin/MixinWorld.java#L34-L58
