### ISSUE TITLE
Seasonal Tooltips not working on modded items

### ISSUE THREAD

**Issue by Volskygge** [Glitchfiend/SereneSeasons#249]
### What's the issue you encountered?

I have Simple Farming installed, as well as Pam's Harvestcraft 2 and the tooltips saying which seasons they grow in don't appear for them, but they appear for vanilla items.</br>

### How can the issue be reproduced?

I have no idea. I checked in the config files and all of the ID's are there. This has been an issue since I installed the mods.

### Mod Version

SereneSeasons-1.14.4-2.0.0.40-universal
simplefarming-1.14.4-1.2.8
pamhc2crops-1.14.4-1.0.4

**Comment by Volskygge** [comment]
I should specify that it's just the tooltips that aren't showing for me; the crops are following the fertility config properly.

**Comment by Forstride** [comment]
We do not support 1.14 anymore, and this issue was already fixed in 1.15
