### ISSUE TITLE
Doesn’t Load Correctly

### ISSUE THREAD

**Issue by mjhavelin** [Glitchfiend/SereneSeasons#252]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

It doesn’t load. It throws up a warning.</br>

### How can the issue be reproduced?

Step 1: Download latest version of Forge (31.1.47) Step2: Download Serene Seasons Latest Version.
Step 3: Load Minecraft Forge and get an error message</br>

### Logs

https://pastebin.com/HNidXDfW </br>

### Mod Version
Latest Version </br>

**Comment by Forstride** [comment]
You're trying to use the 1.12.2 version on 1.15.2...
