### ISSUE TITLE
Compatible with SnowRealMagic?

### ISSUE THREAD

**Issue by Artemis2017** [Glitchfiend/SereneSeasons#253]
Hello,

is this Mod compatible with SnowRealMagic? It doesn´t seems so. Can you make it compatible pls?

If i let it snow the Slabs/Bricks doesn´t covered in. If i uninstall Serene Seasons the Slabs/Bricks covered in snow and i let it 30 Minutes or more snowing!

![grafik](https://user-images.githubusercontent.com/25553095/80100602-75f45680-8570-11ea-9f5c-78fb1a8bea76.png)

MC Version: 1.15.2
Forge: 31.1.47

![grafik](https://user-images.githubusercontent.com/25553095/80100618-7ab90a80-8570-11ea-8f51-c3d01ec070a5.png)

**Comment by Forstride** [comment]
They'd have to add compatibility on their end, as they're probably changing a lot more in their snow method override than we are
