### ISSUE TITLE
Calendar flickers and displays wrong season.

### ISSUE THREAD

**Issue by Effectstudios** [Glitchfiend/SereneSeasons#254]
### What's the issue you encountered?

 Calendar flickers and displays wrong season.
 </br>
### How can the issue be reproduced?

 Not sure, launched the world/server and the problem appeared.</br>
### Logs

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/4565664/latest.log) </br>
### Mod Version
 3.0.0.69</br>

**Comment by Forstride** [comment]
Do you have the same config on the client *and* server?

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.
