### ISSUE TITLE
Add Command to Pause Season Cycle

### ISSUE THREAD

**Issue by EmDash00** [Glitchfiend/SereneSeasons#255]
### Add command to pause season cycle

Something like `/gamerule doDaylightCycle false`

### Why should it be added?

For people playing around in creative mode, having seasons changing can be annoying (especially winter). This would be a minor quality of life improvement to modpack makers like myself that spend a lot of time in creative.

I can also see many creative builders having this same issue.

In the same vein, map makers might want specific seasons for what they're making. Can also imagine some other modpack makers allowing dynamic season progression based on game stages using this (as a compliment to the command block compliance)

**Comment by McMark1441** [comment]
This would also be very useful for servers. When I leave my server running, even when no one is on, the season seem to continue.

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.

**Comment by Forstride** [comment]
Added in 1.16.4
