### ISSUE TITLE
Rain in snow biome 

### ISSUE THREAD

**Issue by DamienBrittan** [Glitchfiend/SereneSeasons#260]
### What's the issue you encountered?
I was flying around the world and found out that biome - Frozen Forest from BBOP (
Biome Bundle O Plenty ) is full of water (because ice melted) and it's rains instead of snowing , and some other snow/cold/ice biomes act like this (not all) . Is there a way to fix this ? Any way to add biome to the list of  non react to seasons ? 

### Mod Version
[ 1.12.2 ]

**Comment by Forstride** [comment]
It's almost certainly because the biome's temperature isn't actually set low enough to be a "real" snowy biome.  It likely wouldn't snow there even in vanilla.

**Comment by DamienBrittan** [comment]
But , how do i change it's temperature ?

**Comment by Forstride** [comment]
BiomeTweaker maybe?  This isn't really something Serene Seasons can or should handle.  If their biome isn't cold enough to have actual snow, there's probably a reason for it.
