### ISSUE TITLE
White leaves, or no leaves on trees during winter option in config? With the exception of spruce trees and leaves.

### ISSUE THREAD

**Issue by CaptainRick218** [Glitchfiend/SereneSeasons#262]
I just think it would be slightly more immersive if trees (except spruce trees), 
should turn either white or have no leaves that grow back in spring, and spruce trees should have green leaves in all seasons.

Cause in real life, the only trees that keep leaves, and don't change color in winter are evergreens, 
which spruce trees closely resemble evergreen trees.
If possible, add it as an option you can turn on or off, cause not everyone will like it.

And if someone wanted to backport it to 1.12.2, 
they could just open the 1.15 jar file as a zip, and copy the new file version of the winter version of the leaves from 1.15.2, 
and paste it over the old one in 1.12.2.

**Comment by Forstride** [comment]
I don't really like this idea.

Also...

> And if someone wanted to backport it to 1.12.2,
> they could just open the 1.15 jar file as a zip, and copy the new file version of the winter version of the leaves from 1.15.2,
> and paste it over the old one in 1.12.2.

That is not how modding works _at all_
