### ISSUE TITLE
Custom times for eastern, christmas . . . 

### ISSUE THREAD

**Issue by FarLokus** [Glitchfiend/SereneSeasons#263]
### What feature are I suggesting?

[ Custom time setting in configs and datapack ]</br>

I want to setup by custom times in the world.
So I can better create maps with Christmas and easter times.
Or Holidays in worldtimes.

### Why should it be added?

Not all countrys have got hollydays in self time.
Maybe you can create an evantmaker for setting up  times manually.

Sorry for the english. I`m german.

For an example the daytime of minecraft is 8 minutes.

[ 8 * 365 ] : 4 = 730 min ( 12,1666 h ) / season
[ 8 * 365 ]      = 2920 min ( 48,666 h ) / year

on server we can better give the time for 2days (real) a minecraft year.

[ 8 * 358 ] = christmas time
[ christmas time + { 7 * 8 } ] = happy new year ]

Thanks

FarLokus

**Comment by Forstride** [comment]
I really don't know what you're asking.  Serene Seasons doesn't add holidays or anything.  If you're saying you want the mod to match real-time, there are add-ons that can do that like RealSerene.
