### ISSUE TITLE
1.12.2 is bugged 

### ISSUE THREAD

**Issue by BattalGazii** [Glitchfiend/SereneSeasons#266]
## Feature Request

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What feature are you suggesting?

[ Provide an overview of the feature being suggested. ]</br>

### Why should it be added?

[ Describe the benefits of implementing this feature. ]</br>

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.

**Comment by Forstride** [comment]
First of all, for the love of God DO NOT SPAM COMMENTS on every single open issue with some unrelated problem.  Second, we do not support 1.12.2 anymore as it says when opening a new issue, and even if we did, you have given NO useful info at all, nor can I even understand half of what your comment is trying to say.  You are on your own on this one.

**Comment by Pinecone6442** [comment]
@Forstride imagine screaming lmao also you're bald and theres nothing you can do about me xd
