### ISSUE TITLE
Tropical Seasons not working correctly?

### ISSUE THREAD

**Issue by IceaPlayzPC** [Glitchfiend/SereneSeasons#270]
I noticed that the weather in the tropical seasons doesn't seem to be working properly in the latest 1.15.2 beta. In mid-dry season, it still rains in jungle biomes (Biomes O' Plenty biomes included), and vice versa where it does not rain during mid-wet season in hot biomes such as the savannah or desert. I've made sure i had the seasons correct (late summer/early autumn for dry season and late winter/early spring for wet season respectively) but still the regular weather. The Serene Seasons version i'm on is 1.15.2-3.0.0.74 (latest one released 4 days ago as of this post).

**Comment by Forstride** [comment]
Yeah we're aware.  It kind of just never got fixed since we were in-between updating BOP and stuff and waiting for 1.16.  Hopefully when we update to 1.16 I'll make sure Adubbz fixes it.

**Comment by IceaPlayzPC** [comment]
Alright awesome! Thanks for the answer, and take your time ^^ There's absolutely no rush xD

**Comment by Forstride** [comment]
Fixed for the 1.16.4 version (Yet to be released)
