### ISSUE TITLE
Snow logged blocks

### ISSUE THREAD

**Issue by MegaGamer265** [Glitchfiend/SereneSeasons#271]
Blocks like stairs, slabs, fences and plants such as flowers or grass should have snow on the same block, and snow could pile up when there are snow storms (also pile up on stairs slabs etc). It will look great if that works!

**Comment by Forstride** [comment]
There are other mods that do this kind of thing.  Definitely not adding this to SS itself though, as it'd be way too intrusive and make it harder to remove the mod from an existing world without as many issues.
