### ISSUE TITLE
Can't open Minecraft with mod installed due to "Missing License Information"

### ISSUE THREAD

**Issue by Lululipes** [Glitchfiend/SereneSeasons#272]
## Bug Report

"Missing License Information in file Mod File: "<i> Then it shows the address to the mod installed in the .minecraft\mod folder </i>
</br>

### How can the crash be reproduced?

Open Minecraft through Forge with the mod installed (I can't even get to the title page)</br>

### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/5550610/latest.log)
[crash-2020-11-16_20.03.07-fml.txt](https://github.com/Glitchfiend/SereneSeasons/files/5550609/crash-2020-11-16_20.03.07-fml.txt)
</br>

### Mod Version
SereneSeasons-1.15.2-3.0.0.74-universal.jar </br>

**Comment by Forstride** [comment]
You're trying to use Serene Seasons on 1.16.3, when it's not updated for it.
