### ISSUE TITLE
[Dev Environment Crash] NoSuchFieldError: GRASS_COLOR_RESOLVER

### ISSUE THREAD

**Issue by znaxcy** [Glitchfiend/SereneSeasons#273]
## Bug Report

Crashes on run, 1.15.2 with forge 1.15.2-31.2.8, latest SS and today's MCP mapping.</br>

### How can the crash be reproduced?

Fresh dev environment--> set up Serene Seasons API from curseforge repo in build.gradle using: `    runtimeOnly fg.deobf("com.github.glitchfiend.biomesoplenty:SereneSeasons:1.15.2-3.0.0.74:universal")
    compileOnly fg.deobf("com.github.glitchfiend.biomesoplenty:SereneSeasons:1.15.2-3.0.0.74:api")` --> run</br>

### Crash Report and Logs

https://pastebin.com/CnGhntzR</br>

### Mod Version
1.15.2-3.0.0.74</br>

edit: updated log link

**Comment by ajruckman** [comment]
Hi, did you find a solution to this?

**Comment by znaxcy** [comment]
I have not yet, no.

**Comment by Adubbz** [comment]
This was an issue caused by us using Mojang's mappings prior to when it was "standard". Given most others will also be using these mappings now it should no longer be an issue.
