### ISSUE TITLE
[1.16.4] Oh The Biomes You'll Go support

### ISSUE THREAD

**Issue by Cixon** [Glitchfiend/SereneSeasons#274]
## Issue Report

[ Suggestion: BYG support. ]</br>

### What's the issue you encountered?

[ BiomesYoullGo biomes not supported in latest Seasons build. ]</br>

### How can the issue be reproduced?

[ N/A ]</br>

### Logs

[ N/A ]</br>

### Mod Version
[ SS v4.0.0.78 | BYG v1.1.5 ]</br>

**Comment by Forstride** [comment]
Serene Seasons works with all biome mods automatically.  The only thing it won't support by default is blacklisted biomes and whatnot, but you can add that to the config manually.
