### ISSUE TITLE
Calendar bug!

### ISSUE THREAD

**Issue by Dragonslayer7532-dev** [Glitchfiend/SereneSeasons#275]
### What's the issue you encountered?

[ Some of the calendar's seasons are missing and going back to fall 1st   ]</br>

### How can the issue be reproduced?

[ download mod run set season to summer 2nd and there you go ]</br>

### Logs

[ i don't have logs rip ]</br>

### Mod Version
 4.0.0.77 (1.16.4) </br>

**Comment by Forstride** [comment]
I'm really not sure what you mean by this.  By Fall 1st are you referring to Early Autumn, and Summer 2nd instead of Mid Summer?

**Comment by Dragonslayer7532-dev** [comment]
Yeah

**Comment by Forstride** [comment]
Oh, I think I know what it is.  You're in a tropical biome and seeing the Dry Season icon.  It's supposed to be a flame, but I guess it kind of looks like a leaf.

**Comment by Dragonslayer7532-dev** [comment]
Ohhhhh i feel like a idiot

Sry for wasting your time
