### ISSUE TITLE
Green Houses!

### ISSUE THREAD

**Issue by Dragonslayer7532-dev** [Glitchfiend/SereneSeasons#276]
### What feature are you suggesting?

Green house Glass 

### Why should it be added?

I find it a pain for my some of my plants to not grow in winter So THE GREEN HOUSE GLASS (pog?)
the plant will check if there is a air gap then green house glass above it and if so then it will grown with out the season being the right one + you can add Ice glass where some plants (that can only grow in winter)  They can grow in any season!
or a plant light that let's it grow inside in any season!

**Comment by Forstride** [comment]
Greenhouse Glass was removed.  You can use regular glass/stained glass instead.

Please read the wiki for further information on crop fertility and other mechanics before opening a new issue.
