### ISSUE TITLE
Crash issue, Ticking Player caused by Serene Seasons

### ISSUE THREAD

**Issue by LordDecay26** [Glitchfiend/SereneSeasons#28]
The game crashed whilst ticking player
The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: sereneseasons.api.season.SeasonHelper.getSeasonState(Lnet/minecraft/world/World;)Lsereneseasons/api/season/ISeasonState;

**Comment by Forstride** [comment]
Gonna need a bit more info than that...

Either way, you likely just need to make sure any mods you have that have Serene Seasons support are using the latest version (Namely TAN, which had support using the old API name)

**Comment by Forstride** [comment]
Well I can't do anything without the actual crash report
