### ISSUE TITLE
Synchronize Server and Client

### ISSUE THREAD

**Issue by Moleculor** [Glitchfiend/SereneSeasons#281]
Since the server is the one in charge of determining gameplay (where a zombie spawns, whether it's day or night, whether a plant grows, etc), changing/tweaking the season settings on the server should change how players connecting to that server experience the world *without* also requiring manual updates to client-side config files.

**Comment by Dracmpire** [comment]
That would be great, and also solve the mid-summer snowstorm problems in my server.

**Comment by Adubbz** [comment]
This has been done in the 1.18 version which will be released soon.
