### ISSUE TITLE
[Feature Idea] Falling leaf particles from trees during autumn in applicable biomes.

### ISSUE THREAD

**Issue by Corvus20** [Glitchfiend/SereneSeasons#285]
The addition of falling leaf particles from trees during autumn, similar to the ones from Coro's Weather 2 or Autumnity.

During autumn, trees in biomes affected by the season change will begin to occasionally shed leaf particles matching their leaf color, and these particles drift in the wind.

Adding such a small touch to this mod would make such a difference in atmosphere. Currently, I have been unable to find a mod that can do such a thing for more than one biome, for modern minecraft versions.

**Comment by Forstride** [comment]
This would be a bit out of scope for the mod IMO, and for it to look good, we'd have to add it for every leaf type, including modded leaves.  And with the mod being kind of intensive already (Mainly when it snows), this really isn't something I want to add.

There are other mods that add similar features like Better Foliage, which will hopefully update to 1.16.4 soon.
