### ISSUE TITLE
Server crash for no reason

### ISSUE THREAD

**Issue by Wolfixsp** [Glitchfiend/SereneSeasons#286]
### What's the issue you encountered?

having a weird crash with my server, this started randomly and without player
https://pastebin.ubuntu.com/p/XzczMY9YW3/

### Logs

https://pastebin.ubuntu.com/p/XzczMY9YW3/

### Mod Version
SereneSeasons-1.12.2-1.2.18-universal.jar

**Comment by Forstride** [comment]
We don't support versions below 1.16.4
