### ISSUE TITLE
Commands are unknown.

### ISSUE THREAD

**Issue by aikiyo** [Glitchfiend/SereneSeasons#287]
### What's the issue you encountered?

I started up a new world, and when I went to change the weather it wouldn't let me and said it was an unknown command. Even though it came from the wiki. I do have cheats enabled so I don't understand what's the problem. Help?

### How can the issue be reproduced?

By typing in 
/season set EARLY_SPRING
![image](https://user-images.githubusercontent.com/77201128/104094904-d132ba00-5261-11eb-85fb-90499073a05c.png)
</br>

### Logs

I do not think there are any I can find.</br>

### Mod Version
1.15.2

**Comment by Forstride** [comment]
The command is /ss setseason on 1.15.2, which we do not support anymore.
