### ISSUE TITLE
Cant get stick from leaves

### ISSUE THREAD

**Issue by unikub0** [Glitchfiend/SereneSeasons#289]
### Mod Version
Newest version on 10 January 2021</br>
### Intro
I want to play with No Tree Punching mod and this mod, in No Tree Punching, i must get flint and to make a flint knife and get the plant fiber and then make a plant string and make the flint axe for break some trees.</br>
### Problem
I can't get stick from leaves, and that is only one way to get stick. And the problem is from this mod.

**Comment by Adubbz** [comment]
I can confidently say this is nothing to do with Serene Seasons. We don't touch drops from blocks _at all_.
