### ISSUE TITLE
Panel indication Seasons, date, etc.

### ISSUE THREAD

**Issue by amaury-d** [Glitchfiend/SereneSeasons#290]
First of all thank for your addon. We love it!

### What feature are you suggesting?

I'd like a small panel (like What are you looking at addon) that displays when a new day starts with: the date and the current season and a welcome message.

### Why should it be added?

It would add immersion and information to know when to take care of cultures.

**Comment by Forstride** [comment]
We're not really interested in adding a HUD for seasons.  Arguably it's more immersive when you have to actually look at your surroundings to see what season it is, or keep track of it yourself (Although we have the calendar that denotes what season/subseason it is).

**Comment by amaury-d** [comment]
Despite it would have been useful to me, I can understand your point of view.
