### ISSUE TITLE
Allow disabling glass growing crops out of season

### ISSUE THREAD

**Issue by froehlichA** [Glitchfiend/SereneSeasons#292]
## Feature Request

</br>

### What feature are you suggesting?

Provide config options to disable the "bees pollinating crops" and "glass allowing growth" features.</br>

### Why should it be added?

I'd like to further restrict players in how they grow crops and when, especially when playing on a server. Allowing players to grow crops regardless of the season if they only place it below a glass block is an amazing feature, but in my opinion players feel about it more "meh just place glass blocks above" than "oh now I have to plan ahead and think about when to best grow crops".

Also, growing crops below a certain y level can already be disabled with the `underground_fertility_level` config option. A `bees_grow_crops` and `glass_grows_crops` boolean toggle would compliment that option nicely. </br>

Also also, should probably not be that hard to implement.

Thanks in advance :D

**Comment by Forstride** [comment]
Bees aren't really an "intentional" design choice.  The way their AI works is hardcoded to advance the stage of crops, and I'm definitely not messing with mob AI just for that.

As for glass, I guess we could add an option for that eventually.

**Comment by froehlichA** [comment]
Oh! Didn't know that about bees. Of course, that would be too big of a change then.

**Comment by Forstride** [comment]
This will technically be able to be done now (Once a new build is up with the block/item tag system) with a datapack and making an empty greenhouse_glass block tag list (With replace set to true).  Not gonna add a proper config option though, cause it's extremely niche
