### ISSUE TITLE
Crash with Survive

### ISSUE THREAD

**Issue by Maxi90909** [Glitchfiend/SereneSeasons#293]
## Bug Report

Crash and Unable to load up the World again(without crashing)

### How can the crash be reproduced?

In My Case: 1. Start up a World with the mods Survive, Serene Seasons, The Undefeatbles and The Undergarden. 2.Go to the Undergarden Dimension. 3. Garther materials for the Slingshot or just get the Slingshot from creative and Some Peebles. 4. Shot the slingshot. 5. Crash and Unable to load up the World or go in the World without it crashing and Kicking you out of the loaded Minecraft.

### Crash Report and Logs

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/5826272/latest.log)
[crash-2021-01-17_11.51.01-server.txt](https://github.com/Glitchfiend/SereneSeasons/files/5826273/crash-2021-01-17_11.51.01-server.txt)

### Mod Version
Serene Seasons 1.16.4-4.0.0.86 
Survive-1.16.4-3.0.11 
Undefeatables 1.1 - 1.16.4
The Undergarden 0.4.3

**Comment by Forstride** [comment]
You already opened an issue for this

**Comment by Maxi90909** [comment]
I know but this one is more specific than the other. Thats why I opened another Issue tab

**Comment by Maxi90909** [comment]
Also the mod wasn't updated and this Issue causes my minecraft world to be unable to be opened. I thougt My Issue was ignored so I posted a more specific one. This has to be fixed because I can't play in My World.

**Comment by Maxi90909** [comment]
Please Open this one instead of the other this one is more specific than the other
