### ISSUE TITLE
Snow graphic bug

### ISSUE THREAD

**Issue by MegaGamer265** [Glitchfiend/SereneSeasons#294]
When its snowing and there is a light source then the snow particles get gray.

**Comment by Forstride** [comment]
...What...?

I don't understand what you're saying at all, and without any visual reference or anything, I'm just gonna assume it's not an actual issue.

**Comment by MegaGamer265** [comment]
![2021-01-18_16 24 48](https://user-images.githubusercontent.com/47698400/104933903-c4bd0880-59a9-11eb-9fa3-73615e9ecec4.png)

**Comment by Forstride** [comment]
That's probably from Dynamic Surroundings

**Comment by MegaGamer265** [comment]
I removed Dynamic Surroundings and its still there.

**Comment by Forstride** [comment]
This seems to happen in vanilla, so it's neither I guess.  Please test all options before making issue reports.

**Comment by MegaGamer265** [comment]
Well thx, but i really thought it can`t be vanilla cause it would be a huge issue xD
