### ISSUE TITLE
Crash with survive

### ISSUE THREAD

**Issue by Maxi90909** [Glitchfiend/SereneSeasons#295]
Bug Report
Crash and Unable to load up the World again(without crashing)

How can the crash be reproduced?
In My Case: 1. Start up a World with the mods Survive, Serene Seasons, The Undefeatbles and The Undergarden. 2.Go to the Undergarden Dimension. 3. Garther materials for the Slingshot or just get the Slingshot from creative and Some Peebles. 4. Shot the slingshot. 5. Crash and Unable to load up the World or go in the World without it crashing and Kicking you out of the loaded Minecraft.

Crash Report and Logs
latest.log
crash-2021-01-17_11.51.01-server.txt

Mod Version
Serene Seasons 1.16.4-4.0.0.86
Survive-1.16.4-3.0.11
Undefeatables 1.1 - 1.16.4
The Undergarden 0.4.3

**Comment by Maxi90909** [comment]
Sorry for posting this again I Deleted the other one Instead

**Comment by Maxi90909** [comment]
[crash-2021-01-17_11.51.01-server.txt](https://github.com/Glitchfiend/SereneSeasons/files/5826477/crash-2021-01-17_11.51.01-server.txt)
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/5826478/latest.log)
Here are the Logs and Crash Report(they don't work on the report above because I copypasted)

**Comment by Forstride** [comment]
Jesus dude you don't need to keep making new issues.  We get it

**Comment by Adubbz** [comment]
Whilst I have attempted to add a workaround for this, I make no guarantees of its efficacy. Your world is corrupted as a result of this crash and Serene Seasons gets caught up in the crossfire. I would not consider this a bug with Serene Seasons, but rather an issue with that slingshot or the Undergarden dimension.
