### ISSUE TITLE
Allow for forge:glass to count as greenhouse block.

### ISSUE THREAD

**Issue by Moleculor** [Glitchfiend/SereneSeasons#296]
### What feature are you suggesting?

Currently it looks like the code only checks if a block is an `instanceof AbstractGlassBlock`. It would be nice if it also checked to see if the block was a member of the `forge:glass` tag?

### Why should it be added?

Because Quark's `Framed Glass` is not ([so far as I can tell](https://github.com/Vazkii/Quark/blob/3fb58edebd949b82da808720e2daebfac71a7025/src/main/java/vazkii/quark/content/building/block/FramedGlassBlock.java#L9), and backed up with bonemeal testing) an `instanceof AbstractGlassBlock` but is part of the tag `forge:glass` and very much looks like the kind of block a greenhouse might be made out of.

### Alternatively

Perhaps instead make a tag `serene_seasons:greenhouse_glass` (or whatever) that you can then use datapacks to whitelist other mod's blocks with.

**Comment by SynfulChaot** [comment]
Doing it via a tag would be the easiest so other mods as well as modpack creators can add their own compatibility.

**Comment by Forstride** [comment]
Added for the next update with the new block/item tag system
