### ISSUE TITLE
Crash When opening/loading world

### ISSUE THREAD

**Issue by Maxi90909** [Glitchfiend/SereneSeasons#298]
## Bug Report

Can't Join my world anymore because of this crash, please Update Serene Seasons and fix this 

### How can the crash be reproduced?

Load My Modpack (Mods can be found in the crash report from pastebin) and try to join a world don't know if this happenes to new worlds to but I can't join my already created world

### Crash Report and Logs
 
https://pastebin.com/ATieLnfT (Crash Report)
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/5860402/latest.log) (Logs)

### Mod Version
Serene Seasons 1.16.4-4.0.0.86

Please don't close this issue because it is not the same

**Comment by Forstride** [comment]
This is quite literally the same exact crash that you already reported 3 times.  The crash is not going to get fixed faster just because you keep opening new issues for it.  Stop making new issues for the same exact thing or you will be blocked from our GitHub.

**Comment by Maxi90909** [comment]
I didn’t mean to make you angry, I thought this was a different Crash Report ,That was caused By something else with Serene Seasons. I don’t have so much experience in Mods as you That’s why I didn’t know this Crash Report was the Same. If I would have known It was the same Crash I already reported. I wouldn’t have reported it here Again.

**Comment by Forstride** [comment]
You can look at them side by side and see right away that it's virtually the same exact text.
