### ISSUE TITLE
Add command block compatibility for setseason

### ISSUE THREAD

**Issue by Adubbz** [Glitchfiend/SereneSeasons#3]
As per title.

**Comment by Akitori** [comment]
I was about to come over here and ask about that with a new issue, but thankfully this existed. 

This would be extremely helpful to my friend's map, as it would mix wonderfully with the custom seasons he has implemented.

**Comment by EnderTeleportation** [comment]
No, but realy. It would help me out a lot, especially for 1.12.2

**Comment by BattalGazii** [comment]
Sorry for my bad English.In 1.12.2 version ,seasons not working only,in winter can snowy  rain.Other seasons leaves don't get  colouring .My forge version is last version .Serene Seasons mod 1.12.2 leaves dont colouring please fix it.

**Comment by Hate9** [comment]
I would also love to see this as an option. I was trying to create a season-changing item with ContentTweaker on 1.12, but couldn't because this command (for some reason) requires a player to be calling it.

**Comment by Forstride** [comment]
Should be fixed for 1.16.4 (Yet to be released)

**Comment by Hate9** [comment]
So, this isn't gonna be fixed on 1.12 at all?

**Comment by Forstride** [comment]
No.  We do not support older versions
