### ISSUE TITLE
Calendar inaccurate when using non-default settings.

### ISSUE THREAD

**Issue by shondoa** [Glitchfiend/SereneSeasons#301]
## Issue Report

The Calendar item becomes inaccurate if you change how many days the sub-seasons last or how many ticks a minecraft day has in the config files.</br>

### How can the issue be reproduced?

Change the length of sub-seasons and/or length of a day in the config, then set to different seasons while watching the calendar.</br>

### Mod Version
1.16.4-4.0.0.86</br>

**Comment by Forstride** [comment]
Are you on a server?  Because the config needs to be the same between the server and client, and client-sided things like the calendar will be messed up if they're not.

**Comment by Moleculor** [comment]
> Are you on a server? Because the config needs to be the same between the server and client, and client-sided things like the calendar will be messed up if they're not.

Out of curiosity on this, what lines *specifically* need to match? 

For example, if `progress_season_while_offline = true` is on the server, but `progress_season_while_offline = false` is on the client, will that cause desync? 

What about `change_grass_color = true`?

**Comment by Forstride** [comment]
I'm not really sure about Progress Season While Offline, since Adubbz handled that.  Change Grass Color is definitely only client-sided though.

**Comment by shondoa** [comment]
Would there be a way to get the config data from the server when connecting? I'd rather not have to make all my users change their configs manually.

**Comment by Moleculor** [comment]
> Would there be a way to get the config data from the server when connecting? I'd rather not have to make all my users change their configs manually.

I desperately would like this as well. There's an issue open for it (#281) requesting the feature, but that's really *all* I know.

**Comment by Forstride** [comment]
Yes, server-synced configs are possible with Forge.  I'm not sure when Adubbz will implement them though.
