### ISSUE TITLE
Serene Seasons Server Spam

### ISSUE THREAD

**Issue by KowalskiXCIX** [Glitchfiend/SereneSeasons#303]
### What's the issue you encountered?
Server is spamming the message "Season time skipped by 2 in minecraft:the_nether/minecraft:the_end" every second
(This also happens with all modded dimensions that are added, the only dimension not receiving this message is the overworld which is whitelisted in the config.)

### How can the issue be reproduced?
Install Forge alongside Serene Seasons on a server, after the world has been generated it will spam this message every second and clutters the log entirely, especially with mods that add other dimensions.

### Logs
https://pastebin.pl/view/4ef5c798

### Mod Version
MC Version: 1.16.5
Forge: 36.0.42
Serene Seasons: Serene Seasons 1.16.5-4.0.1.89

**Comment by Kowantify** [comment]
Updated information above 2/23/2021

New Log: https://pastebin.pl/view/6d9b9ecf

**Comment by Kowantify** [comment]
This issue is caused by a third party mod called MCMT (Minecraft Multithreading)
