### ISSUE TITLE
Make whether a biome is tropical or not accessible to the API

### ISSUE THREAD

**Issue by anIceyGirl** [Glitchfiend/SereneSeasons#306]
## Feature Request

Make whether a biome is tropical or not API-accessible.</br>

### What feature are you suggesting?

Exactly what it says on the tin: there should be an API-accessible function that tells me whether or not a biome is tropical. If it feels like I'm repeating myself, that's because I don't know a better way to phrase it.</br>

### Why should it be added?

It doesn't seem too difficult to implement, plus some mod developers may want to know if a biome is tropical if they want it to affect mob spawn rates or mob behavior only in tropical biomes. </br>

**Comment by Adubbz** [comment]
This has been added to the 1.18 version which will be released soon
