### ISSUE TITLE
1.12.2 RTG + Serene Seasons, rivers config

### ISSUE THREAD

**Issue by I3estOFF** [Glitchfiend/SereneSeasons#307]
## Bug Report
Hello! I know it's old version, maybe i'm doing something wrong, but i want Rivers to have same seasons as Plains.
I've tried change it by turning on seasonal effects here 

 "minecraft:river": {
    "enable_seasonal_effects": true,
    "use_tropical_seasons": false,
    "disable_crops": false
  },

After that Rivers are frozen, not only in winter like Plains, but in spring and autumn too.
Can you help, how can i repair it in my modpack? :)

### Mod Version
SereneSeasons-1.12.2-1.2.18-universal.jar
![image](https://user-images.githubusercontent.com/63112899/106526489-05f30380-64e6-11eb-9d9e-43c6887233e3.png)

**Comment by Forstride** [comment]
We do not support versions below 1.12.2

**Comment by I3estOFF** [comment]
:(

**Comment by Pinecone6442** [comment]
LMAO WHO USES 1.16.4 XD
