### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by derabzockerHD** [Glitchfiend/SereneSeasons#309]
Can you make a version for fabric?

**Comment by Adubbz** [comment]
We have no plans or interest in making a Fabric version for any of our mods (as stated on your issue in the BOP repo). Please make no further issues about this.

**Comment by Aces-and-Jacks** [comment]
So you have no interest in making a fabric version and no one's allowed to port it to fabric based on what's said on curseforge

**Comment by Forstride** [comment]
Yes that's correct

**Comment by Aces-and-Jacks** [comment]
Is there something you have against fabric?
