### ISSUE TITLE
Set crop season via item tags

### ISSUE THREAD

**Issue by SynfulChaot** [Glitchfiend/SereneSeasons#313]
### What feature are you suggesting?

Detect whether or not crops can grow via item tags.

### Why should it be added?

Shifting crop season assignment from your config file to item tags would allow mod creators to easily add native support for their crops as well as allowing modpack creators to do the same.  It would also remove the need for PRs or feature requests every time a mod wants to add SereneSeasons support to their new crops.

**Comment by Forstride** [comment]
Good idea, hadn't really thought of that before.  Although I'm not 100% sure if it'll be possible without actually trying it, but it'd be a better way to do it than our current config.

**Comment by Forstride** [comment]
Fertility has now been changed to completely use block/item tags.  Build with this stuff should be up within the next day or so (Once our build server is back up)
