### ISSUE TITLE
Changing sub-season duration does not change foliage color cycle

### ISSUE THREAD

**Issue by mrPaintMan** [Glitchfiend/SereneSeasons#314]
### What's the issue you encountered?

After changing sub-season duration to 12 days instead of 8, the colors of leaves etc seem to keep the 8-day cycle.
This was tried on a server with Minecolonies, Pams harvestcraft 2 (all mods) and JEI.

### How can the issue be reproduced?

i do not suspect the issue being a result of a combination of mods, so to reproduce:

1. start a server with the default settings with SS installed
2. stop server, edit sub-season duration from 8 to 12 days
3. start server again
4. observe

### Logs

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/6031317/latest.log)
[debug.log](https://github.com/Glitchfiend/SereneSeasons/files/6031318/debug.log)

### Mod Version
Serene Seasons 1.16.5-4.0.1.91

**Comment by Forstride** [comment]
You need to change it on the client as well, as the value isn't synced from the server.
