### ISSUE TITLE
No seasons with 1.16.5, optifine and no shaderpack

### ISSUE THREAD

**Issue by Bakudansama** [Glitchfiend/SereneSeasons#316]
## Bug Report

[ Serene Seasons have no visual effects (with Optifine and no shader on 1.16.5 build) ]</br>

### What's the issue you encountered?

[ I tried the season set PICKYOURSEASON command but nothing changes, The leafs, tint of the game, nothing ]</br>

### How can the issue be reproduced?

[My game have quit a few mods, notably BoP and ByG for biomes, Optifine 1.16.5_HD_U_G7  and no shaderpack installed, i read some ppl have it to work with optifine, i tried as some ppl says to remove some maps in optifine/colormap but i only got the underwater here so its not the culprit, none of my other mods use specific colormaps either. ]</br>

### Mod Version
[ 1.16.5-4.0.1.91-universal ]</br>

**Comment by Forstride** [comment]
Make sure custom colors/swamp colors are enabled in OptiFine's settings.  Beyond that there's not really much we can do, as OptiFine messes with a *lot* of rendering stuff with no regard for other mods.

**Comment by Bakudansama** [comment]
I see , well its all enabled in optifine so i guess that's it.
Sadly optifine is required for a lot of other mods so i can't really remove it (+shaders), and also helpfull for extra tooltip and debug infos ^^'.
