### ISSUE TITLE
Fruit tree leaves not affected by the season

### ISSUE THREAD

**Issue by sharlin073** [Glitchfiend/SereneSeasons#317]
## Bug Report

[  ]</br>

### What's the issue you encountered?

[ Tree Saplings from simple farming are not growable when out of season as intended, but once they grow, their leaves are not affected and still 'age'. ]</br>

### How can the issue be reproduced?

[ open a flat new world, plant a tree which is out of season, and grow with bonemeal with its head covered (so that the mod considers it is underground), and remove the cover block, observe how it ages and still bears fruit. ]</br>

### Logs

[ I'll provide if needed, but as it is a long time of waiting the log is very long...and I guess it is reproducible easily? ]</br>

### Mod Version
[ 4.0.1.91 for 1.16.5 ]</br>

**Comment by Forstride** [comment]
You'd have to add the leaf blocks to the config manually (The default values in the config were done by someone else).  If that doesn't work, it's an issue with Simple Farming not using Forge's crop growth hooks, in which case there's nothing we could do about it.

**Comment by sharlin073** [comment]
Thanks!
