### ISSUE TITLE
Clientside Crash on Terraforged + BYG + BOP server

### ISSUE THREAD

**Issue by MrKashew** [Glitchfiend/SereneSeasons#318]
https://gist.github.com/MrKashew/a5d9bb3f83a3e8e50853202ff01e084e

**Comment by Adubbz** [comment]
Some mod that adds biomes (not necessarily any of those you have mentioned, though it could be them) isn’t registering their biomes correctly and thus they aren’t being synchronised between the client and server properly. I can only speak to BoP doing it correctly as we are the ones responsible for it, I don’t really know amongst the others, especially given your enormous mod list.

**Comment by Adubbz** [comment]
Closing this as I don't believe it is/was an issue with Serene Seasons
