### ISSUE TITLE
Compatibility with Thermal Cultivation

### ISSUE THREAD

**Issue by Suraru** [Glitchfiend/SereneSeasons#319]
## Feature Request

Default compat with Thermal Cultivation

### What feature are you suggesting?

Default compat with Thermal Cultivation

### Why should it be added?

So Thermal Cultivation and Serene Seasons work together without any end user config editing

### Did you already do half the work for me?

Yes,
Already grabbed the IDs and added them to the config, just gotta copy paste it into the default config for next release.
[fertility.txt](https://github.com/Glitchfiend/SereneSeasons/files/6232409/fertility.txt)

Spring:
`, "thermal:barley", "thermal:onion", "thermal:rice", "thermal:sadiroot", "thermal:spinach", "thermal:green_bean", "thermal:strawberry", "thermal:coffee", "thermal:tea"]`

Winter:
`, "thermal:spinach", "thermal:frost_melon"]`

Summer:

`, "thermal:radish", "thermal:rice", "thermal:bell_pepper", "thermal:corn", "thermal:tomato", "thermal:coffee", "thermal:hops", "thermal:tea"]`

Autumn:
`, "thermal:barley", "thermal:rice", "thermal:spinach", "thermal:bell_pepper", "thermal:corn", "thermal:eggplant", "thermal:peanut", "thermal:tea"]`

**Comment by Forstride** [comment]
We're going to be moving to a block/item tag system for crop fertility, and sadly this means the existing config system is being gutted and will require modders to add compatibility for Serene Seasons on their end. But, it's as easy as just adding the tags and putting their crops in them (https://github.com/Glitchfiend/SereneSeasons/tree/SS-1.16.x-4.x.x/src/main/resources/data/sereneseasons/tags)
