### ISSUE TITLE
Growing crops out of seasons in greenhouses

### ISSUE THREAD

**Issue by Beam195** [Glitchfiend/SereneSeasons#322]
## Feature Request
Growing crop out of seasons in greenhouses

### What feature are you suggesting?

If crops is surrounding by glasses, glass panes, stained glasses and stained glass panes they can growing out of seasons similar to how greenhouses

### Why should it be added?
That's because it would be great if you can plants them and make them grow out of seasons in greenhouses by surrounding it with glass type blocks
to make features more realistic in real life you can plants crops out of seasons in greenhouses because the glasses of the greenhouses can absorb sunlight from the sun and make the inside warm to make crops can grow without the need of their actual seasons

**Comment by Forstride** [comment]
This is already a thing, except you only need to place glass above the crops, not on the sides...

See the [Crop Fertility](https://github.com/Glitchfiend/SereneSeasons/wiki/Crop-Fertility) page on the wiki for more info, and please read the other pages before opening issues in the future.
