### ISSUE TITLE
[1.16.5] Calender showing wrong season

### ISSUE THREAD

**Issue by MarioSMB** [Glitchfiend/SereneSeasons#323]
### What's the issue you encountered?

The season calender doesn't display the correct season when used on servers and placed in an item frame. Only the dropped item displays the correct season.

### How can the issue be reproduced?

Launch a dedicated server, connect to it, place a calender in an item frame and change seasons. It doesn't seem to trigger in local games even when opened to LAN (tested locally with only Serene Seasons installed).

### Logs
https://i.imgur.com/BpTo5xz.png  
https://i.imgur.com/5OrzFKr.png

### Mod Version
4.0.1.91

**Comment by Forstride** [comment]
The item frame one would actually be the correct season.  The dropped item can't differentiate between temperate/tropical seasons, whereas in the item frame it's showing the wet season (The season it actually is in that biome) since I'm assuming you're in a tropical biome.

**Comment by MarioSMB** [comment]
Perhaps it would make more sense to have a seasonal forecast calender so that the calender in the item frame can display the actual season (Spring, Winter, Summer etc) too? This *looks* like a bug with the current behaviour, essentially, and doesn't allow players to easily tell what the general season outside of that specific biome is.

**Comment by Forstride** [comment]
It does display the actual season.  If you're in a tropical biome, they use tropical seasons (wet/dry).  You shouldn't really need to know the temperate season outside of a tropical biome, because it's irrelevant to it.

Also it's an item with a 16x16 texture.  There's only so much information we can display, and some people don't understand the icons as it is.

**Comment by MarioSMB** [comment]
It does make more sense now, thanks. I'll open new issues if I come up with anything to help address the clarity issue in-game.
