### ISSUE TITLE
You can waste bonemeal on a fully grown crop.

### ISSUE THREAD

**Issue by Insane96** [Glitchfiend/SereneSeasons#326]
### What's the issue you encountered?

You can use bonemeal on fully grown crops and they get consumed

### How can the issue be reproduced?

1. Plant wheat
2. Bonemeal until it grows
3. Keep bonemealing (in survival)
4. Profit

### Mod Version
1.16.5-4.0.1.91

**Comment by Forstride** [comment]
Will be fixed in the next update (Coming soonish)
