### ISSUE TITLE
Horizontal Panes Compatibility

### ISSUE THREAD

**Issue by HopsandBarley** [Glitchfiend/SereneSeasons#327]
## Feature Request

[Horizontal Pane compatibility with Serene Seasons]</br>

### What feature are you suggesting?

[ Allow for horizontal panes to be used as roofs for greenhouses, for out-of-season crop farming]</br>

### Why should it be added?

[ Allow for more options for greenhouses for builders.
link to horizontal panes:  https://www.curseforge.com/minecraft/mc-mods/horizontal-panes-forge ]</br>

![image](https://user-images.githubusercontent.com/78277756/116407332-aadc5e80-a7ff-11eb-80a2-6a0e616b29ba.png)

**Comment by D0CTOR-ZED** [comment]
I'd suggest changing this check ( https://github.com/Glitchfiend/SereneSeasons/blob/a92ba6371acd3ee80f0df047106de31e33cbd3a9/src/main/java/sereneseasons/handler/season/SeasonalCropGrowthHandler.java#L101 ) so that it checks a block tag.  This would allow pack makers (as well as other mod makers) to add and/or remove acceptable blocks.

**Comment by HopsandBarley** [comment]
any update if something like this will be coming?

**Comment by Forstride** [comment]
The best solution would probably be for us to add a block tag, but that would mean other mods would have to add the tag as well.  I can do it soon, but IDK when a build will be made with it, since we need to re-setup Serene Season's build server.

**Comment by Forstride** [comment]
Gonna close this now as I added the block tag system, and there's one for greenhouse glass that other modders can add blocks to in their mods (https://github.com/Glitchfiend/SereneSeasons/blob/SS-1.16.x-4.x.x/src/main/resources/data/sereneseasons/tags/blocks/greenhouse_glass.json)

Should hopefully be a build up with all of this soon, whenever Adubbz gets around to fixing our build server.
