### ISSUE TITLE
Biomes O' Plenty: Color change for: Blossoms; Seasonal trees

### ISSUE THREAD

**Issue by ProfessionaFiddler** [Glitchfiend/SereneSeasons#329]
I noticed that, pink and white cherry blossoms bloom all year. Probably a good idea to give them standart green cycle, and assign their true color only for spring.

Seasonal birch and maple also are in one color all year. For seasonal trees, green cycle and true color for autumn, but yet slightly true colored in winter. Especialy for maple, it already looks good under snow.

**Comment by ProfessionaFiddler** [comment]
While one can argue those are the specialties of specific biomes, they look extremely out of place, because of adjacent cycling biomes. In order to keep their specialty, they should stand out in the right time, otherwise there is this color disparity.

**Comment by ProfessionaFiddler** [comment]
In order to keep their specialty, they should stand out in the right time, otherwise there is this color disparity.

**Comment by Forstride** [comment]
>While one can argue those are the specialties of specific biomes

I would argue that.  Also these leaves have colored textures.  They're not grayscale with a color applied to them at runtime, and I'm not changing that in BOP and losing quality there just for compatibility with Serene Seasons.
