### ISSUE TITLE
Tropical Biome Weather Doesn't Change

### ISSUE THREAD

**Issue by TechnoMysterio** [Glitchfiend/SereneSeasons#33]
The weather in tropical biomes remains the same, even when the seasons change. So jungles will still rain in the dry season (mid_summer) and savannas will be dry in the wet season (mid_winter):

![2018-04-28_22 24 19](https://user-images.githubusercontent.com/5113920/39401009-9a1d3bc2-4b33-11e8-87cc-7aabc2507635.png)
![2018-04-28_22 24 38](https://user-images.githubusercontent.com/5113920/39401010-9b84e2d0-4b33-11e8-9902-a9c2c05ffba9.png)
![2018-04-28_22 25 33](https://user-images.githubusercontent.com/5113920/39401012-9d4fb5b8-4b33-11e8-97d8-a0cfca336d13.png)
![2018-04-28_22 26 10](https://user-images.githubusercontent.com/5113920/39401013-9fc211f6-4b33-11e8-8ee2-4589c23c12d5.png)

Forge: 14.23.3.2676
Serene Seasons: 1.1.4
Minecraft: 1.12.2

**Comment by Forstride** [comment]
My mistake marking this as a bug, when it's actually not.

So, rain is only actually affected in the mid dry/wet season.  The chart for it looks like this:

![](https://cdn.discordapp.com/attachments/138057128127496192/433426250070229003/unknown.png)

So it only rains in desert biomes in late winter/early spring, and rain is only prevented in jungle biomes in late summer/early autumn.
