### ISSUE TITLE
Survive doesent recognize serene seasons version properly

### ISSUE THREAD

**Issue by Mr-Syntax** [Glitchfiend/SereneSeasons#330]
Survive in the older versions which are compatible with forge 36.1.0 cant boot because survive reads the version as 1.16.4-"version number"

seems like a minor glitch but i would really appreciate if it was fixed as survive is pretty essential in my pack

**Comment by Forstride** [comment]
Considering their mod support is on their end, this is probably also an issue on their end?  The version in our .jar is listed perfectly fine

**Comment by Forstride** [comment]
Also I just checked their issue tracker and they already fixed it on their end.  You need to update your mod(s)
