### ISSUE TITLE
Biomes O' Plenty Request

### ISSUE THREAD

**Issue by ProfessionaFiddler** [Glitchfiend/SereneSeasons#331]
I still wanted to request this...

Is it possible to set up a config file for block coloring?

**Comment by Adubbz** [comment]
As @Forstride already said:

>  Also these leaves have colored textures. They're not grayscale with a color applied to them at runtime, and I'm not changing that in BOP and losing quality there just for compatibility with Serene Seasons.

Making this a config option doesn't change this.
