### ISSUE TITLE
Calendar doesn't update correctly when adjusting tick length for day

### ISSUE THREAD

**Issue by kphoenix137** [Glitchfiend/SereneSeasons#334]
### What's the issue you encountered?

I adjusted the tick length from 24000 to 48000 to work in conjunction with the Time Flies mod, where I doubled the length of an entire Minecraft Day from 20 minutes to 40 minutes. Upon launching the server and entering after installing the Time Flies mod and adjusting the day length and setting Serene Seasons to 48000 ticks, the season went from Winter to Summer which was displayed by using /season get, however the Calendar still displayed the season as Winter. Upon setting the current season to Early Winter using /season set EARLY_WINTER, the world became Winter, however the Calendar displays the current season as Early Summer.</br>

### How can the issue be reproduced?

Set tick length to 48000 in an existing world and view a Calendar item.</br>

### Mod Version
SereneSeasons-1.16.5-4.0.1.91-universal</br>

**Comment by kphoenix137** [comment]
I adjusted the tick length client sided, and this appears to have stopped the issue, however it may still be present for users who haven't adjusted their tick length within the config file.

**Comment by Forstride** [comment]
Yes, you need the same configs on both the server and client.  This isn't an "issue."

**Comment by kphoenix137** [comment]
I apologize, I'm used to other mods syncing the config to the client.
