### ISSUE TITLE
Xaero's Minimap Integration

### ISSUE THREAD

**Issue by Foozey** [Glitchfiend/SereneSeasons#336]
## Feature Request

Xaero's Minimap Integration</br>

### What feature are you suggesting?

When using Xaero's Minimap, you can have it displays the current biome underneath the map. I would love it if next to this, it would also display the current season. So for example, it would read: "Forest, Summer" opposed to just "Forest".</br>

### Why should it be added?

It's a really tiny feature that would make a big difference in my opinion.</br>

**Comment by Forstride** [comment]
That would have to be something they add on their end using our API
