### ISSUE TITLE
[Enhancement] Allowing for certain biomes to permanently be in a certain season.

### ISSUE THREAD

**Issue by Corvus20** [Glitchfiend/SereneSeasons#337]
### What feature are you suggesting?

Making it so certain modded biomes, mainly those with specific seasonal themes, can stay locked in a specific season. Players can also configure these biomes or add new ones with limited seasons via config.

### Why should it be added?

Biomes like Autumnity's maple forests, Environmental's enhanced flower forests, etc. have much more autumn or spring themes to them, and it feels strange to have them in any other season than the ones that fit them. Having springtime in a permanently autumn looking forest or snow in a blossoming field makes little sense. Adding something like this would prevent that problem and would also open up many configuration possibilities.

**Comment by Forstride** [comment]
The mod isn't set up to work like that at all, and it'd be such a niche thing that there's no real need for us to add it.

Best you can do is disable seasonal effects entirely for a biome.
