### ISSUE TITLE
Suggested update/improvement for SimpleFarming default fertility config

### ISSUE THREAD

**Issue by InspectorCaracal** [Glitchfiend/SereneSeasons#339]
### What feature are you suggesting?

I'd like to suggest different default configuration options for Simple Farming - the fruit trees and berry bushes, specifically.

**Spring**
`"simplefarming:blueberry_bush", "simplefarming:banana_leaves", "simplefarming:cherry_leaves", "simplefarming:mango_leaves", "simplefarming:apple_sapling", "simplefarming:apricot_sapling", "simplefarming:banana_sapling", "simplefarming:olive_sapling", "simplefarming:orange_sapling", "simplefarming:pear_sapling", "simplefarming:plum_sapling"`

**Summer**
`"simplefarming:blackberry_bush", "simplefarming:blueberry_bush", "simplefarming:raspberry_bush", "simplefarming:strawberry_bush", "simplefarming:apricot_leaves", "simplefarming:banana_leaves", "simplefarming:pear_leaves", "simplefarming:plum_leaves", "simplefarming:apple_sapling", "simplefarming:banana_sapling", "simplefarming:cherry_sapling", "simplefarming:mango_sapling", "simplefarming:olive_sapling"`

**Autumn**
`"simplefarming:blackberry_bush", "simplefarming:apple_leaves", "simplefarming:banana_leaves", "simplefarming:olive_leaves", "simplefarming:orange_leaves", "simplefarming:pear_leaves", "simplefarming:apricot_sapling", "simplefarming:banana_sapling", "simplefarming:cherry_sapling", "simplefarming:mango_sapling", "simplefarming:plum_sapling"`

**Winter**
`"simplefarming:banana_leaves", "simplefarming:banana_sapling"`

### Why should it be added?

Firstly, while the fruit saplings are added to the default config, the fruit-bearing parts of the trees - the leaf blocks - are not. Adding them would greatly improve the existing compatibility with the mod, and I've done some research to determine which trees are best suited to fruiting in which seasons.

Secondly, changing the sapling growths to only seasons where the fruits *don't* mature adds a sense of having to plant your trees ahead of time, more like most real fruit trees.

(Bananas are an intentional exception because they're not a seasonally fruiting tree)

**Comment by InspectorCaracal** [comment]
I'd like to add a brief but tangential note for anyone using the two mods together:

The Simple Farming fruit leaf blocks *do not* display the seasonal fertility information when added to the configuration files like this, but they *are* affected by Serene Seasons as you'd expect. This does not indicate a compatibility issue within Serene Seasons but is rather a quirk with Simple Farming's tooltip information for the leaf blocks - I think it's showing the fruit info instead.

**Comment by Forstride** [comment]
We're going to be moving to a block/item tag system for crop fertility, and sadly this means the existing config is being gutted and will require modders to add compatibility for Serene Seasons on their end.  But, it's as easy as just adding the tags and putting their crops in them (https://github.com/Glitchfiend/SereneSeasons/tree/SS-1.16.x-4.x.x/src/main/resources/data/sereneseasons/tags)

**Comment by InspectorCaracal** [comment]
Oh, okay then. xD I'll throw the suggestion at them to implement the new compatibility once your change goes through. Thanks for the response!
