### ISSUE TITLE
Tropical season tags for the new tag-based fertility system

### ISSUE THREAD

**Issue by InspectorCaracal** [Glitchfiend/SereneSeasons#340]
## Feature Request

(I know there's an open issue right now about the tropical biome status being API-accessible and I was going to add this to it, but while typing it up I realized it's really an entirely different request so I started a new issue.)

### What feature are you suggesting?

With the new tags system, could we get seasonal fertility tags specifically for tropical seasons? I don't know which of these two ideas would be simpler to implement, so here's both of them:

1. Add two new season fertility tags: wet_season and dry_season. Since those seasons are specific to tropical biomes, adding a crop to one or both of those seasons and none of the temperate seasons would limit it to growing just in the tropics. This also lets you define it so that a crop can only grow e.g. during the wet season.

2. Add a "tropical_biome" tag as a secondary layer to the seasonal checks. If it's in a tropical biome, it then would check both the summer fertility tag and the tropical biome tag, and anything within either of those tags is fertile.

The only substantial difference between the two ideas is, I think, that one checks the local season and the other checks the local biome. I don't know exactly how the fertility checks work so I don't know which would be easier to implement. If they're both the same difficulty, I think option 1 would be better, both in terms of flexibility and consistency.

### Why should it be added?

I think it would add a lot of immersive potential to biome-based seasons and crop diversity, and do it within the scope of the (new but) already-existing system.

**Comment by Forstride** [comment]
Biome tags aren't a thing, otherwise I would use them.  As for the wet/dry season, it's really not meant to affect crop fertility at all.

**Comment by InspectorCaracal** [comment]
Aw, that's unfortunate. Thanks anyway!
