### ISSUE TITLE
[1.16.5] Fertile season tooltips not showing on server

### ISSUE THREAD

**Issue by zderApfel** [Glitchfiend/SereneSeasons#341]
## Bug Report

</br>

### What's the issue you encountered?

Fertile season tooltips are not showing when in multiplayer, in singleplayer they show just fine</br>

### How can the issue be reproduced?

Go on a server running Forge 1.16.5-36.1.32 and install the following mods:

* AutoRegLib
* Backstab
* MrCrayfish's Furniture Mod
* Corpse mod
* CreativeCore
* Drug Mod
* Fake Name
* Falling Tree
* iChunUtil
* Localized Chat
* Ore Excavation
* Quark
* Quark Oddities
* Serene Seasons
* SimpleCoreLib
* SimpleOres2
* Voicechat
* WorldEdit</br>

### Logs

No logs available</br>

### Mod Version
Serene Seasons 4.0.1.119 for Minecraft 1.16.5 (Forge)</br>

**Comment by zderApfel** [comment]
Weird, so it started working randomly as I was playing. Here's the log from the last restart for your reference
[test.txt](https://github.com/Glitchfiend/SereneSeasons/files/6729965/test.txt)

**Comment by kil0byt3** [comment]
Having the same. They work on singleplayer.

EDIT: And after going into Singleplayer once, they now work on the server. @zderApfel, was this the case for you?

**Comment by zderApfel** [comment]
> Having the same. They work on singleplayer.
> 
> EDIT: And after going into Singleplayer once, they now work on the server. @zderApfel, was this the case for you?

Yes it was

**Comment by OcrSu** [comment]
> Having the same. They work on singleplayer.
> 
> EDIT: And after going into Singleplayer once, they now work on the server. @zderApfel, was this the case for you?

My situation is the same

**Comment by Organism-K** [comment]
Same thing happened to me too. Oh well guess im gonna jump on singleplayer everytime i play on my server

**Comment by fred42096** [comment]
I am having the same issue on a single player world but it only seems to affect some crops, with none of PHC2 crops retaining their tooltips. However, if I run agricraft, the journal shows the season just fine.

**Comment by OfficialLahusa** [comment]
This issue could be related to datapack loading on dedicated servers. Related: [Epic Fights Mod: Armor not showing up on server #711](https://github.com/Yesssssman/epicfightmod/issues/711), [Titles Mod: Titles not visible/selectable on a dedicated server until you unlock any titles in single player #26](https://github.com/Aurilux/Titles/issues/26)

**Comment by SaphieNyako** [comment]
When players make a single player world and log in to the server after it works. 
(Using Openloader)

**Comment by Adubbz** [comment]
This has been fixed in the 1.18 version which will be released soon
