### ISSUE TITLE
Serene Seasons and Skyblock Builder crashes when loading new chunks/upon world creation [1.16.5 - Forge]

### ISSUE THREAD

**Issue by StellaBiscuit** [Glitchfiend/SereneSeasons#342]
## Bug Report

Serene Seasons crashes when loading new chunks/when creating the world (the world is created and can be joined after that)
This has been tested on a Skyblock Type world using Skyblock Builder, I don't know if it happen on a different type but with both mod on

### How can the crash be reproduced?

Install Serene Seasons and Skyblock Builder (LibX is it's library) and create a new world with the "Skyblock" type
The crash happen with the default config of both mods

### Crash Report and Logs

[crash-2021-07-03_21.39.24-server.txt](https://github.com/Glitchfiend/SereneSeasons/files/6759248/crash-2021-07-03_21.39.24-server.txt)
[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/6759250/latest.log)

### Mod Version
Forge - 36.1.32 (it shows 36.1.0 in the files I provided but it's because I forgot to crank it up, it happened in 36.1.32 too)
Serene Seasons - 4.0.1.119 Universal
Skyblock Builder - 1.6.2
LibX - 1.0.76

Oh and extra info, it seems that the temperature changes are at fault, but strangely, Primal Winter doesn't crashes with Skyblock Builder even if it also changes the temperature

**Comment by StellaBiscuit** [comment]
Bonus, Snow Under Trees + Skyblock Builder ALSO cause the same issue and Serene Seasons doesn't need to be installed...

So Serene Seasons or Snow Under Trees + Skyblock Builder cause the crash

**Comment by Adubbz** [comment]
I added some checks in the 1.18 version to deal with this specific crash, however the underlying cause of the issue isn't one stemming from Serene Seasons. For whatever reason we're being provided with null biomes, which should never happen under normal circumstances.
