### ISSUE TITLE
Unable to bonemeal nether blocks in the nether outside of greenhouses

### ISSUE THREAD

**Issue by JTheBlue** [Glitchfiend/SereneSeasons#343]
## Bug Report

[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

Blocks such as Nylium and Nether Mushrooms (both the crimson and warped variants) can't be bonemealed in the nether unless a greenhouse structure is built. </br>

### How can the issue be reproduced?

Try and bonemeal netherrack that's near nylium or a mushroom on nylium in the nether  that isn't inside a greenhouse it won't work.</br>

### Logs

[ Please include any relevant logs here. This can be done by dragging and dropping your log files into the issue. ]</br>

### Mod Version
[ Serene Seasons 1.16.5-4.0.1.119]</br>

**Comment by Forstride** [comment]
Hmm...Nylium and Fungi are set to be seasonal year round, so it might be some weird conflict with how our dimension whitelisting works.

**Comment by JTheBlue** [comment]
I tried to replicate it with version "Serene Seasons 1.16.5-4.0.1.91" and it worked fine so It only seems to be with this newer version, hope that helps.

**Comment by Forstride** [comment]
Did you change the out of season crop behavior setting in the config at all?

**Comment by JTheBlue** [comment]
Nope
say's "out_of_season_crop_behavior = 1"
I didn't change the config

**Comment by Forstride** [comment]
Ok I'm dumb.  I forgot that Nether biomes are set as infertile biomes, but it doesn't really make sense if you can't grow Nether plants in them, so I'll make separate block tags for Nether-fertile plants.

**Comment by Forstride** [comment]
Actually just gonna remove the Nether biomes from the infertile biomes list.  It's probably more annoying than it's worth to keep.

**Comment by AlienXtream** [comment]
um... ok... so... this now seems to cause a crash with better nether reforged (1.16.5)
also, why is this closed 12 of Jul when the curseforge file was updated 1 day ago... (hence me posting this 3 months later) no, seriously. my brain hurts trying to understand how they are so different... 0.o

**Comment by Adubbz** [comment]
There were no changes. This was purely an automatic build triggered by Jenkins. There's no special meaning to be interpreted here.

**Comment by AlienXtream** [comment]
thats confusing to me but ok... XD
anyway. sorry for the necro. i just decided to remove the mod. too many issues with seasons mods in general it seems. its a brilliant mod. just a bit unstable on my instance :)
