### ISSUE TITLE
[1.16.5] Crops not respecting manually added fertility season tags in latest update

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [Glitchfiend/SereneSeasons#346]
## Bug Report

Since the most recent update where Serene Seasons changed from adding crops in the config file to using forge tags, adding or removing tags from crops no longer changes crop fertility behavior.</br>

### What's the issue you encountered?

Crops do not respect the seasonal fertility tags when manually added. It seems that when applying the tags to the crops, the tags are not inherited by the crop block and requires adding the block to the tags, in addition to the seeds/saplings. The result is that, regardless of what tags you add or remove from the crop itself to change the seasons it can grow in, it will retain the original behavior. This applies to both vanilla or modded crops (modded crops lacking existing tags will simply grow year-round).</br>

### How can the issue be reproduced?

1. Use a crafttweaker script to remove summer and autumn season tags from wheat seeds and wheat, then add the winter season tag to wheat seeds and wheat.
2. Attempt to grow wheat in the winter. No growth will be seen, as the minecraft:wheat block will still show summer and autumn tags when viewed in f3.
3. Change season back to summer and autumn, and wheat block will grow as normal, despite tags only being set for winter.</br>

### Logs

[latest.log](https://github.com/Glitchfiend/SereneSeasons/files/6874609/latest.log)</br>

### Mod Version
Forge 36.1.2
Serene Seasons 1.16.5-4.0.1.120
CraftTweaker 1.16.5-7.1.0.203</br>

**Comment by Forstride** [comment]
>and requires adding the block to the tags, in addition to the seeds/saplings

Ehm...Yeah, that's how it works.  You need to add them to the appropriate block tags for the actual crop growth functionality, and the item tags for the tooltip fertility info.  Unless I'm missing the point of you saying that.

Anyway, it's possible we're setting up our tags in the wrong stage of mod initialization.  Others have reported issues with tags not showing up on servers until a random point during their play session, so it wouldn't surprise me.  Code isn't my strong suit though, so I'll have to ask around for help with it.

**Comment by Whiskey-Sunshine** [comment]
I didn't know if that was how it was meant to work, as back in the original config file, the blocks would inherit the growth seasons by simply adding the seeds to the appropriate list, adding the blocks themselves wasn't necessary.

Just wanted to make sure of it at least, thanks for the reply!

**Comment by Forstride** [comment]
Ah, yeah.  The old system did work like that, but with this system it's cleaner and more obvious to other modders to just have the separate tags and require them to be added to both.

**Comment by Whiskey-Sunshine** [comment]
Understood, thank you for the clarification.
