### ISSUE TITLE
WHEN i use Bsl shader ，sky look like forever night

### ISSUE THREAD

**Issue by fkyah3** [Glitchfiend/SereneSeasons#348]
## Bug Report

[ WHEN i use Bsl shader sky look like forever night]</br>

### What's the issue you encountered?

[WHEN i use Bsl shader ，sky look like forever night ]</br>

### How can the issue be reproduced?

[hope can fix this  thx]</br>

### Logs

[ nope]</br>

### Mod Version
[SereneSeasons-1.16.5-4.0.1.120-universal.jar
![光影](https://user-images.githubusercontent.com/87884337/129309233-77804522-2b25-41b4-9ebb-312c2a5e3054.jpg)

**Comment by Adubbz** [comment]
Shader issues are nothing to do with Serene Seasons.

**Comment by fkyah3** [comment]
> 着色器问题与 Serene Seasons 无关。

thx for help
