### ISSUE TITLE
Calendar Rework

### ISSUE THREAD

**Issue by vivvyinks** [Glitchfiend/SereneSeasons#350]
## Feature Request

</br>

### What feature are you suggesting?

</br>
Adding the current season and day of season to the Calendar's tooltip. When in an item frame, the season/day of season renders when a player looks at it. 

### Why should it be added?

</br>
Ability to more finely view the day of the year would be extremely helpful for many "living world" modpacks.

**Comment by Forstride** [comment]
Added Calendar tooltips in the latest build for 1.19.2, however the item frame thing doesn't seem possible, since items in frames don't tick, and there would be no way to update the hover text to match the current season/day.
