### ISSUE TITLE
[1.18.1] Crops which are in season act as if they aren't on server

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Glitchfiend/SereneSeasons#358]
### What's the issue you encountered?

On my multiplayer server (which I host) we've gathered crops for summer. When we plant a crop which is tagged _summer_, for example wheat seeds, the crops destroy themselves one by one after a while (I've set `out_of_season_crop_behavior` to 2 which means that they get destroyed if they're not planted in the right season). When I wanted to test if this also happened in single-player, it worked perfectly fine (see video 1).

https://user-images.githubusercontent.com/72312697/147753245-09cafdd8-0b47-408c-a823-b889bb797178.mp4

_Singleplayer world._

https://user-images.githubusercontent.com/72312697/147754094-2b4131b5-1f2a-41d2-99a9-29a6b42c0aa8.mp4

_Multiplayer world. Wheat should be able to grow in the summer, but doesn't. This was also the case for potatoes we planted in spring._

### How can the issue be reproduced?

1. Install Forge 1.18.1 and the latest Serene Seasons version.
2. Change the config to break crops that are out of season (this is optional, but makes it easier to see if the mod registers the crops out of season as they'll break instead of growing slowly like the first option in the config).
3. Join/set up a multiplayer server.
4. Plant crops that are in the right season (if it's for example spring, plant potatoes).
5. Observe the behaviour.
### Logs
_Single-player log:_ [latest.log](https://github.com/Glitchfiend/SereneSeasons/files/7792942/latest.log)

**Multiplayer log:**
_Server log:_ [latest.log](https://github.com/Glitchfiend/SereneSeasons/files/7792968/latest.log)

### Mod Version

Forge 39.0.9
Serene Seasons 6.0.0.8 _(1.18.1)_

**Comment by Forstride** [comment]
For the second video, biomes that are always snowy act as winter biomes, as stated on the Crop Fertility page in our wiki.  As for the first video, it's hard to tell what the biome is directly where the crops are planted, but if it's right on the edge of a frozen ocean, they'd grow regardless since frozen oceans are blacklisted and therefore aren't affected by seasons at all.

**Comment by GeorgeOrwell1** [comment]
Is it possible to change the first thing you mentioned (snowy biomes always act as winter)? I don't want to move everything we've built just so we can grow crops, even though it wouldn't be very realistic to let crops be able to grow in snowy biomes.

**Comment by Forstride** [comment]
No, there's no way to change that.  But you can make a greenhouse to grow out of season crops, again as stated in our wiki.
