### ISSUE TITLE
When both Serene Seasons and Create are installed Some of the Create's Ponder entries crash the game.

### ISSUE THREAD

**Issue by antauriprime** [Glitchfiend/SereneSeasons#359]
## Bug Report

Any of the Create's Ponder entries containing organics cause a crash if Serene Seasons is installed.
Plough's 4th section and the second page of the Mechanical Saw are 2 good examples.

### How can the crash be reproduced?

1. Ponder on the plough
2. Skip to 4th section

Video demo of reproduction steps:

[](https://user-images.githubusercontent.com/30935221/147861360-533c5215-1657-4600-914a-d998ba082e1a.mp4)

### Crash Report and Logs

https://pastebin.com/bUqDB1RM

### Mod Version
6.0.0.8

**Comment by Adubbz** [comment]
I would probably suggest reporting this to Create. Given it appears to be entirely in their code they'd be in a much better position to debug this

**Comment by Adubbz** [comment]
Oh actually, I see at the bottom there's a part relevant to SS. It seems they're doing something bad with unregistered biomes?

**Comment by antauriprime** [comment]
Ah, alright. I've already submitted this issue to the Create's github as well, just in case :)

**Comment by antauriprime** [comment]
The latest version of Create has finally fixed this issue! Hooray!
