### ISSUE TITLE
Rainbow Leaves

### ISSUE THREAD

**Issue by Lightaseption** [Glitchfiend/SereneSeasons#360]
### What feature are you suggesting?

There is a type of tree in Biomso'plenty Called Rainbow birch or something like this Well i really don't like to see when using Biomsoplenty and Serene both , Rainbow Birch Leaves will turn to another color by the season and will lose the rainbow color of it in every seasons, actually when using Serene there is no rainbow on their leaves and will be removed for all the game another says

**Comment by Forstride** [comment]
Can't seem to replicate this at all.  Likely a compatibility/settings issue with OptiFine
