### ISSUE TITLE
Request -- replace sensor and calendar with visually pleasing plant to indicate seasons

### ISSUE THREAD

**Issue by T3sT3ro** [Glitchfiend/SereneSeasons#363]
## Feature Request

I think it could be neat if the calendar and sensor were to be replaced by a single item -- a bonsai like tree (that can be planted in a pot), which reacts to seasons.

Rough concept of it's look presented below:

![seasonal bush](https://user-images.githubusercontent.com/5300963/148710937-3f093b3f-0563-4424-b625-f5ba5b63aa10.png)

### Why should it be added?

Aesthetics.

**Comment by Forstride** [comment]
I mean that might be cool as just a separate block?  But it's not really "readable" enough to completely replace the sensor/calendar.

**Comment by T3sT3ro** [comment]
The visuals can be adjusted in any way, and imo the main core models (winter=snow & cold, spring=green & blooming, summer=hot & burning, autumn=dying&colorful) are intuitive. IMO you could also add current season icon to the pot if you want to, but I would stay with the sole tree in a pot design. That way it is subtler and can be used in builds. I bet this concept could be honed to be more readable, but also I count on people's ability to connect the dots.

**Comment by Forstride** [comment]
>but also I count on people's ability to connect the dots

Yeah that's kind of the problem...People already have a hard time connecting a flower to Spring, sun to Summer, leaf to Autumn, and snowflake to Winter, and this would arguably be even more confusing for those people.

**Comment by T3sT3ro** [comment]
Well, kinda true, but there is another factor to that. I was in this confused state as well. I didn't get how the calendar worked the first time I saw it -- but it was due to how little interactivity it has and how it differs from compass or clock. With them you can see every so often how the texture changes and you *know* that it has some moving element. With the calendar it is really hard to notice any difference and display it in a pleasing way (it looks like a map and I assumed you have to interact with it with RMB). I think universal signs, such as snow covered leaves, falling leaves, blooming buds and colorful flowers are universal enough for that to work. I can't imagine someone not being able to understand, that icycles hanging from snow covered leaves mean winter.

**Comment by Forstride** [comment]
Closing this since I recently changed the calendar texture, and it's hopefully more readable
