### ISSUE TITLE
Request:  Render Calendar In Item Frame As Map

### ISSUE THREAD

**Issue by digitaltrucker** [Glitchfiend/SereneSeasons#367]
## Feature Request

</br>

### What feature are you suggesting?

 When the calendar is placed in an item frame, have it render as a map instead of as an item.</br>

### Why should it be added?

It would be much more visually pleasing.</br>

**Comment by Forstride** [comment]
The map has completely different rendering, so this probably wouldn't be possible.  However, I recently changed the Calendar texture, and it looks more appealing when used in an item frame
