### ISSUE TITLE
Suggestion: Real seasons

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/SereneSeasons#368]
## Feature Request

To be able to define the seasons in real time as in real life.

### What feature are you suggesting?

Add in the mod configuration the possibility to activate real time seasons based on real life. It will be synchronized by the computer in solo and on the local server time.

### Why should it be added?

This is a request from the RealSerene (https://www.curseforge.com/minecraft/mc-mods/realserene) mod which was unfortunately dropped in 1.12.2. I would like to be able to find it in the official mod in 1.17 or even 1.18!

**Comment by Forstride** [comment]
We don't have plans to add this to Serene Seasons itself, but there's a newer add-on that functions like RealSerene did: https://www.curseforge.com/minecraft/mc-mods/real-seasons
