### ISSUE TITLE
Other Modded Crops Config

### ISSUE THREAD

**Issue by theDaleighChronicle** [Glitchfiend/SereneSeasons#374]
### Overview

A config file to add crops to the seasonal fertility list (modded crops not already compatible.)

### Why would this feature be useful?

For mods that add crops but don't already has compatibility with Serene Seasons (in my case Cultural Delight.)

**Comment by Adubbz** [comment]
This can already be done through data packs.

**Comment by theDaleighChronicle** [comment]
Oh. So for those of us who can't code, we just have to kind of live with it. Okay then.

**Comment by Adubbz** [comment]
Datapacks require no knowledge of code, they’re purely json

**Comment by PaulerLeOne** [comment]
Could you explain how exactly can I add seasonal fertilty to modded crops with datapacks? What are the files to add?
