### ISSUE TITLE
The game lags badly

### ISSUE THREAD

**Issue by Dr-WeiAL** [Glitchfiend/SereneSeasons#375]
### What's the issue you encountered?

After upgrading the mod to version 7.0.0.15, the tps in the game is very low, and version 7.0.0.14 does not have this problem

### How can the issue be reproduced?

I have a lot of mods installed, among them Immersive Weathering and Snow! Real Magic! and Serene Seasons running the game lags badly

### Mod Version

7.0.0.15

**Comment by Adubbz** [comment]
I really don’t see how this would be possible, given there were no changes to the mod’s code between version 14 and 15. The only difference was that builds are now published to maven, which involves no code changes. I would need to see this reproduced with Serene Seasons on its own.

**Comment by Dr-WeiAL** [comment]
The problem suddenly disappeared and I don't know what happened to it, so I'll close the problem for now
