### ISSUE TITLE
Mod has permanently changed the biome I live in.

### ISSUE THREAD

**Issue by theyorkster** [Glitchfiend/SereneSeasons#376]
### What's the issue you encountered?

I am using this mod on a server for my friend and I and we were tired of how often it was snowing so we decided to delete the mod. I love the mod however.

 But we noticed that when the mod was deleted, somehow our biome that we live in which is a wet jacaranda field has been now turned into what is called a "shattered glacier" and now it only snows here and literally has changed the biome entirely. The foliage is more fit for an icy biome and again, it only snows.

 How can I fix this issue?(: thank you <3

### How can the issue be reproduced?

i dont know

### Mod Version

1.16.5

### Additional information

no new info

**Comment by Forstride** [comment]
Serene Seasons does not affect biome/world generation at all, so you must've deleted some other mod(s) as well.

**Comment by theyorkster** [comment]
i didn't.

**Comment by theyorkster** [comment]
any more ideas? I am at a loss for some myself.

**Comment by Forstride** [comment]
No, but we don't support 1.16.5 anyway so it doesn't really matter

**Comment by theyorkster** [comment]
What do you mean you don’t support it? If that’s the case then why is this
mod available for download in that version on Curse Forge? Wish you cared
more to help. Have a great day.

**Comment by Adubbz** [comment]
For the same reason that alpha versions of Minecraft can be downloaded. We don’t intend on scrubbing the internet of our historical works because we no longer support them.

**Comment by Forstride** [comment]
Even if we did still support those versions, what I said originally still stands.  Serene Seasons does not affect biome generation/placement/etc., so it is not an issue with Serene Seasons
