### ISSUE TITLE
Ambience Update: Northern lights etc.

### ISSUE THREAD

**Issue by Jonas4505** [Glitchfiend/SereneSeasons#377]
### Overview

There would be a chance for northern lights to occur at night. Mostly in very cold biomes with natural snow. I would also like to see that sun effect in hot biomes. I don't know how it's called but you'll see a picture if you google: Heatwave to hit Gauteng, Free State next, but won't be as hot as Western Cape - weather service... It's the first picture. My last suggestion is that in spring and fall there would be particles falling from trees. 

### Why would this feature be useful?

It would really improve the ambience and it generally would feel way more immersive. I think it would make Minecraft, in general, look prettier, especially the northern lights. And the particles could cover up the loss of the firefly haha.

**Comment by Forstride** [comment]
There are already other mods that focus on this like Dynamic Surroundings, and it would be a bit beyond the scope of what we want in Serene Seasons.
