### ISSUE TITLE
[1.18.2] Dynamic Surroundings resurrected sounds do not stop in winter

### ISSUE THREAD

**Issue by IceaPlayzPC** [Glitchfiend/SereneSeasons#378]
### What's the issue you encountered?

In Dynamic Surroundings (1.16 version), whenever it was winter for serene seasons, the biome sounds would stop to capture the silence of winter. However, for Dynamic surroundings resurrected, the sounds continue to play as if its any other season unlike in 1.16. Its not game breaking but a bit immersion breaking.

### How can the issue be reproduced?

-Download Dynamic Surroundings Resurrected
-Change season to winter
-Listen as sounds continue to play rather than going silent

### Logs

N/A

### Mod Version

1.18.2

### Additional information

I have reported this on DSR's github issue tracker as well, but i figure i'd report it here too in case its something with serene seasons.
Not sure if 1.18.2 is still supported as 1.19 was released 3 days ago but worth a shot

**Comment by Adubbz** [comment]
This is something that would be done on their side. Even in 1.16 we didn’t have any special integration with Dynamic Surroundings within Serene Seasons.

**Comment by IceaPlayzPC** [comment]
Alright, i figured so. Thank you!

**Comment by Adubbz** [comment]
For reference, the original integration with Serene Seasons was done through capabilities on Dynamic Surroundings’ side here: https://github.com/OreCruncher/DynamicSurroundings/blob/01707e27dd800509409c9830e7709aaac6cdc0de/src/main/java/org/orecruncher/dsurround/capabilities/season/SeasonInfoSereneSeasons.java. It appears the fork has stripped out this scheme which is rather unfortunate.
