### ISSUE TITLE
[Minor] Fallen birch leaves from Verdure have wrong tint

### ISSUE THREAD

**Issue by DarkShadow44** [Glitchfiend/SereneSeasons#379]
### What's the issue you encountered?

Birch leaves have the wrong tint, see image:
![2022-06-20_16 35 31](https://user-images.githubusercontent.com/2029892/174625489-9863be00-f352-4002-a4fe-86c2acd9797c.png)

### How can the issue be reproduced?

Use with Verdure mod and set season to MID_AUTUMN. Then place birch leaves and fallen birch leaves (Verdure) in a plains biome.

### Mod Version

Serene+Seasons-1.18.2-7.0.0.13

### Additional information

[Verdure](https://www.curseforge.com/minecraft/mc-mods/verdure) version 1.18.2-1.1.2

**Comment by Forstride** [comment]
Birch leaf coloring is hardcoded in Minecraft.  Ultimately there's not really much we can do to allow our seasonal coloring to apply to blocks that use their own hardcoded colors.
