### ISSUE TITLE
[Bug] Ice become water in cold biomes

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/SereneSeasons#38]
Hello,

In cold biomes, ice become water. The biome is "Cold Taiga" and come from Biome Bundle that is supposed to not adding any new biomes but re-use vanilla ones.

There is no settings for cold biomes in settings, only for tropical ones and all ice in cold biomes are transformed into water that is cause a large water flow and lag in the server.

Thank you in advance!

**Comment by Forstride** [comment]
I can't replicate this at all.  Regardless though, biomes that were already snowy aren't really affected by seasons at all.  You're likely in a biome that was never snowy to begin with and has a temperature above 0.15F

**Comment by ExDomino** [comment]
Ice should never become water in cold biomes.

**Comment by Forstride** [comment]
It *doesn't*.  I just told you I couldn't replicate the issue, and that the biome you're in likely isn't snowy.

**Comment by ExDomino** [comment]
Even if the word "cold" is in the biome name, it is not snowy for you?
Is it a Biome Bundle issue then? I create a repport in their github just in case.

**Comment by ExDomino** [comment]
But the F3 says that the biome is "cold". You really cannot do anything about that?
A kind of "compatiblity" option to make that all biomes with "cold" in the name is not affected by seasons? I know that this is a really ugly method, but this could save the problem. I mean, without any reset of the map on our server.

**Comment by ExDomino** [comment]
![autruche](https://user-images.githubusercontent.com/1377729/42709540-db9abfa0-86ae-11e8-9ebe-3b84eacce2f6.jpg)
