### ISSUE TITLE
Vines missing seasonal fertility information

### ISSUE THREAD

**Issue by MarioSMB** [Glitchfiend/SereneSeasons#380]
### What's the issue you encountered?

The Vines item is missing seasonal fertility information in its description. Twisting Vines and Weeping Vines correctly state that they can be grown year-round.

### How can the issue be reproduced?

N/A

### Mod Version

7.0.0.13

### Additional information

Vines can spread and be farmed in a similar manner to their Nether variants.

**Comment by Forstride** [comment]
Twisting Vines/Weeping Vines have the Forge crop growth hooks that Serene Seasons relies on to control crop fertility, whereas regular vines do not, meaning they can't/don't have any kind of interaction with crop fertility at all.
