### ISSUE TITLE
Serene Seasons (sereneseasons) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by Crystal-Spider** [Glitchfiend/SereneSeasons#382]
### What's the issue you encountered?

It doesn't happen every time, but like 1 out of 2 or 3 times.  
When I click play from the laucher the game loads for a bit and then crashes with the error message written in the title.

### How can the issue be reproduced?

I'm using [this](https://www.curseforge.com/minecraft/modpacks/crystal-modpack) modpack and often the game crashes on loading.  
To reproduce, download the modpack, install Optifine (don't know if this step is required to reproduce), launch the game a few times and in one of these times it should happen.

### Logs

https://gist.github.com/Nyphet/05bdc422eb78323a5a669ce1409d0262

### Mod Version

7.0.0.13

**Comment by Adubbz** [comment]
This was fixed in 8.0.0
