### ISSUE TITLE
Pam's Harvest Craft Compatibility 

### ISSUE THREAD

**Issue by Dragonslayer7532-dev** [Glitchfiend/SereneSeasons#386]
### Overview

in minecraft 1.18.2 as i was playing with this mod and all of the pam's mods i saw that the seeds do not have seasons with them like they used to i was wondering why and if this could be added back

### Why would this feature be useful?

more crops i'd guess

**Comment by Forstride** [comment]
Mod compatibility is on their end.  If they removed it at some point, we can't do anything about that
