### ISSUE TITLE
Colors not changing throughout the year

### ISSUE THREAD

**Issue by Pinecone6442** [Glitchfiend/SereneSeasons#387]
### What's the issue you encountered?

The minecraft colormap doesn't change, only appears to happen with dynamic trees but that's all. (1.12.2)

### How can the issue be reproduced?

Install the latest 1.12.2
join a world
see no colormap change

### Mod Version

latest

**Comment by Forstride** [comment]
We no longer support 1.12 or any versions below 1.19

**Comment by Pinecone6442** [comment]
> We no longer support 1.12 or any versions below 1.19

I fixed it
