### ISSUE TITLE
Feature Request: Ramping Crop Growth

### ISSUE THREAD

**Issue by im-hyps** [Glitchfiend/SereneSeasons#389]
### Overview

Currently, Serene Seasons nerfs crops when seasons are enabled.
This is because they either grow at normal speed, or a slower speed.

What I propose, is instead a system where they grow at a higher speed in their season, normal speed on either side of that, and then slower in winter.
While I don't have the exact numbers, it would mean that instead of crops growing at this rate;
100%
50%
50%
50%

They would instead grow at;
125%
100%
100%
75%.

### Why would this feature be useful?

This is overall more balanced for players, and would not just globally lower the growth of all crops while keeping the seasonal mechanic intact.

**Comment by Forstride** [comment]
If crop growth was buffed in-season instead of nerfed out-of-season, it'd make greenhouses completely pointless.  Also not every crop is only fertile in a single season, which would make this fairly unbalanced as you'd just receive a growth boost for essentially nothing.
