### ISSUE TITLE
[Suggestion] Add option to disable seasons in specifics biomes

### ISSUE THREAD

**Issue by ExDomino** [Glitchfiend/SereneSeasons#39]
Hello,

My suggestion is simple: for each biomes, add an options to disable all seasons effects in this biomes. For example we would like to disable it in all biomes that have the word "cold" in the name. Consider that is a new setting, like tropical one, to specify a biome that is cold. In these biomes, ice would no become water and it can snow every time like default vanilla settings.

Thank you in advance.

**Comment by thedeadman782004** [comment]
You can disable seasonal effect using the blacklist in the config folder.  Not ones that contain a certain keyword, but at least you can blacklist a specific biome.

**Comment by Forstride** [comment]
Currently all the blacklist does is prevent the grass/foliage color from changing
