### ISSUE TITLE
Season ticks update even when doDayCycle is false

### ISSUE THREAD

**Issue by 26Ivi** [Glitchfiend/SereneSeasons#393]
### What's the issue you encountered?

I'm working right now on a modpack and I'm using Serene Seasons with Hourglass, and works well, except when I set gamerule doDayCycle to false still updates the serene seasons tick tracker so isn't sync with the actual day count anymore

### How can the issue be reproduced?

Install Serene Seasons + Hourglass
Set gamerule doDayCycle to false
use /season get multiple times and see how it still updates

### Mod Version

Serene+Seasons-1.18.2-7.0.0.13

### Additional information

if you guys can fix it on 1.19 and 1.18 would be great since I have to publish this modpack in 3 months and I really don't know how to solve it myself

**Comment by Adubbz** [comment]
This is intentional. A separate game rule exists for seasons - ``doSeasonCycle``.

**Comment by 26Ivi** [comment]
> This is intentional. A separate game rule exists for seasons - `doSeasonCycle`.

Oh, thanks
