### ISSUE TITLE
I fixed a problem I had in the PT-BR translation!

### ISSUE THREAD

**Issue by seriousfreezing** [Glitchfiend/SereneSeasons#395]
### Overview

I have a modpack with SereneSeasons, but one problem I was having is that the translation is incomplete, thus not having the translation for the beginning, middle and end of the seasons!

### Why would this feature be useful?

[pt_br.zip](https://github.com/Glitchfiend/SereneSeasons/files/10149745/pt_br.zip)
Then I ask you to post this correction of the translation I made!

**Comment by seriousfreezing** [comment]
I made for: SereneSeasons-1.19.2-8.1.0.24

**Comment by Adubbz** [comment]
Please submit your translation as a pull request so it can be merged into the repo
