### ISSUE TITLE
Crash on start: java.lang.NoSuchFieldError: f_122901_

### ISSUE THREAD

**Issue by SonOdin** [Glitchfiend/SereneSeasons#399]
### What's the issue you encountered?

Hi, 
when I start Minecraft 1.19.3 with this Mod (Serene Seasons) it crashes. java.lang.NoSuch.FieldError: f_122901_ 
It is a fresh Minecraft installation with only Forge 44.0.37 installed. I have this issue and my friend, too. What are we doing wrong?

### How can the issue be reproduced?

Start Minecraft with Forge 44.0.37 and Mod Version: SereneSeasons-1.19-8.0.0.19

### Logs

https://gist.github.com/SonOdin/01abe5871b89bca421d94c5a7b370b48

### Mod Version

8.0.019

**Comment by Adubbz** [comment]
You can’t use the 1.19 version on 1.19.3. You need to download the 1.19.3 version.
