### ISSUE TITLE
When serene seasons is installed, tough as nails rain collectors will fill up with water during rainy weather, even if it is not actually raining in that biome

### ISSUE THREAD

**Issue by IceaPlayzPC** [Glitchfiend/SereneSeasons#400]
### What's the issue you encountered?

So, while I was playing on my 1.19.2 world, I noticed that during the middle of dry season in a lush desert biome (late summer early fall period), my rain collectors still collected rain. So I thought, huh, that's odd. Since Lush Deserts usually rain I thought it was because of that, but while writing this report I decided to try a mesa biome during times where it doesn't rain there. Rain collector filled up. I tested on an instance with no other mods but tough as nails and the rain collector did not fill up, meaning this is an issue with serene seasons being installed. Since idk if its tough as nails causing this or serene seasons causing this, I'll be posting this bug report to both GitHubs.
This bug is present in the latest 1.19.3 versions of both mods as well, as I have tested that to see if the bug was relevant to the latest versions of each mod.

### How can the issue be reproduced?

1. Either go to a tropical biome that rains normally and switch to dry season in Serene Seasons, or go to a biome that doesn't normally receive rain
2. place down rain collector and toggle rain
3. wait for a bit as the rain collector fills with water

### Logs

n/a

### Mod Version

1.19.3

### Additional information

If this report only fits under the tough as nails github feel free to close it, as i have posted this same report over there too.

**Comment by Adubbz** [comment]
This has been fixed in Tough As Nails as of 1.20.4.
