### ISSUE TITLE
Serene seasons crashing upon world creation/join

### ISSUE THREAD

**Issue by ShadOhh** [Glitchfiend/SereneSeasons#403]
### What's the issue you encountered?

I added serene seasons to my modpack. Starting and launching the game no problem. But upon world creation/join it crashes minecraft with exit code -1

### How can the issue be reproduced?

Using my modpack that i made
[V2.zip](https://github.com/Glitchfiend/SereneSeasons/files/10716957/V2.zip)

### Logs

https://gist.github.com/ShadOhh/07d95053acd8460bf62f738646092c6b

### Mod Version

8.1.0.24

**Comment by Sc2Marines** [comment]
Hello ShadOhh, The problem come from immersive portal.
I have exactly the same issue with my modpack.
To solve it you can delete cerene season or immersive portal.
I'm looking for an other solution but actually I didn't find.

**Comment by Adubbz** [comment]
Superseded by #432
