### ISSUE TITLE
Serene Seasons and Tough as Nails crash on Startup

### ISSUE THREAD

**Issue by kbobthor** [Glitchfiend/SereneSeasons#406]
### What's the issue you encountered?

Loaded up a survival game with Serene Seasons and Tough as Nails along with some other mods. I was able to get into a game and play for a few minutes before the game crashed and I got this message. Now I cant even load into a new world without the game crashing immediately. I have tried to disable all mods except Serene Seasons and Tough as Nails, still cant create or load into any world without crashing immediately. Made a new instance on Forge with just TaN and SS, crashed immediately with the same error

### How can the issue be reproduced?

Make an instance of Minecraft 1.19.3 on Forge 44.1.20 SereneSeasons-1.19.3-8.2.0.29.jar and ToughAsNails-1.19.3-8.1.0.88.jar as the only two mods. Create a new world and the game will immediately crash when loading into it. 

### Logs

https://gist.github.com/KyleLinder/0a962638e96a54e48e3ed3f8e76b6c84

### Mod Version

SS 8.2.0.29 and TaN is 8.1.0.88

**Comment by Forstride** [comment]
For now downgrade Serene Seasons to 8.2.0.27.  I had updated Serene Seasons to use biome tags instead of the config system, but didn't realize Tough As Nails used it at all and didn't update that to compensate.

**Comment by Adubbz** [comment]
This has been fixed
