### ISSUE TITLE
[Feature] Add project to modrinth.com

### ISSUE THREAD

**Issue by Sammcb** [Glitchfiend/SereneSeasons#407]
### Overview

Hi, would it be possible for you to add this mod to [modrinth](https://www.modrinth.com)?

I would love to see this mod on Modrinth so I can use it with the modpack manager I am creating!

Thanks so much!

### Why would this feature be useful?

Personally, I would find it really useful to have the option to download this mod from Modrinth so I can use it with my modpack manager. Thanks!

**Comment by Forstride** [comment]
No
