### ISSUE TITLE
Grass blocks aren't winter tagged so you can't use bonemeal on them in cold biomes

### ISSUE THREAD

**Issue by Insane96** [Glitchfiend/SereneSeasons#412]
### What's the issue you encountered?

Not sure if it's intended but you can't use bonemeal on grass blocks when in cold biomes.

### How can the issue be reproduced?

Use bonemeal on grass in a cold biome

### Mod Version

8.2.0.38

**Comment by Forstride** [comment]
Yes this is intentional
