### ISSUE TITLE
Season Cycle set to false still updates seasons (MC 1.19.2)

### ISSUE THREAD

**Issue by vinnyg0621** [Glitchfiend/SereneSeasons#413]
### What's the issue you encountered?

in my map, the gamerule doSeasonCycle is set to false. but when I set it to mid spring, it later changed to late spring.
MC version: 1.19.2
Forge version: 43.2.8

### How can the issue be reproduced?

when gamerule doSeasonCycle is set to false, make the seasons stop changing.

### Mod Version

8.1.0.23

### Additional information

every time this happens, I always have to type the command /season set [season], even when the gamerule is set to false

**Comment by vinnyg0621** [comment]
someone please help

**Comment by Adubbz** [comment]
I can't reproduce this, especially on the latest version. If this was a server it may have been part of a sync issue on server logins which has just been fixed. If this still occurs on 1.20.4 then feel free to reopen this, though I will need more details as to how to get it to happen.
