### ISSUE TITLE
Suggestion: Make the Calendar placeable.

### ISSUE THREAD

**Issue by Ezeyra** [Glitchfiend/SereneSeasons#418]
### Overview

Make the calendar item placeable. 

### Why would this feature be useful?

I wouldn't have to go rummaging through my messy storage system every time I wanted to check if the season has changed. I could place it on a wall in my base and have it always at the ready while also being decorative.

**Comment by Forstride** [comment]
It is placeable in an item frame, and it will continue to update properly when placed in one.  Other than that, we don't have any plans to make a separate block/tile entity for it.
