### ISSUE TITLE
[Sorry, Not 1.19.4+]  [1.19.2]   About the snow melting

### ISSUE THREAD

**Issue by fenlincao** [Glitchfiend/SereneSeasons#419]
### What's the issue you encountered?

When switching from winter to spring, the unloaded block will not update the snow, resulting in the snow in winter will not melt until the next update block, and the speed of melting is very slow, which greatly affects the game. It is hoped that all the snow will be removed when the color changes from winter to spring.Finally, thanks again and hope to resolve the bug as soon as possible, and hope to fix this issue in the next update 1.19.2.

### How can the issue be reproduced?

1.Create a world
2.Change the seasons, adjust the weather to rainy days,and go around and update blocks
3.When enough snow falls, the weather changes to sunny days and the season changes to spring

### Mod Version

1.19.2-8.1.0.24

**Comment by Forstride** [comment]
Snow melting has nothing to do with block updates, and I can't replicate this either way.  Just know that snow can still exist in Spring in some biomes if it's cold enough (Taiga, Windswept Forest, etc.), and in some cases won't melt until Late Spring or even Early Summer.

**Comment by fenlincao** [comment]
@Forstride  I'm sorry to bother you again. Maybe I didn't make it clear, which led to your misunderstanding. Please allow me to explain again. 
well, it's true that block updates have nothing to do with snowmelt, and snowmelt does depend on temperature, maybe my issues should be changed to advice.  I mean, before adding this mod, most biomes would not snow, but after adding this mod, these biomes will start to snow, which is a good thing, However, it must be noted that it is a long time to wait for the snow to melt naturally, which usually wastes a lot of time, so I hope that the snow can be directly removed when the season changes from winter to spring.
There is a mod called Immersive Snow, which perfectly expresses my meaning, but it has some issues because it is not created by the same author and the mod seems to have stopped, I just hope you can integrate it directly onto Serene Seasons so that it can be perfectly matched.
Thank you again!

**Comment by iKollor** [comment]
Bump!
