### ISSUE TITLE
An option to adjust which mobs can spawn during seasons

### ISSUE THREAD

**Issue by GrandmaPork** [Glitchfiend/SereneSeasons#420]
### Overview

Basically how crops work but with mobs. Maybe like a season whitelist/blacklist that you can add/remove mobs from

### Why would this feature be useful?

When using mods like alex mobs, it's odd to have birds and other non-winter mobs spawning in during winter.

**Comment by Forstride** [comment]
This already was a feature at one point, but the problem with it is that passive mobs spawn WAY less frequently after a chunk has already been generated.  Say you explore a new area during winter when nothing is spawning, you would then have an extremely hard time finding mobs in that area during summer.

We'd have to mess around with mob spawn caps for it to feel right, and not only is that a bit too invasive/out of scope for the mod, but it could be very problematic when factoring in other mob mods.

**Comment by GrandmaPork** [comment]
Oh splendid. I love it when Minecraft breaks like this
