### ISSUE TITLE
Custom models/textures for leaves for seasons where they loose their leafs

### ISSUE THREAD

**Issue by T3sT3ro** [Glitchfiend/SereneSeasons#421]
### Overview

It would be nice to have some intermediate stage of leaves that start randomly replace leaf blocks during fall/winter. Leaves would go through several stages of loosing leaves, leaving "branches" blocks. Evergreen trees would not leave their leafs during winter. The mechanism should be similar to how temporary ice (created with boots + frost walker) is melts or the mechanism of how plants grow. I imagine it would be drop leafes on random tick depending on the season.

Branches blocks would have higher chance of dropping sticks when broken.

### Why would this feature be useful?

It would look cool and realistic.

**Comment by Forstride** [comment]
This has already been suggested multiple times, but it will not be implemented.  I can assure you it would not look good
