### ISSUE TITLE
Feathers compatibility

### ISSUE THREAD

**Issue by ManeBOI** [Glitchfiend/SereneSeasons#422]
### Overview

feathers is a stamina mod for other mods for example elenai dodge. Feathers has a feature where if you're in a snowy biome the stamina(feathers) would freeze but when used with serene seasons it doesnt work if it winter

### Why would this feature be useful?

imo if using with feathers it would nicely balance the dodge mechanic and others

**Comment by Forstride** [comment]
They'd have to add compatibility using our API
