### ISSUE TITLE
Logspam using Dimensional threading

### ISSUE THREAD

**Issue by SrRapero720** [Glitchfiend/SereneSeasons#423]
## ISSUE
when dimensional threading is enabled causes a constant logspam
![image](https://github.com/Glitchfiend/SereneSeasons/assets/29090346/4c9df0b2-b8fa-449e-b632-8c5d6e6bde2d)

-----
disabling dim threads fixes it. but basically i can't use dimensional threads

### How can the issue be reproduced?

- instal sereneseasons + [Dimensional Threading](https://www.curseforge.com/minecraft/mc-mods/dimensional-threading-reforged)
- Run a server
- logspam

### Logs

N/A

### Mod Version

SereneSeasons-1.18.2-7.0.0.15.jar

### Additional information

N/A

**Comment by Adubbz** [comment]
This was already been resolved in a newer version.
