### ISSUE TITLE
Game Crashed While Ticking Player 1.19.3

### ISSUE THREAD

**Issue by whammmy** [Glitchfiend/SereneSeasons#424]
### What's the issue you encountered?

opened a world i had aready been playing in for a while. As soon as it tried loading the terrain and stuff it crashes and gives the the error 
"The game crashed whilst ticking player Error: java.lang.NoClassDefFoundError:sereneseasons/config/BiomeConfig"

### How can the issue be reproduced?

By trying to open the world

### Logs

https://gist.github.com/whammmy/7c1af0d153c87a3a2a013b6d2daaa4a1#file-crash-2023-07-29_19-33-23-server-txt

### Mod Version

8.2.0.28

**Comment by Adubbz** [comment]
Redownload the mod. This seems to me like you've probably gone and deleted part of the mod's code when trying to delete config files

**Comment by whammmy** [comment]
I just tried making another world, and it seems as soon as the effect you spawn with wears off the game crashes. 

I'm not sure if this issue is realated, but in the datapack selections it says that serene seasons is made for an older version.

**Comment by whammmy** [comment]
> Redownload the mod. This seems to me like you've probably gone and deleted part of the mod's code when trying to delete config files

idk how this would've happened bc all I did was put the mod into my mods folder, but i did reinstall the same version. You were right, it works now. thanks
