### ISSUE TITLE
[NOT 1.19.4, 1.18.2] Biomes on Winter turn permanently into snow biomes upon mod deletion

### ISSUE THREAD

**Issue by Catomax262** [Glitchfiend/SereneSeasons#426]
### What's the issue you encountered?

For some reason, my home biome is catalogued as a warm biome, but after deleting this mod, it turned permanently into a snow biome, and the water nearby is freezing a lot + constant snowfall when raining. This is annoying considering that my mob farms with water are freezing and not working.

### How can the issue be reproduced?

1. Wait until it's winter
2. Delete this mod from the folder
3. It's now locked into winter

### Logs

n/a

### Mod Version

7.0.0.13

**Comment by Forstride** [comment]
Closing this since it's not a supported version, and no one else has ever reported this as an issue (Nor do I think it's even possible for this to happen).
