### ISSUE TITLE
how to change the season?

### ISSUE THREAD

**Issue by NutiYTGitHub** [Glitchfiend/SereneSeasons#430]
### Overview

I have a question, I want to change the season from summer to winter and I don't know how to do it, please help

### Why would this feature be useful?

I have a question, I want to change the season from summer to winter and I don't know how to do it, please help

**Comment by Adubbz** [comment]
Please do not open issues for general questions like this, they are much better suited for Discord. The ``/season set`` command does what you want.

**Comment by Forstride** [comment]
You can find the commands on the wiki here: https://github.com/Glitchfiend/SereneSeasons/wiki/Commands

And for future reference, please don't open issues for basic questions like this.  Use our Discord server
