### ISSUE TITLE
[1.19.2] Immersive Portals crash (1.18 fix doesn't work) (IP dev needs access to source code)

### ISSUE THREAD

**Issue by ThisIsSP4RTAN** [Glitchfiend/SereneSeasons#432]
### What's the issue you encountered?

Instant crash when creating a new world when using Serene Seasons and Immersive Portals

### How can the issue be reproduced?

Just load the game and try to create a new world while using Serene Seasons and Immersive Portals

### Logs

https://gist.github.com/SeVeredC0nnection/08963d4fc5a2e3894273234bc62b1df2

### Mod Version

8.1.0.24

### Additional information

Nick1st_ (Maintainer of Immersive Portals) has stated he needs access to the Serene Seasons source code in order to fix this but maybe you could take a look at his source code and apply a fix to it.
https://github.com/iPortalTeam/ImmersivePortalsModForForge

The fix that partially solved the issue for 1.18.2 does not seem to work in 1.19.2
https://github.com/Glitchfiend/SereneSeasons/issues/390#issuecomment-1236045863
https://github.com/iPortalTeam/ImmersivePortalsModForForge/commit/cf57371a6e31e9b2152a3bf2695ddd273ebb5403

**Comment by Adubbz** [comment]
In the case of 1.20.2, the source is now available

**Comment by CalaMariGold** [comment]
Is it possible that this can be fixed for 1.19.2?

**Comment by Forstride** [comment]
Closing this since they work fine together on Fabric 1.20.4, and the Forge port of Immersive Portals isn't updated past 1.19.2.
