### ISSUE TITLE
[Request} Thermometer

### ISSUE THREAD

**Issue by PlayfulPiano** [Glitchfiend/SereneSeasons#433]
### Overview

Add a "Thermometer" item which shows the current temperature where you are, affected by biome, season, etc.
Bonus if it could gain Curios support.

### Why would this feature be useful?

Like with the Calendar showing the current season and subseason, adding a Thermometer item to say the current biome's temperature based on the season impact would also be helpful/informative for considering snow/rain thresholds or any of the other vanilla temperature impacts.

**Comment by Forstride** [comment]
Not sure if this was accidentally posted here instead of the Tough As Nails repo, but Serene Seasons has nothing to do with this, and the Thermometer was re-added to TAN in 1.20.4 anyway

**Comment by PlayfulPiano** [comment]
> Not sure if this was accidentally posted here instead of the Tough As Nails repo, but Serene Seasons has nothing to do with this, and the Thermometer was re-added to TAN in 1.20.4 anyway

No this is intentionally for Serene Seasons, not TAN, and is mainly to consider snow generation / rain generation during weather instances.

**Comment by Forstride** [comment]
I mean, you can just see if it'll rain or snow when it actually happens (*And* you'll already see ice start to form even before then).  Definitely not necessary enough to add an item just for that.
