### ISSUE TITLE
Installing Serene Seasons later causes Season sync issues on loaded Chunks

### ISSUE THREAD

**Issue by kispintyi** [Glitchfiend/SereneSeasons#434]
### What's the issue you encountered?

Upon installing the mod after we generated a few chunks those chunks didn't work together with Serene Seasons even after in-game days and it caused a Season sync issue.

### How can the issue be reproduced?

Boot up modded 1.20.1
Play for a while, load a few chunks
Quit
Download Serene Seasons Mod 1.20.1
Boot up modded 1.20.1 again with Serene Seasons
Observe the issue
# Picture:
![image](https://github.com/Glitchfiend/SereneSeasons/assets/116653691/90bffd12-cfbd-4f9c-aa84-5c2fbf218c06)

### Mod Version

9.0.0.46

**Comment by Forstride** [comment]
I don't see anything wrong in that screenshot (Although it's also dark and not easy to see where any individual chunk issues would be).  The biome on the left looks like a Sparse Jungle, which is going to use tropical seasons rather than the temperate seasons that the biome on the right is using.

**Comment by kispintyi** [comment]
When its snowing everywhere (winter) it doesn't snow near my house for example

**Comment by Forstride** [comment]
You'd have to take a screenshot of that with the biome info.  Also snow only falls in a limited radius around players, even if your render/simulation distance is set high.  It's the same way vanilla snow works.

**Comment by Adubbz** [comment]
Closing this, as @Forstride said, more information would be needed here to deem this as a bug. Snow only occurs in a limited radisu around players and not in all biomes (neither of which are bugs)
