### ISSUE TITLE
Issues when Running Along with Sodium/Oculus (1.20.1)

### ISSUE THREAD

**Issue by NGRenner** [Glitchfiend/SereneSeasons#435]
### What's the issue you encountered?

Unsure if this is known or something that should be posted here, but I thought id report it.

Using Rubidium/Sodium with Oculus along with this mod causes a weird mishap where only the colors of birch trees change, nothing else (shown in picture). Everything else seems to work properly. 

![2023-11-20_22 54 37](https://github.com/Glitchfiend/SereneSeasons/assets/124471876/0af06d20-a0d6-44f2-901e-400b5e1c38df)

Not sure if this mod is intended to work with Sodium/Oculus or Optifine, but its just something i observed.

### How can the issue be reproduced?

 Have Rubidium, Oculus installed via Forge (.238.1.1) and run Serene Seasons on Minecraft.

### Mod Version

9.0.0.46

**Comment by Forstride** [comment]
It's an issue with a specific version of Rubidium.  From what others have said, downgrade to a version below 0.7, or use Embeddium instead, which people are recommending over Rubidium now.
