### ISSUE TITLE
Sugarcane NO hieght limit?

### ISSUE THREAD

**Issue by Aceplante** [Glitchfiend/SereneSeasons#439]
### What's the issue you encountered?

Sugarcane seems to have NO limit at all (in the summer?), quickly resulting in it being dozens of blocks tall...

This feels very weird and it should definitely be capped at about 8-10 or so?

Edit: I suppose I didnt test it with solely your mod, but I figured it was yours

### How can the issue be reproduced?

yes

### Mod Version

1.19.2

**Comment by Adubbz** [comment]
This is not an issue with Serene Seasons.
