### ISSUE TITLE
uh.. placable calandar?

### ISSUE THREAD

**Issue by Aceplante** [Glitchfiend/SereneSeasons#440]
### Overview

Im surprised this isnt a thing already and even more surprised no one seems to have suggested it?? Basically, it would place similar to a painting and look like an actual calendar showing the season and day?

(also I know it says "1.20.2+", but hopefully this can be added to 1.18.2 as well?, or at least 1.19.0 for obvious reasons)

### Why would this feature be useful?

Because it would allow you to easily see exact day and season, plus placing it would be cool. As of now you can put it in an item frame I guess but it seems really weird to not be able to hang a calendar.

**Comment by Romb0ne** [comment]
Placing it in a item frame should work?

**Comment by Adubbz** [comment]
Placing calendars in item frames is the way to go here. If they don't work as expected when doing that then obviously that would be a bug, though to my knowledge they work fine. This is consistent with Vanilla not supporting placing clocks on the wall, and instead encouraging the use of item frames.
