### ISSUE TITLE
Apparent incompatibility with Terralith.

### ISSUE THREAD

**Issue by Axxyxe** [Glitchfiend/SereneSeasons#441]
### Overview

I have not found anything about this online, but it seems like this mod isn't compatible with Terralith; in the "Winter" season, any snow that falls does not melt in the mod's biomes, but they do appear to melt in vanilla ones. 

### Why would this feature be useful?

It would be very helpful to be able to add modded biome IDs into some kind of list in the config, where their seasonal colors and weather effects can be set.

**Comment by Forstride** [comment]
1) If snow is falling in their biomes in the winter, it *should* melt once the temperature is high enough.  The temperature is likely still just low enough in some biomes in early/mid spring to still have snow.

2) You can change that with a datapack.  There's an example datapack in the pinned messages on our Discord server, or you can just look at the default biome tags here: https://github.com/Glitchfiend/SereneSeasons/tree/1.20.2/src/main/resources/data/sereneseasons/tags/worldgen/biome
