### ISSUE TITLE
{1.12.2} Serene seasons kicks me out

### ISSUE THREAD

**Issue by Gallaxau** [Glitchfiend/SereneSeasons#443]
### What's the issue you encountered?

I created a server with serene seasons ans when i try t o join i get kicked out

### How can the issue be reproduced?

Make a server and download mustard zombie modpack along with winter zombies then start the server and join it

### Logs

https://mclo.gs/Q8VpOlS

### Mod Version

1.2.18

**Comment by Gallaxau** [comment]
java.lang.ArrayIndexOutOfBoundsException: -5
at sereneseasons.season.SeasonTime.getSubSeason(SeasonTime.java:67)
at sereneseasons.init.ModHandlers.lambda$registerSeasonColourHandlers$1(ModHandlers.java:73)
at sereneseasons.init.ModHandlers$$Lambda$381/1047719887.func_180283_a(Unknown Source)

**Comment by Forstride** [comment]
We don't support 1.12, but this is likely due to you setting the season time to a ridiculous value, causing integer overflow.  Granted this was fixed in newer versions, but either way we don't support 1.12
