### ISSUE TITLE
Seasons reset upon server restart

### ISSUE THREAD

**Issue by JSDrums1** [Glitchfiend/SereneSeasons#444]
### What's the issue you encountered?

When a server is stopped and restarted, the seasons reset to early spring, and are not persistent through the restart.

### How can the issue be reproduced?

Stop and restart a server

### Mod Version

9.0.0.46

**Comment by Adubbz** [comment]
I can't seem to reproduce this as of 1.20.4 at least, so presumably this has already been fixed in a later version.
