### ISSUE TITLE
level.isRainingAt(BlockPos) not working as expected

### ISSUE THREAD

**Issue by CreativeMD** [Glitchfiend/SereneSeasons#447]
### What's the issue you encountered?

Someone reported an issue of AmbientSounds playing rain sounds in the desert. It seems like the method `level.isRainingAt(BlockPos)` is not working properly. Somehow it returns `true` even the block position is inside a desert. This method is true even though there is no visible rain ([Change in question](https://github.com/Glitchfiend/SereneSeasons/blob/1.20.4-multi/common/src/main/java/sereneseasons/mixin/MixinLevel.java))

### How can the issue be reproduced?

Call the method with a block position inside a desert. In vanilla it should return false, but with Serene Seasons installed it will return false.

### Mod Version

9.0.0.46

**Comment by Billnotic** [comment]
In addition, this affects all mobs, modded or vanilla, which check if it is raining and take damage (eg. vanilla endermen or alexmobs gusters).

**Comment by CreativeMD** [comment]
Apparently this got fixed in 1.20.4, would be cool to have a port back to 1.20.1
