### ISSUE TITLE
Crash on world load neoforge/20.4

### ISSUE THREAD

**Issue by Abalieno** [Glitchfiend/SereneSeasons#450]
### What's the issue you encountered?

I wanted to test Tough as Nails, which seems to hard depend on Serene Seasons (or it won't launch on neoforge).

Loads fine, but crashes when joining a world.

### How can the issue be reproduced?

Join a world.

Using my own test here, in case there may be conflicts: https://legacy.curseforge.com/minecraft/modpacks/gregorian-anagogy/

### Logs

https://gist.github.com/Abalieno/3e261d5d2d24abad81b316452909444e

### Mod Version

SereneSeasons-neoforge-1.20.4-9.3.0.16

**Comment by Adubbz** [comment]
The crash you've provided can probably be resolved be deleting your config file and allowing it to regenerate. Though TAN shouldn't have a hard dependency on Serene Seasons. If there is, that's unintentional

**Comment by Abalieno** [comment]
Nope, deleting configs and creating a new worlds still leads to the same crash.

**Comment by amzelee** [comment]
try removing all instances of TAN and SS mods including config files etc and launch minecraft then enter a world or something to see if it gets fixed. Then download the latest versions of TAN and SS and put them in.
