### ISSUE TITLE
can't seem to find the sub season config

### ISSUE THREAD

**Issue by T3rryScary357** [Glitchfiend/SereneSeasons#453]
### What's the issue you encountered?

the only config i have id fertility and seasons
<img width="1211" alt="Screenshot 2024-02-04 234543" src="https://github.com/Glitchfiend/SereneSeasons/assets/158995981/3675ee23-dd2a-439a-b1b3-6f563763e594">

### How can the issue be reproduced?

can't find the config 

### Mod Version

1.20.1

**Comment by T3rryScary357** [comment]
i found the config file. why is it in the save file though?

**Comment by Forstride** [comment]
Because that's how Forge's synced server configs work
