### ISSUE TITLE
Wintertime Floods Planet

### ISSUE THREAD

**Issue by Epik-B0mber** [Glitchfiend/SereneSeasons#463]
### What's the issue you encountered?

Upon the dawning of winter in my server, it began snowing, and I watched in abject horror as the entire map was replaced with ice, which then turned into water and just flooded everything. Why is this even a feature? It literally destroyed my entire world :(
![2024-03-17_19 28 43](https://github.com/Glitchfiend/SereneSeasons/assets/30029656/9e419ac1-3630-4131-8843-531d08ef2cd9)

### How can the issue be reproduced?

1. Wait for winter to come
2. Watch your world burn-- or, thaw I guess

### Mod Version

9.2.0.5

**Comment by Forstride** [comment]
1) You're on an outdated version of the mod for 1.20.2, which we don't support.  And I can't replicate this in 1.20.4 at all.

2) It's far more likely that this is a "conflict" with a different mod, as Serene Seasons doesn't even directly place the ice blocks.  We only change where the game considers it cold enough for snow/ice to form, and then the actual placing of those blocks is handled by vanilla (Or another mod if they're overriding that).  As for which mod, you'd have to test and find out for yourself, but Snow Real Magic is one mod that's a common culprit for conflicts with Serene Seasons, so if you have that installed, I'd suggest removing it.

**Comment by Epik-B0mber** [comment]
I did not have that specific one but I will do some tests with whatever mods I transfer to 1.20.4 later on, thank you for the clarification.
