### ISSUE TITLE
Does not work on older worlds

### ISSUE THREAD

**Issue by Zeoys1** [Glitchfiend/SereneSeasons#464]
### What's the issue you encountered?

So i use a world that i think i created in 1.16.5. But i use this world for when i play 1.20.1. But the problem is that any crop can grow during any season. This is the settings i use, again, works perfectly on other worlds.
![6aac96608faaed838c4dfb08ea511c7b (1)](https://github.com/Glitchfiend/SereneSeasons/assets/165967357/4567f2d4-ede9-4a39-814e-269d3a4b9b2b)

### How can the issue be reproduced?

1. Join the world thats created during an older version
2. Try to farm like regular

### Mod Version

1.20.1

**Comment by Forstride** [comment]
1) We don't support 1.20.1, but there's no reason it wouldn't work on an existing world unless you have some kind of datapack or something in that world that's breaking the crop fertility tags and causing them to be fertile year-round.

2) If this is in regards to modded crops, it will only work if they use Forge's crop growth hooks.

**Comment by Zeoys1** [comment]
> 1. We don't support 1.20.1, but there's no reason it wouldn't work on an existing world unless you have some kind of datapack or something in that world that's breaking the crop fertility tags and causing them to be fertile year-round.
> 2. If this is in regards to modded crops, it will only work if they use Forge's crop growth hooks.

What do you mean you dont support 1.20.1? Thats the version i use no datapacks. No modded crops, im talking about wheat, carrots etc.

**Comment by Forstride** [comment]
I mean we don't support 1.20.1, whether that's bug fixes or other forms of providing support.  We only ever support the latest version of Minecraft, which right now is 1.20.4.

Either way, the only reason it wouldn't work on one world, but works on others is something with your setup, not the mod itself.
