### ISSUE TITLE
Ability to set season in survival

### ISSUE THREAD

**Issue by Wertyhappy27** [Glitchfiend/SereneSeasons#465]
### Overview

Some type of firework rocket, or machine, that can set the season while in survival, a good example is the Fallout 4 weather fireworks, craft with ingredients that would be fit for each season, can only be used once in a while.

### Why would this feature be useful?

In the cases where you don't want to deal with a season, and dont want to use commands, examples where you are building, winter hits, and you would rather not deal with snow (oddly specific case, I know)

**Comment by Forstride** [comment]
I don't like this idea at all personally.  I mean if someone wants to make some kind of add-on for that they're more than welcome, but I'm definitely not implementing this in SS itself.

**Comment by Wertyhappy27** [comment]
Could you share how one could possibly add it?

**Comment by Forstride** [comment]
Learn how to make mods and use our API for the season-related stuff I guess?
