### ISSUE TITLE
Biome climate checking

### ISSUE THREAD

**Issue by JedaiGames** [Glitchfiend/SereneSeasons#470]
### Overview

Well. I don't know is it bug, or is it vanilla minecraft behaviour. But here's the thing:
Stony beach biome in minecraft can generate in various places, either near hot biomes and cold one.
It becames even worse if you use generation changing mods such as tectonic, that allows stony shore to be generated a lot deeper in the terrain, at various height. Wich leads to a problem: 
In your mod stony shore counts as cold winter biome, wich leading to situations when surrounding area can be tropical biomes, deserts, warm ocean without ice, while stony shore covered in snow and water nearby frozen.

Maybe there is a safe way to dinamicaly change climate of biome, based on what biome he surrounded with? So things like this doesn't break immersion with illogical stuff? Just changing stony shore to warm biome probably won't work, because in that case we will have opposite - warm biome without snow, surrounded by cold oceans and snow mountains.

### Why would this feature be useful?

Problem with snow mid land causes breaking of immersion.

**Comment by Forstride** [comment]
>In your mod stony shore counts as cold winter biome

Not in newer versions.  It's been blacklisted for a while now, so it doesn't have any seasonal effects at all.
