### ISSUE TITLE
start the game + mods + serene seasons mod = Error 1 { 1.18.2 V } 

### ISSUE THREAD

**Issue by nonames218** [Glitchfiend/SereneSeasons#472]
### What's the issue you encountered?

Before I start, I am not proficient in the English language,okay .

when i start the game with _**serene seasons mod**_ will crash and saw a error 1,

 but i when i start the without the _**mod**_ will not happen any thing,

 same when the _**mod**_ only without the mods  .

idk why?
so 
i need help plz😢

### How can the issue be reproduced?

idk whats mean this ?

### Logs

https://gist.github.com/nonames218/81e6926b120a8d229f353e9fe5ba12a4
### Mod Version

1.18.2-7.0.0.15 and 1.20.6-9.4.0.4

**Comment by Forstride** [comment]
Aside from the fact that the log you posted doesn't mention Serene Seasons at all, we do not support versions below 1.20.6

**Comment by nonames218** [comment]
oh This is weird it was in mods file when i start it both (1.18.2 and 1.20.6 ) but in 1.20.6 an error 
![1 20 6](https://github.com/Glitchfiend/SereneSeasons/assets/170136881/31c480f4-fb97-4a02-9ccc-fa575fb9e41b)
![1 2 0 6](https://github.com/Glitchfiend/SereneSeasons/assets/170136881/a29a9c6a-b934-4b58-8f61-fef9c6881c7e)

**Comment by nonames218** [comment]
This is weird it was in mods file when i start it both (1.18.2 and **_1.20.6_** ) _**SAME PROBLEM**_ {Error 1} but thx
