### ISSUE TITLE
Frozen waterlogged blocks in winter

### ISSUE THREAD

**Issue by jacksonmagas** [Glitchfiend/SereneSeasons#477]
### Overview

Add the ability for waterlogged blocks to freeze/thaw with the seasonal freeze thaw cycle. This would take the form of the waterlogged block appearing as if it shared the block space with a block of ice.

### Why would this feature be useful?

When bodies of water freeze in winter waterlogged blocks such as seagrass stay as water, making the whole frozen body of water patchy. Having these blocks ice over as well would help make winter more immersive when living near water.

**Comment by Forstride** [comment]
We don't change how water freezing actually works.  We only change the temperature that it checks for so it works with seasons.  And even if we did change how freezing works, I don't think it'd be a good idea to forcibly remove blocks (Even if it's just stuff like seagrass or kelp), cause that's the only way freezing over waterlogged plants would work...It's not feasible at all for us to completely overhaul how they work just so it looks like the plants are frozen.
