### ISSUE TITLE
snow bug not melting globally

### ISSUE THREAD

**Issue by Nurian08** [Glitchfiend/SereneSeasons#479]
### What's the issue you encountered?

Hello everybody. I know it might be a bit boring, but I wanted to give modders some suggestions to add to this amazing mod.

(disregard any grammatical errors, as English is not my mother tongue)

1- Well, recently, I did some tests and realized that after winter the snow in regions not carried by our character doesn't melt, and only melts when we get close, so I think it would be interesting to add global snowfall and melting to the mod as we enter spring.

### How can the issue be reproduced?

- Let's go:

 - Let winter come and have its snowfall
 - Walk around the world to distant regions of the world while it is snowing (this will cause snow to fall in regions that are not constantly loaded)
 - Wait for winter to pass
 - And finally note that in distant regions that are not constantly loaded, the snow does not melt and stays there (taking away the player's immersion)

### Mod Version

1.20.1

**Comment by Forstride** [comment]
We don't have any current plans to implement this, and there's already a long-standing issue open for this anyway (#256)
