### ISSUE TITLE
Being able to change the size of stations

### ISSUE THREAD

**Issue by Nurian08** [Glitchfiend/SereneSeasons#480]
### Overview

My suggestion is to add an option to be able to increase the size of the stations as much as we want, even to realistic sizes, with each station lasting 3 months or even to values ​​that we want, this could bring flexibility to new players who want play with this mod.

### Why would this feature be useful?

This would bring more flexibility to the mod, potentially bringing in more players as it could be used both in RPs for YouTubers and series, as well as bringing a more realistic look to the mod.

**Comment by Forstride** [comment]
I assume stations is a bad translation of seasons?  Anyway, you can already change the length in the config.  Anything extremely long is likely going to desync at some point though, but we want to add a real-time sync option in the future that would work off of the local system time of the player/server.
