### ISSUE TITLE
Mod doesn't affect River biome

### ISSUE THREAD

**Issue by sergionicolini** [Glitchfiend/SereneSeasons#487]
### What's the issue you encountered?

Mod doesn't affect River biome

### How can the issue be reproduced?

Example during winter it snows in the plain biome but in the river biome it doesn't.

### Mod Version

10.0.0.2

**Comment by Forstride** [comment]
It's not supposed to, otherwise you'd have snow in the rivers running through the middle of jungles and deserts too

**Comment by sergionicolini** [comment]
in fact its a bug
in my world during winter it snows on plain biome but when i cross a river it rains so the biome river for some reason is not affected by the mod which is a problem

**Comment by Forstride** [comment]
Maybe I phrased it poorly, but the river is *intentionally* blacklisted.  It's not a bug
