### ISSUE TITLE
N/A:Bonemeal has serious bugs in snowplains

### ISSUE THREAD

**Issue by nitbe** [Glitchfiend/SereneSeasons#489]
### What's the issue you encountered?

forge 1.20.1 9.0.046
when i set out of season crop behavior=2,using bonemeal in snowfields will destroy block
![R9~3V$6G$LDT`%5%SXC827E](https://github.com/user-attachments/assets/6b7f1118-5a10-4020-92e6-31cdc98fa37f)

### How can the issue be reproduced?

*in snowplains
*config=>serensseason=>fertility=>out_of_season_crop_behavior = 2
*ues bonemeal in the dirt

### Mod Version

1.20.1-9.0.0.46

**Comment by Forstride** [comment]
We do not support 1.20.1
