### ISSUE TITLE
[Wish] Backport to 1.12 and 1.12.1

### ISSUE THREAD

**Issue by SkullbocksDE** [Glitchfiend/SereneSeasons#49]
Hi Glitchfiend,

would you mind to backport your mod to 1.12 and 1.12.1?

A user asked if I could hook with my mod into yours, but my mod supports MC from 1.12 to 1.12.2. It would be a bit sad for other users, if I would drop the other versions.

Best regards,
Mike

**Comment by Forstride** [comment]
Probably not gonna happen.  There's really no need to support 1.12 and 1.12.1 anymore, seeing as everyone is using 1.12.2
