### ISSUE TITLE
Rain does not render in dry biomes during wet season

### ISSUE THREAD

**Issue by IStingBees** [Glitchfiend/SereneSeasons#490]
### What's the issue you encountered?

Rain does not render in dry biomes during wet season. However, you can still see water dropping from the leaves of the trees.

### How can the issue be reproduced?

Install mod, Set season winter, Go to Dry biome, Set weather to rain, observe

### Mod Version

1.20.1

### Additional information

I know older versions are not supported, but if truly a reproducible bug, then it breaks a core feature of the mod, making it unusable for people who want basic seasonal functions.

**Comment by Forstride** [comment]
We do not support older versions of the mod, regardless of whether there's a reproduceable bug or not

**Comment by IStingBees** [comment]
That wasn't the main qualifying factor in my statement. A bug that needs to be fixed obviously needs to be reproducible. The issue is the bug is a problem in the core feature of the mod. So the reply should be "regardless of whether there is a major bug or not". Small correction.
