### ISSUE TITLE
Compatibility with the simple clouds mod.

### ISSUE THREAD

**Issue by LordSeabass** [Glitchfiend/SereneSeasons#506]
### Overview

The simple clouds mod overhauls MC's normal weather system making weather localized and as a result snow doesn't build up on the ground during the winter season.

here is a link to the mod page [Here](https://modrinth.com/mod/simple-clouds)

here is my compatibility request in the Simple Cloud's github [Here](https://github.com/nonamecrackers2/simple-clouds/issues/35)

### Why would this feature be useful?

This feature would be good to have as it would make the game more immersive for players using these 2 mods together

**Comment by Forstride** [comment]
Considering they add localized weather, the compatibility would definitely need to be on their end.  We have an API that they can hook into though.
