### ISSUE TITLE
[1.20.1 IMMEDIATE HELP NEEDED!] newest version season set command does not change season

### ISSUE THREAD

**Issue by vinnyg0621** [Glitchfiend/SereneSeasons#507]
### What's the issue you encountered?

when I type in command "/season set mid_autumn" and I have the gamerule doSeasonCycle set to "false", nothing happens.

### How can the issue be reproduced?

1. enter a new world
2. enable cheats
3. set gamerule doSeasonCycle to false
4. type command /season set mid_autumn

### Logs

https://mclo.gs/Yn5QOKL

### Mod Version

9.1.0.0

### Additional information

is there anything i'm doing wrong??
i really need the season to match my IRL season

also on latest MinecraftForge version

**Comment by vinnyg0621** [comment]
i need help - the /season command doesn't do anything anymore! 😓

**Comment by MineKingTop** [comment]
Hey, so I had the same issue, just remove Serene Season Fix, it bugs the command.

**Comment by vinnyg0621** [comment]
oh thanks, that worked. they should fix it too
