### ISSUE TITLE
Leaves are decaying in all seasons.

### ISSUE THREAD

**Issue by Darkfighter1306** [Glitchfiend/SereneSeasons#508]
### What's the issue you encountered?

Since I have downloaded Serene Seasons on my server (Fabric 1.21.1 0.16.7). The leaves on top of trees disappear, but also player placed leaves. I didnt change anything in the config or in the server settings. I also dont have any fast decay leaves mods. I have tried to remove everything and just restart the server again with a new config. But that doenst seem to work. I had this issue on 10.0.0.6 and atm at 10.1.0.1.
[2024-10-23_22 24 55](https://github.com/user-attachments/assets/d95042d7-2297-4e3e-8fb4-98aba26a381b)

### How can the issue be reproduced?

N/A

### Mod Version

10.1.0.1

**Comment by Forstride** [comment]
Serene Seasons doesn't affect leaf decay at all
