### ISSUE TITLE
Crash after 10 minutes of playing. (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by AndrewDelnik** [Glitchfiend/SereneSeasons#514]
### What's the issue you encountered?

After 10 minutes playing, game crash and launcher shows me this message:
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'boolean sereneseasons.season.SeasonHooks.coldEnoughToSnowSeasonal(net.minecraft.world.level.LevelReader, net.minecraft.core.Holder, net.minecraft.core.BlockPos)'

### How can the issue be reproduced?

I suspect that the error will occur after about 10 minutes in any world. 

The error is probably related to the mod sheet, and more specifically the Terralith mod, which affects the generation of the world.

### Logs

https://gist.github.com/AndrewDelnik/5e9853d19214a5bef9015d7ca5c98ef9

### Mod Version

10.2.0.1

### Additional information

Mod List:
		Name Version (Mod Id)

		Additional Placements 2.1.0 (additionalplacements)
		AdoraBuild: Structures 2.8.0 (adorabuild_structures)
		AmbientSounds 6.1.3 (ambientsounds)
		Ametrin API 0.2.7 (ametrin)
		Animal Feeding Trough 1.1.3 (animal_feeding_trough)
		Architectury 14.0.4 (architectury)
		Attack Through Grass 2.0.2 (atg)
		Bagus Lib 1.21.3-14.0.2 (bagus_lib)
		Block Variants 6.2 (block_variants)
		Cave Spider Spawn 1.2 (cavespiderspawn)
		Chested Companions 1.3.1 (chestedcompanions)
		ChoiceTheorem's Overhauled Village 3.5.4 (ctov)
		Cloth Config v16 API 16.0.141 (cloth_config)
		Collective 7.89 (collective)
		CreativeCore 2.12.22 (creativecore)
		Edibles 4.4 (edibles)
		EnchantWithMob 1.21.3-21.3.1 (enchantwithmob)
		Ex Machina 0.4.0.1 (exmachina)
		FlowingFluids 0.3.1 (flowing_fluids)
		Forgified Fabric API Base 0.4.42+d1308ded19 (fabric_api_base)
		Forgified Fabric BlockView API (v2) 1.0.10+9afaaf8c19 (fabric_block_view_api_v2)
		Forgified Fabric Renderer API (v1) (CaffeineMC) 4.0.3+63dbf70448 (fabric_renderer_api_v1)
		Forgified Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 (fabric_rendering_data_attachment_v1)
		GeckoLib 4 4.7.1 (geckolib)
		GlitchCore 2.2.0.4 (glitchcore)
		Grabby Mobs 1.6 (grabbymobs)
		Healing Campfire 6.1 (healingcampfire)
		Hot Kettles 1.1.1+mc1.21.3 (hotkettles)
		Hunters Return 1.21.3-20.3.3 (hunters_return)
		Iris 1.8.0+mc1.21.3 (iris)
		Iron Door Key 1.2 (irondoorkey)
		Items Displayed 2.1.1 (items_displayed)
		Lithostitched 1.3.8 (lithostitched)
		Minecraft 1.21.3 (minecraft)
		More Red 0.0NONE (morered)
		Naturally Charged Creepers 3.5 (naturallychargedcreepers)
		NeoForge 21.3.56 (neoforge)
		Now Playing 1.5.10 (now_playing)
		Reg's More Foods 1.2.0+1.21.2+forge (rmf)
		RevampedWolf 1.21.3-14.0.0 (revampedwolf)
		Serene Seasons 10.2.0.1 (sereneseasons)
		Sit 1.3.5 (sit)
		Skeleton Horse Spawn 4.0 (skeletonhorsespawn)
		Snow Under Trees 1.4.6 (snowundertrees)
		Sodium 0.6.0+mc1.21.3 (sodium)
		Sound Physics Remastered 1.21.3-1.4.6 (sound_physics_remastered)
		Spiders Produce Webs 3.5 (spidersproducewebs)
		Structory 1.3.7 (structory)
		Suspicious Zombification 1.2.6 (suszombification)
		Terralith 2.5.6 (terralith)
		Trample Everything 3.5 (trampleeverything)
		Ultimate Car Mod 1.21.3-1.0.33 (car)
		Ultimate Plane Mod 1.21.3-1.5.5 (plane)
		Unlit Campfire 1.21.3-3.2.0.1 (unlitcampfire)
		Zombie Horse Spawn 5.1 (zombiehorsespawn)

_No response_

**Comment by Forstride** [comment]
This is an issue with the Snow Under Trees mod.  They need to update their compatibility for Serene Seasons (Unless they already did and you're not using the latest version of it).

**Comment by AndrewDelnik** [comment]
Oh, thank you!)
