### ISSUE TITLE
Seasons should not affect the twilight forest

### ISSUE THREAD

**Issue by EnderiumSmith** [Glitchfiend/SereneSeasons#52]
There is no config for dimensions but they affect other dimensions like the twilight forest.

**Comment by danikk14g** [comment]
this can also affect Aroma1997's dimension, which is commonly used for solar powergen, a blacklist dimid option in the config would solve this.

**Comment by EnderiumSmith** [comment]
a whitelist would be bettter

**Comment by Brycey92** [comment]
Why not both?

**Comment by Forstride** [comment]
Just gonna close this and use this as the main issue for the dimension whitelist: https://github.com/Glitchfiend/SereneSeasons/issues/10
