### ISSUE TITLE
Winter Snow

### ISSUE THREAD

**Issue by Periwinkl3** [Glitchfiend/SereneSeasons#56]
Snow gets left unmelted in the chunks that are far away and it is immersion breaking coming back to those chunks in the summer. I find myself just standing in one place in the new season just to wait for the snow to melt. Is there anyway a tick rate can be changed or something along those lines that will make snow melt quicker once it hits Spring?

**Comment by Forstride** [comment]
Just gonna close this since someone else had opened an issue for the same thing, and it's gained more traction: https://github.com/Glitchfiend/SereneSeasons/issues/85
