### ISSUE TITLE
No config option for changing subseason length

### ISSUE THREAD

**Issue by rocksrocksrocksrocksrocks** [Glitchfiend/SereneSeasons#57]
Unless I'm a complete idiot, I'm unable to  find any way of changing the subseason length in the Config menu in pretty much all the releases. It states on the Wiki that this is a changeable option yet I am unable to find it and I've searched in all the config sections of all the mods that I've got installed in case it migrated.

**Comment by Forstride** [comment]
It's not in the GUI menu currently.  You have to manually edit the config files.

**Comment by rocksrocksrocksrocksrocks** [comment]
Jeeesus that's a pain and a half. Maybe a suggestion for the future would
to be to have this added to the GUI? Cheers.
