### ISSUE TITLE
No able to set crop fertility for a seed with a meta id

### ISSUE THREAD

**Issue by LukeSkywaIker** [Glitchfiend/SereneSeasons#62]
Maybe i just dont know the correct syntax for it, but setting barley seeds from natura in cropfertility.cfg doesnt work this way. (wont grow + no tooltip). 

S:spring_seeds <
natura:overworld_seeds:0
>

Thank you in advance!

**Comment by Ash70** [comment]
Same applies to rustic tomatoes and chili peppers, however they do not have a metaID.

**Comment by lobbienjonsji** [comment]
Same case for all cuisine crops.

**Comment by Forstride** [comment]
Closing this as it's no longer relevant in 1.14/1.15
