### ISSUE TITLE
Day length not matching config.

### ISSUE THREAD

**Issue by MessyConfessor** [Glitchfiend/SereneSeasons#63]
Currently, I've got the time settings for my seasons like so:

> "time settings" {
>     # The duration of a Minecraft day in ticks [range: 20 ~ 2147483647, default: 24000]
>     I:"Day Duration"=384000
> 
>     # The duration of a sub season in days [range: 1 ~ 2147483647, default: 7]
>     I:"Sub Season Duration"=21
> }

By my math, that should make a day/night cycle last 5 hours and 20 minutes. However, when I start a new world and jaunt around a bit, the cycle is still only lasting about 20 minutes.

Are there any known mod conflicts that cause this? Alternatively, I see that there's another mod with a similar function (except without the season mechanic), do you guys happen to know if it's compatible with yours/if installing them side by side will allow me to control the day length like I'm trying to do?

Other mod is here: https://minecraft.curseforge.com/projects/extended-days

**Comment by Forstride** [comment]
This doesn't actually change the length of days.  It only affects how long the seasonal cycle lasts in relation to them.  It's meant to be used in conjunction with a mod like Extended Days.

**Comment by MessyConfessor** [comment]
Oh, my bad. I guess I misunderstood the config's grammar. Thank you, I'll get Extended Days.
