### ISSUE TITLE
[Suggestion] Narrower Crop Fertility (by Sub-Season)

### ISSUE THREAD

**Issue by MessyConfessor** [Glitchfiend/SereneSeasons#68]
I'm making a pack with Mystical Agriculture, and I thought it would be good if I were able to narrow some of the more valuable resource crops (say, Diamonds and above) to a sub-season instead of a full season, as a balancing measure. Would it be possible to add in a config option to make crop fertility more granular like this?

**Comment by Forstride** [comment]
Probably not gonna happen.  Sub seasons are really only meant to be cosmetic and not affect gameplay that much, and we'd have to overhaul how the crop tooltips appear if we were to add sub season support.
