### ISSUE TITLE
[Questions] RE Agricraft & Season Display

### ISSUE THREAD

**Issue by 99Blocks** [Glitchfiend/SereneSeasons#69]
Hi there,

Loving the look of this mod but I wanted to check a couple of things before I dive into devving my new pack with it included.

First up; How does it interact with Agricraft and are cropsticks/nbt values for agri-crops handled ok?

Secondly; Is there a way to display what season it is and maybe even what day of the season somewhere on the screen or in the inventory GUI/with a keybind?

Many thanks, sorry for the post here but I couldn't see anywhere to post a comment directly asking.

**Comment by Forstride** [comment]
Agricraft doesn't work with it, as their crops do not use the same functions and implementations that crops from vanilla and most other farming mods do.  There's nothing we can do about it to fix it on our end.

No, there's no seasonal GUI display, although we've gotten a few requests for it, so we'll probably add something in the future, but it's not a priority.
