### ISSUE TITLE
Unable to grow botania flowers with bonemeal in winter despite allowed crop

### ISSUE THREAD

**Issue by esotericist** [Glitchfiend/SereneSeasons#72]
Even with `botania:flower` added to all four seasons, I cannot bonemeal Botania mystical flowers in winter to get the double version. As soon as spring hit, I was able to do so.

**Comment by Forstride** [comment]
So, previously only seeds were allowed to be listed in the config file, but I've fixed it so that you can add blocks as well, for growable crops/plants that don't have seeds, such as saplings, or the Botania flowers in this case.  Update will be live soon on CurseForge.
