### ISSUE TITLE
Add dynamic trees compatibility

### ISSUE THREAD

**Issue by beanaboston** [Glitchfiend/SereneSeasons#73]
I noticed you added compatibility for birch trees.

Dynamic oak trees work good, but dynamic birch trees do not. I'm guessing it is due to the way you have to have birch trees change compared to the regular trees. It'd be great to have compatibly added for those trees.

**Comment by Forstride** [comment]
Are you using the stable build of Dynamic Trees or the dev build?  The creator of it said that it *should* work if you use the dev build, so give that a try.

**Comment by beanaboston** [comment]
All right I'll try that later. Thanks!
