### ISSUE TITLE
Non-seed Crop Fertility Clarifications

### ISSUE THREAD

**Issue by MessyConfessor** [Glitchfiend/SereneSeasons#74]
I see that you guys have added fertility settings for non-seed crops, but I wasn't sure about the limitations, so I hope I'm not being out of line asking for some clarification here. Specific examples:

1. Can I set fertility for "minecraft:reeds" or "minecraft:cactus" to keep sugar cane and cactus from growing outside of specific seasons?
2. If I set fertility for "harvestcraft:pamavocado", can I keep tree-hanging crops like avocados from ripening outside of season?
3. If I set fertility for, say, "minecraft:sapling", can I prevent new trees from maturing in winter?
3a. Am I able to use metadata to set fertility for saplings individually, such that different saplings will mature in different seasons?
4. Will this work for log-style blocks that go through a ripening cycle, like Pam's cinnamon tree ("harvestcraft:pamcinnamon") or chorus flowers?

Hope this isn't too much. Just trying to feel out the borders of the new mechanic.

**Comment by Forstride** [comment]
Ok, so, blocks *have* to implement IGrowable for it to work, *and* they have to implement the proper Forge hooks that we use to cancel the growth event.  The latter is a problem with a lot of mods, as some of them just use old vanilla code from before Forge added the hooks.

There's really not a lot we can do to cancel growth events for mods that don't use Forge hooks, even *with* specific implementation.  Maybe in the future we can set up our own hooks (If that's even possible.  I'm really not that advanced of a coder), and other mods could just implement those, but yeah.

Metadata isn't supported yet, and I'm really not sure when it'll be added.  Our lead coder has been away from modding for a while, so I've kind of just being scraping by and relying on other peoples' help (The whole crop fertility thing was mostly done by someone else).
