### ISSUE TITLE
Seasons not changing

### ISSUE THREAD

**Issue by ClockyVaudeville** [Glitchfiend/SereneSeasons#75]
I have pam's, serene seasons, ambient sounds and better foliage installed with no texture packs, yet for me the seasons seem to not be changing, my crops for pam's which are governed by the seasons aren't growing. In short my game seems to be stuck on spring, if I want different seasons I have to do it manually. I went afk for an hour or so in my inventory screen in hopes that in the time it took for me to come back the seasons would have changed, and this is after having that same world open and actively playing for three or four hours beforehand. When I came back the season was still spring and the season clock hadn't changed. Can anyone help me figure out why this is happening?

**Comment by Forstride** [comment]
Can't really help you, as it sounds like a problem that only exists on your end.
