### ISSUE TITLE
Desert Biome no longer growing some vanilla crops?

### ISSUE THREAD

**Issue by minakitty** [Glitchfiend/SereneSeasons#76]
I set up my base in a desert biome, and ported in sugar cane, wheat, potatoes, carrots and beets from a nearby village.  The sugar cane and wheat are growing fine, but the others are not growing at all.  Even after three years in game the entire field is still at 0% growth on those crops.  I've tried replanting samples of them at random times in case it was just a glitch, but it seems more than that.  If it's just 'that's how deserts are', that's fine, but I couldn't find anything documented about this 'feature'

**Comment by Forstride** [comment]
Desert biomes (As well as jungle and other tropical biomes) can only grow summer crops.

**Comment by minakitty** [comment]
Could the page on tropical seasons on the wiki be updated to explain this, please?

**Comment by Forstride** [comment]
I added an additional page for Crop Fertility earlier today that explains it.

**Comment by minakitty** [comment]
Awesome, that does clear things up ... also as an experiment I started adding greenhouse glass (that stuff is expensive to craft!) and found out that at least on beets so far, so likely the others, it is allowing growth in Spring. Uncertain if that's an expected outcome (since it seemed the greenhouse is supposed to simulate keeping things warmer, and nothing would be warmer than summer) but at this point it seems to be working
