### ISSUE TITLE
Issue with the weather renderer

### ISSUE THREAD

**Issue by Azzmurr** [Glitchfiend/SereneSeasons#77]
So, I have a issue with the weather renderer if this mod is installed, as well as the mod that adds better render for snow and rain (Fancy Block Particles). If in normal biome there will be winter, then with this mod all the same rain will fall, but if it is turned off, snow will fall.

## Forge Version (e.g. 2604): 2756

![2018-08-19_14 51 56](https://user-images.githubusercontent.com/25296625/44308603-7282f200-a3c1-11e8-80d2-bfc7827d3214.png)
![2018-08-19_14 51 46](https://user-images.githubusercontent.com/25296625/44308604-7282f200-a3c1-11e8-8085-d8b1ee0c5f6f.png)

**Comment by Forstride** [comment]
There's probably nothing we can do.  They likely override the same weather rendering stuff we do (We have to change how snow and rain rendering works to take seasons into account).  If anything, they'd have to add support on their end, as they're changing a lot more than we are.
