### ISSUE TITLE
Oak and birch don't change visually when using resource pack

### ISSUE THREAD

**Issue by darthvader45** [Glitchfiend/SereneSeasons#83]
I am currently using the John Smith Legacy resource pack for 1.12.2, and noticed the oak and birch leaves don't seem to change visually, though the break particles show up as the right color.  Could this be fixed, and if it requires editing the resource pack, what textures would I need to add?

**Comment by HogeliBogeli** [comment]
I have the same problem including vines not changing colors. Same resourcepack in 1.12.2. I'm using Optifine with Swamp Colors turned on. Playing on a LAN world, I'm the host. My friend is also using a resourcepack, but he can see the colors changing.

**Comment by darthvader45** [comment]
I'm playing in singleplayer and have this issue.  It's rather annoying.  You should be able to reproduce this by using the resource pack I mentioned in dev.

**Comment by Forstride** [comment]
It has something to do with OptiFine and how they handle custom color maps from texture packs.

I'm not sure if there's any way we can fix it, aside from maybe making it so the mod is required to load after OptiFine, but that might cause even more issues.

**Comment by darthvader45** [comment]
If there's no way for even sp614x to fix it, then we may be doomed to no change in leaf color with this resource pack.
