### ISSUE TITLE
Doesn't appear to Work at all

### ISSUE THREAD

**Issue by jredfox** [Glitchfiend/SereneSeasons#84]
Issue: 
the temperature if it shifts doesn't effect biome foliage
it never snowed playing 10 minecraft days
the foliage never changed during fall to orange colors or winter green/brown colors

Biomes are modded yes but, the other seasons mod didn't require hard coded biomes in order to work. This mod appears to be broken.

![2018-09-18_18 17 20](https://user-images.githubusercontent.com/9736369/45721897-87dd6e80-bb6f-11e8-837e-015f39eced1d.png)

**Comment by Forstride** [comment]
I'm not really sure you understand what you're even talking about.  There's nothing in your screenshot that looks out of place either.

If you're having issues, they're likely caused by OptiFine, in which case, we have a thing in the FAQs on our wiki addressing it.

**Comment by jredfox** [comment]
The fact that biome foilage looked like that all year round and the same with all modded biomes your mod is broken

**Comment by liach** [comment]
At least hold a season clock to show what season it is, bro. You should try debug commands too and try in another creative superflat world **with the least mods possible** to confirm it.

**Comment by Forstride** [comment]
You being the only person with this issue, and not providing any useful information aside from saying it "doesn't work" makes your issue invalid.  Do you really think there wouldn't be a handful of similar issues if the mod just didn't work?

**Comment by jredfox** [comment]
I report an issue you investigate it. Saying it works as intended without testing isn't proper. nor is it my job to beta test your mod this is a simple issue report. Have fun being broken I refuse to help a broken mod who throws issues away.

**Comment by liach** [comment]
> I told you 4 issues that was wrong with it

No, there is only one. https://github.com/Glitchfiend/SereneSeasons/issues?utf8=%E2%9C%93&q=author%3Ajredfox+

It is not a specific developer's mod's responsibility to be compatible to other mods, either. Maybe your evil notch lib broke, too.

**Comment by liach** [comment]
I also see `32 mods loaded` in your screenshot, but you did not provide the mods and the versions at all. You should remove optifine to make this bug valid, too.

**Comment by Forstride** [comment]
"Saying it works as intended without testing isn't proper"

We test the mod every time we make a single change to it.

The problem exists solely on your end, whether it's due to a combination of mods interfering with it (Which you never listed), something you changed with the config files, or just a misunderstanding of how the mod works.

It's not my job to magically guess what's causing your problem.  If you can't help yourself in the slightest, why should I waste my time trying to help an arrogant smartass like you?

**Comment by Generalcamo** [comment]
> I report an issue you investigate it.
You act like you are entitled to everything. You have been acting the same way in the Forge, JEI, and even Traverse githubs. Yet you show no effort to actually answer questions and provide reasonable proof other than "it's not _my_ job to fix _your_ mod that has an issue I can't prove."

**Comment by Forstride** [comment]
Just gonna lock this cause I doubt it's gonna go anywhere.  I've read over this guy's history on GitHub, and yeah, he definitely sounds like an entitled brat.  Good luck on your modding endeavors, cause I'm sure you're gonna need it!
