### ISSUE TITLE
*Suggestions* Automatic snow cover

### ISSUE THREAD

**Issue by RomaXYZ** [Glitchfiend/SereneSeasons#85]
I’ll be pretty cool and more realistic if whenever it became winter that the game reloads with snow and ice already on the ground world wide (where it’s applies, for example tropical biomes won’t have this) so that you wouldn’t have to wait for the ice to freeze especially if you travel large distances. Also if whenever winter is over, the world reloads and it melts off the ground where it applies (for ex: plains biomes which usually don’t have frost on the ground would revert to their normal states when winter is over)

**Comment by Brycey92** [comment]
I'd also like to see this.

**Comment by Avatair** [comment]
It is implemented in a PR https://github.com/Glitchfiend/SereneSeasons/pull/31

**Comment by RomaXYZ** [comment]
Are you sure? I've been playing with the mod for some time recently and that feature never works.

**Comment by Brycey92** [comment]
Why was this issue closed if the PR still hasn't been merged?

**Comment by Forstride** [comment]
Because the PR is never going to be merged.  It's out of date, has conflicting files, and the guy that made it was being really hostile afterwards about the license of the mod.  Might as well just close that too at this point

**Comment by Avatair** [comment]
Digging up one year old problems of this kind really upsets my stomach. But vecause my person has been mentioned, I'm forced to answer. Please allow me to correct the last point of your statement.

Never, I repeat, I've NEVER been hostile towards anybody or anything in one or another way. We had an ugly discussion, that is true. But till the end I've remained polite and did my best to avoid things like insulting, cursing or getting personal in some way, no matter what. The topic of this discussion was, nothing more nothing less, a suggestion of one possible solutions to keep this mod updated. But sadly it was perceived as an offence, a hostile takeover or whatever else by some members of the team instead, leading to a terrible escalation. Now I have fully distanced myself from this mod and Glitchfiend and please, Forstide, let's simply forget about all this.

**Comment by Forstride** [comment]
I had forgotten about it.  I was only responding because the one guy brought it up
