### ISSUE TITLE
Enable snow on tropical and hot biomes

### ISSUE THREAD

**Issue by E-daw** [Glitchfiend/SereneSeasons#86]
Would it be possible to add complete book customization? So that you can make it snow in tropical biomws like jungles? Also make it configurable for it to snow in desserts or freeze rivers and oceans?

**Comment by matheusvingadouro** [comment]
just remove the tropical/hot biomes from the config lists and change the temperature with biometweaker

**Comment by Forstride** [comment]
What he said.  This is just a bit too situational of a suggestion to implement.
