### ISSUE TITLE
[Suggestion] Add ability to change any item's texture based on season

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/SereneSeasons#87]
I'm thinking a config-file e.g.
modid:itemid=winter.png,spring.png,summer.png,autumn.png
And textures placed in assets/textures/items/

The idea behind this is to make it possible to have flowers grow, bloom and die so there is less color & life in winter.

**Comment by Forstride** [comment]
That'd probably be way too complex, and for such a relatively minor feature, it's really not worth the hassle.
