### ISSUE TITLE
*Suggestion* Allow snow to fall in Fall an Autumn in certain biomes

### ISSUE THREAD

**Issue by RomaXYZ** [Glitchfiend/SereneSeasons#88]
In the real world, winter in cold regions such as the Russian and Canadian taiga begin much earlier (say October) than in more temperate regions which occur in December or January. My suggestion is, allow it to be customizable when snow begins to fall in certain temperature thresholds. (Say snow begins to fall at the value  .2 which is Taiga at mid Autumn or Mid Spring). That way, snow follows the cold.

**Comment by ichttt** [comment]
You removed a method in the API, which you other mods rely on. Don't do that. Put in a deprecation annotation and give mod authors time to remove their calls to the method.
