### ISSUE TITLE
*Suggestions* Seasons Overley

### ISSUE THREAD

**Issue by Dhannyjsb** [Glitchfiend/SereneSeasons#89]
can you add overlay for season time, like a season clock but, always show on the top screen. ?

**Comment by Deshiba** [comment]
Optional trough configuration, please don't break my immersion.

**Comment by Dhannyjsb** [comment]
I can't find Optional configuration for that.

**Comment by merdinarchfire** [comment]
I think it would be cool if you made a fancy display when the seasons change, like in the middle of the screen. maybe or even in one of the corners? would be a really nice touch. :)

**Comment by Deliphin** [comment]
While it's not as fancy as what you're suggesting, the mod already has an item that works like a Minecraft clock but for serene seasons' seasons.

**Comment by Forstride** [comment]
The Season Clock has been replaced by a new Calendar item that shows the current season/progression a lot more clearly, so I feel like the need for a GUI isn't really necessary anymore, and I'm gonna close this.
