### ISSUE TITLE
[bug] serene seasons causes sand/gravel to fall

### ISSUE THREAD

**Issue by Shivaxi** [Glitchfiend/SereneSeasons#92]
so you know how sometimes sand and gravel and stuff can be generated floating?  and wont fall?  until updated by like say placing a torch or another block next to it.  serene seasons seems to do this "update" check thing automatically, so all sand and gravel now fall if the player is close enough.  note it doesnt work in spectator gamemode though, which is interesting, and was a way to test as i'd fly up to floating sand in spectator, it wouldnt fall or anything, then i switch to either creative or survival, and boom the sand falls

now this could kinda been seen as a feature and a bug lol.  one side its like, oh yay no more floating sand/gravel on generation, hooray.  on the other side, and my side, i have custom generation mods like Ruins and Recurrent Complex that uses the floating sand/gravel "glitch" to effect, for booby traps and stuff inside generated dungeons and structures.  and thats how i noticed it haha, because all the traps were already activated upon these dungeons/structures generating

not 100% sure how its doing that or having that side effect, i imagine it has something to do with updating the chunks in biomes for changing their temperature and stuff and grass/foliage color changes, but that only happens on a season change, and you'll see all the chunks flash and reload.  the bug im talking about though is happening no matter what, no where near a season change
it would be cool if there was some sort of compatibility fix for this in the config if possible

(note:  did try disabling everything in the config, but issue still occurs, just having the mod running period.  also thoroughly tested in controlled environment with only serene seasons running and it's definitely the culprit)

note 2:  thought it would be relevant to point out this was not an issue when serene seasons was part of Tough As Nails, as in 1.11.2 I ran the same structure generation mods with Tough As Nails and never had this issue with the custom structures and dungeons spawning the sand/gravel traps)

**Comment by Shivaxi** [comment]
I'm not sure you read my entire post.  Update are not happening on a season change.  They are happening continuously, all the time, around any player, despite season change or even if the effects are completely disabled.  Again I tested this by flying up to floating sand/gravel in spectator mode, the blocks were fine, no change.  However switching to creative or survival mode would cause all the sand/gravel to then fall after a second or two of being in creative/survival and NEAR the sand/gravel.

And to re-iterate again, this was not an issue at all when seasons were part of Tough As Nails, which accomplished the same with, updating blocks and the colors of grass and trees, etc, without this issue occurring.

**Comment by Forstride** [comment]
I can't recreate this at all, even when changing seasons, making it rain/snow, and switching game modes.  Are you absolutely positive it's not another mod causing this?  Because it really doesn't seem to be caused by Serene Seasons.

**Comment by Shivaxi** [comment]
Yes, 100% sure.  I did notice though it only seems to effect structures generated after terrain generation.  I'm not sure why, but normal terrain like if floating sand spawns in a desert is not effected.  I run Recurrent Complex and Ruins which spawn structures that purposely have floating sand/gravel traps.  Approaching those with Serene Seasons on makes them fall immediately upon getting close.  Turning serene seasons off allows the gravel and sand to float just fine.  I can't explain why it only effects structures spawned in after initial terrain generation, or why the gravel/sand doesn't fall when in spectator mode as I previously mentioned.  It was easy to test by flying around in spectator, finding one of the sand/gravel trap structures, and then going into creative or survival, to see if the sand/gravel would fall.

**Comment by Deshiba** [comment]
Seems like a compat issue then. I'd suggest listing the whole mod list in a screenshot or external text dump site.

**Comment by Forstride** [comment]
Nah I've tried it myself and it does seem to happen with only Serene Seasons and Ruins.  It's a really, really weird issue, as it doesn't even affect naturally generated floating sand.

**Comment by Shivaxi** [comment]
and only in creative/survival mode, doesnt happen in spectator either for some reason.

**Comment by Deshiba** [comment]
Well, spectator makes sense. Mobs don't move either when you load an area in spectator only but start moving when a player loads it.  That's why I think there's another mod that might be the culprit here. Do you have a list of what you use?

**Comment by Shivaxi** [comment]
Forstride just commented above that he tried it himself with just Ruins and Serene Seasons and the bug happens.  We spoke on discord about the issue as well, it's not another mod.

**Comment by Forstride** [comment]
Have you tried it with the very latest version?  There were quite a lot of things changed yesterday that could've potentially fixed it.

**Comment by Deshiba** [comment]
@Shivaxi Sorry, Misread. My mind translated to "doesn't".

**Comment by Shivaxi** [comment]
Confirmed bug is still present in the latest version of Serene Seasons, just tested.
