### ISSUE TITLE
[Suggestion] Config to adjust season lengths

### ISSUE THREAD

**Issue by Andyghandi** [Glitchfiend/SereneSeasons#95]
Hi, I Think a neat option would be to have a config to adjust each season time. I live in south Sweden and there sure is a temperate zone here, but the time there is snow here is about 2 months, and the spring/summer are the longest seasons. So i kinda wanna mimic that. By default, the snowy season in serene seasons are too long for my taste.

**Comment by Forstride** [comment]
The way our season system works can't really support differing lengths for individual seasons.  Sorry
