### ISSUE TITLE
Season length in config doesn't seem to be affecting my server

### ISSUE THREAD

**Issue by TheInventrix** [Glitchfiend/SereneSeasons#96]
I don't know where else to ask this, but: I started a Forge server world with 1.12.2, then shut it down, changed the subseason length, and restarted the server. At the moment, it *should* be taking roughly 3 real-world days per season, as I set it to 70. But it's still going through a season at the default speed of a few hours... Other than this, everything is working perfectly?

I've poked around at the logs and tried changing the config multiple times, restarting the server each time, and I can't figure out if this is a bug or if I just am doing something wrong - and if it's the latter, what the heck I should be doing differently to fix it.

**Comment by Forstride** [comment]
Are you sure you have the same config on your client as well?

**Comment by TheInventrix** [comment]
> Are you sure you have the same config on your client as well?

Oh, dammit. No, I don't, thank you so much!
