### ISSUE TITLE
Snow missing

### ISSUE THREAD

**Issue by Nikslg** [Glitchfiend/SereneSeasons#98]
I was testing out this mod, and so far it was beloved by people on the server that I was managing.

However, there are some compability issues or so it seems.
We have [Weather2](https://minecraft.curseforge.com/projects/weather-storms-tornadoes?gameCategorySlug=mc-mods&projectID=237746) mod, to imitate wind, sandstorms, tornadoes and etc.
And during the winter, Snow doesnt seem to "fall".
We see Water freezing, but no snow layers on the ground.
Not sure if it's working the way it is supposed to, but I heard that usually snow should generate.

**Comment by Forstride** [comment]
They likely still don't support Serene Seasons, and it's not something we can fix on our end.
